### ISSUE TITLE
(personal preference?) Empty {} should be kept on separate lines

### ISSUE THREAD

**Issue by sjrd** [olafurpg/scalafmt#105]
Original:
```scala
abstract class HTMLTableHeaderCellElement extends HTMLTableCellElement {
}
```

Scalafmt:
```scala
abstract class HTMLTableHeaderCellElement extends HTMLTableCellElement {}
```

I would like the input to look like this:
```scala
abstract class HTMLTableHeaderCellElement extends HTMLTableCellElement {
}
```

Using
* 0.1.1
* default

**Comment by olafurpg** [comment]
It's not a problem to fix this, but I could perhaps explain why you want to keep that newline?

**Comment by sjrd** [comment]
Good question. I don't have any strong feelings about this. I just feel like if you open a brace, you should always go the next line, and the closing brace should be on its own line. It's mostly a consistency argument.

But it's really not a priority. In fact our coding style encourages *not* to write the `{}` at all in that case.

**Comment by olafurpg** [comment]
My issue is that I imagine this can sometimes produce undesirable output, so I prefer to keep it hidden behind a flag. What if the original code is `{}`, should the formatter insert a newline?

**Comment by olafurpg** [comment]
Since this is not a priority I'll keep the current implementation. Don't hesitate to reopen if it starts bugging you.
