### ISSUE TITLE
[Scala.js-specific] = js.native should always be kept on the same line

### ISSUE THREAD

**Issue by sjrd** [olafurpg/scalafmt#108]
Note that this is not a question of preference of the Scala.js style guide. It should apply equally to all style guides, but it's specific to Scala.js code. The `= js.native` is a very special beast.

Original:
```scala
  def uniform4fv(location: WebGLUniformLocation, v: Float32Array): Unit = js.native
```

Scalafmt:
```scala
  def uniform4fv(location: WebGLUniformLocation, v: Float32Array): Unit =
    js.native
```

I would like the input to look like this:
```scala
  def uniform4fv(location: WebGLUniformLocation,
      v: Float32Array): Unit = js.native
```
In all cases, `js.native` should be kept right next to its `=`. Which means that the line should be broken somewhere else.

Using
* 0.1.1
* default

**Comment by olafurpg** [comment]
I made a special case if you use the Scala.js style AND `js.native` is the rhs of an assignment (def/val/var).
