### ISSUE TITLE
NoSuchMethodError: java.lang.Long.hashCode(J)

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#112]
https://www.reddit.com/r/scala/comments/49j5am/scalafmt_010_released_with_sbt_plugin_cli_and/d0t6anf

`Long.hashCode` appeared in Java 8.

**Comment by sjrd** [comment]
You should use `x.##` anyway ;)

**Comment by olafurpg** [comment]
Aha. Lesson learned :smile:
