### ISSUE TITLE
Configuration: spaces inside parentheses `( arg )`

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#116]
Original:
```scala
function(arg)
```

Scalafmt:
```scala
function(arg)
```

I would like the input to look like this:
```scala
function( arg )
```

**Comment by paulp** [comment]
Please also, and from my POV with greater urgency, spaces inside import selectors. Curly braces without whitespace induce claustrophobia.

Currently:
```diff
-import scala.{ Any, Long, Nothing, StringContext, Unit }
-import scala.annotation.unchecked.{ uncheckedVariance => uV }
-import java.{ lang => jl }
-import java.{ util => ju }
-import java.{ io => jio }
-import java.util.{ function => juf }
-import java.nio.{ file => jnf }
+import scala.{Any, Long, Nothing, StringContext, Unit}
+import scala.annotation.unchecked.{uncheckedVariance => uV}
+import java.{lang => jl}
+import java.{util => ju}
+import java.{io => jio}
+import java.util.{function => juf}
+import java.nio.{file => jnf}
```

**Comment by olafurpg** [comment]
Out of curiosity, is there any well documented Scala style guide that supports adding spaces like this? I know it's supported in scalariform and clang-format but I don't see it in the official Scala, Scala.js, Spark or Twitter style guides.

It's straightforward to fix this issue but each new configuration option adds a burden on scalafmt developers and users. I like clang-format's approach for this http://clang.llvm.org/docs/ClangFormatStyleOptions.html#adding-additional-style-options

cc/ @cvogt

**Comment by dwijnand** [comment]
FWIW it's also a supported as an opt-in in IntelliJ's code style formatting.

**Comment by olafurpg** [comment]
I've added 3 flags for 0.2.2

```
--spacesInParentheses
--spacesInSquareBrackets
--spacesInImportCurlyBraces
```

following clang-format naming convention.

**Comment by olafurpg** [comment]
I changed my mind and decided to only add `--spacesInImportCurlyBraces`. I would hate it if scalafmt induces claustrophobia on @paulp 😜 

The other two have not been properly followed up on since I was asked to support them. It's possible to revert f10ee86a118fa8354787eff53206e17b764809cb in case we later decide to support those styles.

**Comment by cvogt** [comment]
@olafurpg our internal coding style for a significantly sized code base at @xdotai would require both `--spacesInParentheses` and `--spacesInImportCurlyBraces`. And personally, I find method calls with spaces inside of parens much more readable.

**Comment by cvogt** [comment]
So +1 for bringing --spacesInParentheses back. However you may want to distinguish calls from signatures.

**Comment by cvogt** [comment]
@olafurpg Just trying scalafmt for a project. Not having `spacesInParentheses` is a blocker for me. Could we bring this back pretty please :)?
