### ISSUE TITLE
some indentation of long, nested types

### ISSUE THREAD

**Issue by cvogt** [olafurpg/scalafmt#117]
Original:
```scala
val x:FooBarrrrrr[BaaaaaaaaaaaazBazzz[String, Option[List[Either[Int, Option[String]]]]]
```

Scalafmt (this is a guess):
```scala
val x: FooBarrrrrr[BaaaaaaaaaaaazBazzz[String, Option[List[Either[Int, Option[String]]]]]
```

I would like the input to look like this (roughly):
```scala
val x: FooBarrrrrr[
  BaaaaaaaaaaaazBazzz[
    String,
    Option[ List[
        Either[ Int, Option[String] ]
 ]]]
```

**Comment by olafurpg** [comment]
0.1.3 will make some changes to how type parameters are formatted, [some example tests](https://github.com/olafurpg/scalafmt/blob/6c4e5165bcbfa3a932cc112d7e87a1e919fcaf99/core/src/test/resources/default/DefDef.stat#L42)

Please give it a try and see how it feels, we can iterate on this in future releases.

**Comment by olafurpg** [comment]
See #116 for the spaces around arguments. My best bet is that I'll work on it somewhere around 0.2.x.
