### ISSUE TITLE
Files in Scalding hang

### ISSUE THREAD

**Issue by ianoc** [olafurpg/scalafmt#127]
Original:
```scala
 /**
   * If any errors happen below this line, but before a groupBy, write to a TypedSink
   */
  def addTrap[U >: T](trapSink: Source with TypedSink[T])(implicit conv: TupleConverter[U]): TypedPipe[U] =
    TypedPipeFactory({ (flowDef, mode) =>
      val fields = trapSink.sinkFields
      // TODO: with diamonds in the graph, this might not be correct
      val pipe = RichPipe.assignName(fork.toPipe[T](fields)(flowDef, mode, trapSink.setter))
      flowDef.addTrap(pipe, trapSink.createTap(Write)(mode))
      TypedPipe.from[U](pipe, fields)(flowDef, mode, conv)
    })
```

Scalafmt:
None it hangs

I would like the input to look like this:
I'd just like it to terminate

Using
* 0.1.3

**Comment by olafurpg** [comment]
I guess this snippet is taken from [TypedPipe.scala](https://raw.githubusercontent.com/twitter/scalding/develop/scalding-core/src/main/scala/com/twitter/scalding/typed/TypedPipe.scala)? I can reproduce the hanging behaviour on 0.1.3 but not on my 0.1.4 branch, which I hope to release later today.

**Comment by ianoc** [comment]
@olafurpg Yep,from there. awesome, i'll give it a whirl again once the new version is out. Thanks for the quick response!

**Comment by olafurpg** [comment]
Just released 0.1.4, it should sync with maven in a few minutes. So far, I've only tested against the Scala.js repo to find bugs and hanging behaviour. Soon I plan to enable those tests for [a whole bunch of more projects](https://github.com/olafurpg/scalafmt/blob/master/core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala#L51).

**Comment by olafurpg** [comment]
FWIW, I ran scalafmt on all of twitter/scalding and got the following results:


Formatter timed out: 6

https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/macros/impl/TypeDescriptorProviderImpl.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/typed/BijectedSourceSink.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/typed/GeneratedFlattenGroup.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/typed/Grouped.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-serialization/src/main/scala/com/twitter/scalding/serialization/JavaStreamEnrichments.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-serialization/src/main/scala/com/twitter/scalding/serialization/macros/impl/ordered_serialization/providers/ProductOrderedBuf.scala

org.scalafmt.Error$CantFormatFile: 15

https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-commons/src/main/scala/com/twitter/scalding/commons/source/VersionedKeyValSource.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-commons/src/test/scala/com/twitter/scalding/commons/extensions/CheckpointSpec.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/FileSource.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/macros/impl/FieldsProviderImpl.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/serialization/WrappedSerialization.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/typed/LookupJoin.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/test/scala/com/twitter/scalding/bdd/TypedApiTest.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/test/scala/com/twitter/scalding/mathematics/Matrix2OptimizationTest.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/test/scala/com/twitter/scalding/TypedPipeTest.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/test/scala/com/twitter/scalding/LookupJoinTest.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-hadoop-test/src/test/scala/com/twitter/scalding/reducer_estimation/ReducerEstimatorTest.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-serialization/src/main/scala/com/twitter/scalding/serialization/macros/impl/ordered_serialization/runtime_helpers/TraversableHelpers.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-serialization/src/test/scala/com/twitter/scalding/serialization/JavaStreamEnrichmentsProperties.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-thrift-macros/src/main/scala/com/twitter/scalding/thrift/macros/impl/ScroogeInternalOrderedSerializationImpl.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-thrift-macros/src/main/scala/com/twitter/scalding/thrift/macros/impl/ordered_serialization/ScroogeOrderedBuf.scala

Success: 364

I found a lot of similar issues formatting other repos, will work on those for the 0.1.5 release.

**Comment by olafurpg** [comment]
The scalafmt 0.1.5 test suite will include all scalding files except these three, which contain autogenerated code:

https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/typed/GeneratedFlattenGroup.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-serialization/src/main/scala/com/twitter/scalding/serialization/macros/impl/ordered_serialization/providers/ProductOrderedBuf.scala
https://raw.githubusercontent.com/twitter/scalding/7759d9c399896fc4c54be0f2406e047e030d8586/scalding-core/src/main/scala/com/twitter/scalding/macros/impl/TypeDescriptorProviderImpl.scala

I'm still trying to come up with a solution to gracefully handle auto generated code like that.
