### ISSUE TITLE
Assignments should be aligned by Equals sign

### ISSUE THREAD

**Issue by Nutomic** [olafurpg/scalafmt#138]
Original:
```scala
    def address = column[String]("address", O.PrimaryKey)
    def name = column[String]("name")
    def status = column[Int]("status")
```

Scalafmt:
```scala
    def address = column[String]("address", O.PrimaryKey)
    def name = column[String]("name")
    def status = column[Int]("status")
```

I would like the input to look like this:
```scala
    def address = column[String]("address", O.PrimaryKey)
    def name    = column[String]("name")
    def status  = column[Int]("status")
```

Using 0.1.5

**Comment by olafurpg** [comment]
I agree that aligning sequences of statements by certain tokens, like your examples, would be super cool. However, the devil lies in the details. To help me understand your expectations, could you answer these questions:

* Should this feature be enabled globally or only for specific blocks? If enabled for block, how would you enable it? If enabled globally, how would you format the following?

```scala
object A {
  def address = column[String]("address", O.PrimaryKey)
  def name = column[String]("name")
  def abba = "cool"
  @inline
  def iHazAnnotation = 'best

  // what about different mixes of val/var/def with modifiers?
  val x = 2
  final val itGetsTricker = 22222
  var foobar = "kaz"
  def add(a: Int, b: Int): Int = a + b

  // Also align comments?
  val iHaveComment = "value" // this is comment 1
  val meToo = "bananas are the best" // this is comment 2
  val waterloo = 'nocomment

  // how about named arguments?
  function(a = 1,
           baz = "bar",
           kazam = boom)

  // default values?
  def function(a: Int = 1,
               baz: String = "bar",
               kazam: Symbol = 'boom): Int = 2
  def shouldThisAlignWithFunction_? = _
}
```

* Do you only want to align equal signs or do you also want to align by other tokens? If other tokens, which ones? For example, `=>` in pattern matching, opening parenthesis in case class or `extends` in a sealed trait. Hypothetical example:

```scala
sealed abstract class Super
case class A  (a:   Int)           extends Super
case class Ba (baa: Int, a:   B)   extends Super
case class Baa(ba:  Int, baa: Baa) extends Super
```

**Comment by Nutomic** [comment]
Do you also reorder items (ie member declarations) in a class? If not, I'd say this should only be applied to items of the same type that don't have anything between them. Comment alignment would also be nice in that case. I'm not sure about arguments or default values, that's probably stuff for another issue.

I guess it would be pretty nice to align lines that are very similar and close by each other. But those cases seem rather rare. I would totally be fine with just considering the assignment operator for now.

**Comment by olafurpg** [comment]
> Do you also reorder items (ie member declarations) in a class?

Nope. Pure whitespace changes, AST must remain identical.

> align lines that are very similar

Could you be more specific here? For example, what if a def takes arguments or has explicit return type:

```scala
  def address = column[String]("address", O.PrimaryKey)
  def name(str: String) = column[String](str)
  def status = column[Int]("status")
  def statusWithReturnType: Column[Int]  = column[Int]("status")
```

> that's probably stuff for another issue.

I agree, but the implementation will rely on similar mechanics so I was curious to know your opinion :smile:

**Comment by Nutomic** [comment]
That case looks pretty complicated. I would be totally fine with a rule that affects only patterns of `val/var name = something` (so not `name(str: String)`), and only if it fits in one line, and there's nothing in between the affected lines.

**Comment by olafurpg** [comment]
Good, it's become quite narrow then. This should fit well with the alignment of `=>` in pattern matching, which has been requested offline.

I asked the folks on the gitter channel for their opinions on this, would like to get a better understanding of what people think. We'll give it a few days.

**Comment by paulp** [comment]
Hi. I've thought about this subject far more than is healthy. I believe I could write a PhD thesis on it. Exciting to see it being taken seriously. To automatically format my scala code on a continuous basis would be the realization of a long-held dream, still impossible over the absence of the feature being described here.

**Comment by dwijnand** [comment]
I'm also interested in this too.

It's nice to see that at least vertical formatting is preserved (from my 2 minute test).

**Comment by paulp** [comment]
Let me point out some more points of alignment which are very common in scala code, and make a suggestion.
```scala
  val colors = Map (
    "white"   -> white,
    "green"   -> green,
    "yellow"  -> yellow,
    "red"     -> red,
    "blue"    -> blue,
    "cyan"    -> cyan,
    "black"   -> black,
    "magenta" -> magenta
  )
```
```scala
// dependencies
addSbtPlugin("com.eed3si9n"         % "sbt-unidoc"            % "0.3.2")
addSbtPlugin("com.github.gseitz"    % "sbt-release"           % "1.0.0")
addSbtPlugin("com.jsuereth"         % "sbt-pgp"               % "1.0.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-ghpages"           % "0.5.3")
addSbtPlugin("com.typesafe.sbt"     % "sbt-site"              % "0.8.1")
addSbtPlugin("org.tpolecat"         % "tut-plugin"            % "0.4.0")
addSbtPlugin("pl.project13.scala"   % "sbt-jmh"               % "0.2.3")
addSbtPlugin("org.scalastyle"      %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"         % "1.2.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-git"               % "0.8.4")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"           % "0.6.8")
addSbtPlugin("com.github.tkawachi"  % "sbt-doctest"           % "0.3.5")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"          %  "1.1")
```
```scala
  // comments
  final val CAPTURED      = 1 << 16       // variable is accessed from nested function.  Set by LambdaLift.
  final val LABEL         = 1 << 17       // method symbol is a label. Set by TailCall
  final val INCONSTRUCTOR = 1 << 17       // class symbol is defined in this/superclass constructor.
  final val SYNTHETIC     = 1 << 21       // symbol is compiler-generated (compare with ARTIFACT)
  final val STABLE        = 1 << 22       // functions that are assumed to be stable
  final val BRIDGE        = 1 << 26       // function is a bridge method. Set by Erasure
  final val ACCESSOR      = 1 << 27       // a value or variable accessor (getter or setter)
  final val SUPERACCESSOR = 1 << 28       // a super accessor
  final val MODULEVAR     = 1 << 30       // for variables: is the variable caching a module value
  final val IS_ERROR      = 1L << 32      // symbol is an error symbol
  final val OVERLOADED    = 1L << 33      // symbol is overloaded
```
Rather than focusing too much on individual punctuation clusters,

**Comment by paulp** [comment]
Let me point out some more points of alignment which are very common in scala code, and make a suggestion.
```scala
// tuples
val colors = Map (
  "white"   -> white,
  "green"   -> green,
  "yellow"  -> yellow,
  "red"     -> red,
  "blue"    -> blue,
  "cyan"    -> cyan,
  "black"   -> black,
  "magenta" -> magenta
)
```
```scala
// dependencies
addSbtPlugin("com.eed3si9n"         % "sbt-unidoc"            % "0.3.2")
addSbtPlugin("com.github.gseitz"    % "sbt-release"           % "1.0.0")
addSbtPlugin("com.jsuereth"         % "sbt-pgp"               % "1.0.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-ghpages"           % "0.5.3")
addSbtPlugin("com.typesafe.sbt"     % "sbt-site"              % "0.8.1")
addSbtPlugin("org.tpolecat"         % "tut-plugin"            % "0.4.0")
addSbtPlugin("pl.project13.scala"   % "sbt-jmh"               % "0.2.3")
addSbtPlugin("org.scalastyle"      %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"         % "1.2.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-git"               % "0.8.4")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"           % "0.6.8")
addSbtPlugin("com.github.tkawachi"  % "sbt-doctest"           % "0.3.5")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"          %  "1.1")
```
```scala
// comments
final val CAPTURED      = 1 << 16       // variable is accessed from nested function.  Set by LambdaLift.
final val LABEL         = 1 << 17       // method symbol is a label. Set by TailCall
final val INCONSTRUCTOR = 1 << 17       // class symbol is defined in this/superclass constructor.
final val SYNTHETIC     = 1 << 21       // symbol is compiler-generated (compare with ARTIFACT)
final val STABLE        = 1 << 22       // functions that are assumed to be stable
final val BRIDGE        = 1 << 26       // function is a bridge method. Set by Erasure
final val ACCESSOR      = 1 << 27       // a value or variable accessor (getter or setter)
final val SUPERACCESSOR = 1 << 28       // a super accessor
final val MODULEVAR     = 1 << 30       // for variables: is the variable caching a module value
final val IS_ERROR      = 1L << 32      // symbol is an error symbol
final val OVERLOADED    = 1L << 33      // symbol is overloaded
```
And there are quite a number of others. Rather than focusing too much on covering many cases, I suggest hitting only the super common ones from "first principles" and inferring all the rest from the incoming code. If two or more lines have the same token in the same columns, surrounded by whitespace on both sides, then that is a candidate for alignment to preserve. That's likely to be too weak by itself, but it can be strengthened with additional heuristics - especially of course if it's three or more lines with a token in the same position.

**Comment by paulp** [comment]
The sbt example makes for an interesting one because you have `%` and `%%` offering a common alignment anchor. Obviously it's unlikely this can be inferred without help, but I'd say it's worth enumerating some common cases and allowing others to be specified by the user. Another frequent one is  `val`, `def`, and `type`.

**Comment by paulp** [comment]
The text editor plugin I use to manage my alignment is [AlignTab](https://github.com/randy3k/AlignTab) which I suggest bears examination. I actually find myself stuck wedded to sublime text despite many dissatisfactions because I cannot find the capabilities of this plugin in any other environment's alignment tool and I can't give up those forms of alignment. (I acknowledge they probably do exist elsewhere and I just haven't found them yet.)

The ability to left/center/right justify each column individually is one example. The ability to specify minimum distance between columns (especially, to control when there is no whitespace between tokens and when there must be a space) is another.

Here is my configuration in sublime, which is somewhat brutal to make sense of thanks to sublime's insistence on storing everything in json. It does say a lot though about what I've found useful in my long slog through the world's scala code. Let me know if I can clarify the meaning of anything.
```json
{
  "named_patterns" : {
        "first_equal" : " = (?:.*?[^{]$)/f",
        "first_comma" : ", /f",
        "first_colon" : ":/rclf",
          "all_space" : "\\s+/l1l0",
              "hocon" : ": (?:.*?[^{]$)/r1l1l1f",
              "typed" : "[:]/r0c1l1f",
           "bash_var" : "[$][(]|[|][|]|[)]|[#]",
       "sbt_operator" : "[&|@#<+:~]+[=][ ]/r1c1l1",
      "quoted_string" : "[\"](?:[^\"\\\\]|\\\\.)*[\"]",
        "first_arrow" : "(?<!:) [-=][>]/l1c1l1f",
         "sbt_module" : "(?: = | %+ )/lrllclclclcl",
      "align_generic" : "(?: [-=]>(?: |$)| [:+]{1,}= )/l1rf",
         "align_esac" : "(?:[)]|[;][;])/r0c1l1",
               "json" : ":(?!.*[{])/r1c1l1f1",
               "bang" : "[!]/r1c1l1f1",
    "one_line_method" : "[ ][=][ ](?:.*?[^{]$)/l1f",
       "go_interface" : "[()]/r0c0l0l0l0",
     "one_line_class" : " extends |[ ][=][ ]| [{] | [}]$"
  },
}
```

**Comment by paulp** [comment]
Here's an example of aligning around sbt's zoo of operators - no small task.
```
                       name :=  "xyzzy"
                description :=  "xyzzy description"
               organization :=  "org.improving"
                   licenses :=  Seq("Apache-2.0" -> url("http://www.apache.org/licenses/LICENSE-2.0"))
               scalaVersion :=  "2.11.8"
                shellPrompt :=  prompt(name.value)
                logBuffered :=  false
               watchSources ++= sourcesIn(baseDirectory.value / "project")
 initialCommands in console <+= repl
                       test <<= run in Test toTask ""
                  maxErrors :=  10
           triggeredMessage :=  Watched.clearWhenTriggered
```

**Comment by paulp** [comment]
Slightly more ambitiously, it should be possible to infer the missing column of alignment in the example which starts with `final val CAPTURED = ...`. Those lines should be aligned on `=`, `<<`, and `//` all, despite the incoming code failing to align on `<<`.

**Comment by olafurpg** [comment]
I'm happy this issue is getting the attention is deserves.

First, scala.meta cannot yet parse sbt files. Please upvote https://github.com/scalameta/scalameta/issues/358 to convince Eugene this would be a worthwhile feature in scala.meta.

For the sbt and the `colors` Map examples, the common pattern is that they're lists (application arguments, sbt source file statements) of infix applications. How about specifying which infix operators align together as some sort of `Set[Set[Token]]`?

For `val/def`, I believe the most common case is to align by `=` and comments.  Scalafmt could align those tokens if it sees a sequence of statements of same type (e.g. `Defn.Val`, `Defn.Def`), which are not separated by a blank line.  This would ignore differences between statements like annotations or modifiers, is that OK?

As @paulp suggests, this might be a good start from which we could derive a more general solution. Maybe something similar to AlignTab, thanks for the link.

PS. with 0.1.6 out I've started working on 0.2.0, which will make configuration much easier. The currently useless `ScalaStyle` trait will become a `ScalafmtConfig` case class.

**Comment by michalrus** [comment]
@paupl, you *might* get something similar with Emacs’ align-regexp, e.g. http://haskell.github.io/haskell-mode/manual/latest/Aligning-code.html#Aligning-code. :smirk_cat:

**Comment by paulp** [comment]
> How about specifying which infix operators align together as some sort of `Set[Set[Token]]`?

In sbt's case you would not wish to enumerate all possible operators, nor could you do so in a way which wouldn't break with the addition of new ones. You don't necessarily need a full `Token => Boolean` predicate to identify them, but at least something with power equivalent to a regular expression.

**Comment by paulp** [comment]
As an aside, one of the great forms of aggravation in alignment based on regexes is avoiding overreach when the same characters occur with different meaning, e.g.
```scala
def f[A](x: A)(f: A => Int) = f(x) match {
  case 1 => true 
  case 2 => false
}
```
At a lexical/regex level, one can apply heuristics to avoid the `=>` in the function type becoming aligned with the case arrows, but it becomes more and more ridiculous, always misses something, and obfuscates the meaningful portion of the machinery.

**Comment by olafurpg** [comment]
Release 0.2.0 should be live on Maven soon. It contains a basic implementation for token alignment. It can format all examples which were given in this thread. Test suite is [here](https://github.com/olafurpg/scalafmt/blob/2b1f8e674a0db5bb2e27e03974bcc4396b85b456/core/src/test/resources/align/AlignTokens.stat). The [actual implementation](https://github.com/olafurpg/scalafmt/blob/2b1f8e674a0db5bb2e27e03974bcc4396b85b456/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L167) is around 130 lines of super imperative code, I hope to refactor it soon.

You can align by custom tokens OR simply use the default align tokens in the style `defaultWithAlign`, which aligns by `=>`, `->`, `=` assignments, `%` and `%%`. [Here](https://github.com/olafurpg/scalafmt/commit/b990ec78647db1a27621661b4f26265882d1a423#diff-ae5748146f114992c73f16c549cd5332R262) is the diff from formatting all files in scalafmt with  the `defaultWithAlign` style.

You can find documentation for using a custom style or defining custom align tokens in [the user docs](http://olafurpg.github.io/scalafmt/#Configuration).

The docs may be incomplete, don't hesitate to poke at me for more info. Let me know what you think :smile:, I'm especially happy to get more test cases.

**Comment by paulp** [comment]
I can point you at a boatload of test cases, because so much of my code is already aligned. Just run scalafmt on [psp-std](https://github.com/paulp/psp-std) and look at where the existing alignment has been lost.

**Comment by olafurpg** [comment]
Wow, [you must have a really wide display](https://github.com/paulp/psp-std/blob/master/std/src/main/scala/Pstring.scala#L69)! You probably should increase `--maxColumn` to 120. I also see I forgot to align by `extends` in the `defaultWithAlign` style.

I'll see how much time I have to look at it. With 0.2.0 I really need to start writing my thesis, hoping to hand it in around 5 weeks and I haven't started writing yet.

**Comment by paulp** [comment]
Some other things I noticed after running

  `sbt "cli/run --style defaultWithAlign --maxColumn 160 -i -f /g/psp-std"`

from scalafmt 9547de0170. Take your time, I've been waiting enough years that I'm not counting the minutes.

Most of the failures are long lists of type aliases, which should be a trivial fix. Example.
```diff
-  type BinOp[A]           = (A, A) => A // binary operation
-  type OrderRelation[-A]  = (A, A) => Cmp
-  type Relation[-A]       = (A, A) => Boolean
-  type Suspended[+A]      = ToUnit[ToUnit[A]]
-  type ToBool[-A]         = A => Boolean
-  type ToInt[-A]          = A => Int
-  type ToSelf[A]          = A => A
-  type ToString[-A]       = A => String
-  type ToUnit[-A]         = A => Unit
+  type BinOp [A] = (A, A) => A // binary operation
+  type OrderRelation [-A] = (A, A) => Cmp
+  type Relation [-A] = (A, A) => Boolean
+  type Suspended [+A] = ToUnit[ToUnit[A]]
+  type ToBool [-A] = A => Boolean
+  type ToInt [-A] = A => Int
+  type ToSelf [A] = A => A
+  type ToString [-A] = A => String
+  type ToUnit [-A] = A => Unit
```

This next one is a site which would be handled naturally if you inferred alignment from the opening and closing curly braces already being column-aligned (as well as `extends`) but will otherwise frustrate plausible attempts to anticipate it.
```diff
-trait Eq[-A]   extends Any            { def eqv(x: A, y: A): Boolean }
-trait Hash[-A] extends Any with Eq[A] { def hash(x: A): Int          }
+trait Eq[-A] extends Any { def eqv(x: A, y: A): Boolean }
+
+trait Hash[-A] extends Any with Eq[A] { def hash(x: A): Int }
```

Last one is subtly but somewhat dangerously wrong, because the assignments inside the block should not be aligned with the containing function's body: alignment shouldn't jump scope.
```diff
 object Cleaver {
   def apply[R, A, B](f: (A, B) => R, l: R => A, r: R => B): Cleaver[R, A, B] = new Cleaver[R, A, B] {
-    def split(x: R): A -> B = (l(x), r(x))
-    def join(x: A, y: B): R = f(x, y)
-    def join(x: A -> B): R  = f(x._1, x._2)
+    def split(x: R): A -> B                                                  = (l(x), r(x))
+    def join(x: A, y: B): R                                                  = f(x, y)
+    def join(x: A -> B): R                                                   = f(x._1, x._2)
   }
 }
```

**Comment by olafurpg** [comment]
@paulp The last one is an actual bug, see #152.

The first three are fixable with configuration, although it is a bit awkward

```scala

 ollie  ~  dev  psp-std  scalafmt -f foo.scala  // no vertical alignment
object A {
  x match {
    case 1 => 2 -> 2 // this is a comment
    case 11 => 22 -> 22 // another one
    case 111 => 222 -> 222 // third!

    case 1111 => 1111 // Please ignore me, I'm a loner
  }
  trait B extends A
  trait BB extends A

  class B extends A
  class BB extends A

  type C = Int
  type CC = String

  trait Eq[-A] extends Any { def eqv(x: A, y: A): Boolean }
  trait Hash[-A] extends Any with Eq[A] { def hash(x: A): Int }
}

 ollie  ~  dev  psp-std  cat .scalafmt                                                                  master
--alignTokens =;Defn.(Va(l|r)|Def|Type),extends;Defn.*,{;Template,};Template,=>;Case,->;Term.ApplyInfix
 ollie  ~  dev  psp-std  scalafmt -c .scalafmt -f foo.scala // with vertical alignment
object A {
  x match {
    case 1   => 2   -> 2 // this is a comment
    case 11  => 22  -> 22 // another one
    case 111 => 222 -> 222 // third!

    case 1111 => 1111 // Please ignore me, I'm a loner
  }
  trait B  extends A
  trait BB extends A

  class B  extends A
  class BB extends A

  type C  = Int
  type CC = String

  trait Eq[-A]   extends Any            { def eqv(x: A, y: A): Boolean }
  trait Hash[-A] extends Any with Eq[A] { def hash(x: A): Int          }
}
```

There is a bug if you try to align by comments `//`, which I've described in #151

**Comment by olafurpg** [comment]
Also note that #153 causes problems when you want to align top-level classes/traits
