### ISSUE TITLE
Make comments in `.scalafmt` great again

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#151]
`replaceAll("//.*", "")` causes a bug since --alignTokens could be set to `//;.*`

**Comment by paulp** [comment]
Don't punish all the comments for that - configuration files which disallow comments are completely maddening. You can just distinguish between lines which begin `//;` and all the other uses of `//`, right?

**Comment by paulp** [comment]
Also, `#` is better anyway - same suggestion to allow for `#;`

**Comment by olafurpg** [comment]
Good point. Agreed.
