### ISSUE TITLE
Unicode arrows don't align

### ISSUE THREAD

**Issue by lespea** [olafurpg/scalafmt#155]
I can't get unicode arrows to align; even if I override alignTokens in `.scalafmt` with something like `--alignTokens ⇒;Case,=;Defn.(Va(l|r)|Def),→;Term.ApplyInfix,//;.*`.  Ideally scalafmt would align both by default (also the left arrow in for statements should be aligned as well)

Original:
```scala
1 match {
  case 1 ⇒ 1
  case 11 ⇒ 1
}

val m = Map(
  1 → 1,
  11 → 1
)

for {
  a <- List(1)
  aaa <- List(1)
} yield 1

for {
  a ← List(1)
  aaa ← List(1)
} yield 1
```

Scalafmt:
```scala
1 match {
  case 1 ⇒ 1
  case 11 ⇒ 1
}

val m = Map(
  1 → 1,
  11 → 1
)

for {
  a <- List(1)
  aaa <- List(1)
} yield 1

for {
  a ← List(1)
  aaa ← List(1)
} yield 1
```

I would like the input to look like this:
```scala
1 match {
  case 1  ⇒ 1
  case 11 ⇒ 1
}

val m = Map(
  1  → 1,
  11 → 1
)

for {
  a   <- List(1)
  aaa <- List(1)
} yield 1

for {
  a   ← List(1)
  aaa ← List(1)
} yield 1
```

Using
* 0.2.0

**Comment by olafurpg** [comment]
My wild guess is that `//;.*` in the end is the culprit, because of #151. On my 0.2.1 branch I've added unicode symbols and `<-` for generators to the defaultWithAlign style.
