### ISSUE TITLE
Single arg breaking

### ISSUE THREAD

**Issue by sjrd** [olafurpg/scalafmt#160]
Original:
```scala
   implicit class IterableW[+A](it: JSIterable[A]) {
     def iterator(): Iterator[A] =
-      toIterator(it.asInstanceOf[IteratorMethodAccess].bracketCall[JSIterator[A]](iteratorSy
+      toIterator(it
+            .asInstanceOf[IteratorMethodAccess]
+            .bracketCall[JSIterator[A]](iteratorSymbol)())
   }
```

Scalafmt:
```scala
OUTPUT FROM SCALAFMT
```

I would like the input to look like this:
```scala
HOW YOU WANT THE OUTPUT TO LOOK LIKE.
```

Using
* 0.1.x

**Comment by olafurpg** [comment]
I have a working implementation that produces this output:

```scala
implicit class IterableW[+A](it: JSIterable[A]) {
  def iterator(): Iterator[A] =
   toIterator(
       it.asInstanceOf[IteratorMethodAccess]
         .bracketCall[JSIterator[A]](iteratorSymbol)())
}
```

What do you think @sjrd?

These changes were twofold and will impact (positively, IMO) current scalafmt users:

* Newlines inside applications are slightly more penalised if there's no space after opening `(` compared to putting a newline after `(`. This was necessary to move the `it` to a new line. One unit test that was affected:

```scala
// before 
object a {
  function(function(function(a, b),
                    function(c, d)))
}

// after 
object a {
  function(
      function(function(a, b),
               function(c, d)))
}
```
* We don't put a newline before the first dot `.` if it the indentation exceeds the current column. This prevents funny output like:

```scala
// before
a
  .fooo(bar)
  .kaz(mania)

// after
a.fooo(bar)
  .kaz(mania)

```


 will improve the formatting output in many other related cases.

**Comment by sjrd** [comment]
That sounds reasonable.
