### ISSUE TITLE
Triple quoted strings and stripMargin.

### ISSUE THREAD

**Issue by paulp** [olafurpg/scalafmt#170]
Original:
```scala
object Generator {
  def template = s"""
    |package psp
    |package tests
    |package generated
    |
    |object Expressions {
    |  ${ vals mkString "\n" }
    |}""".stripMargin
}
```

Scalafmt:
```scala
object Generator {
  def template = s"""
                    |package psp
                    |package tests
                    |package generated
                    |
                    |object Expressions {
                    |  ${vals mkString "\n"}
                    |}""".stripMargin
}
```

I would like the input to look like the original. That's the inside of an interpolated string you're reformatting! It looks like it behaves differently if I call `.dingo` instead of `.stripMargin`. But you have no way of knowing what that call to stripMargin does! You can't assume it's a call to the standard library's stripMargin method simply because it happens to share the name.

Output collected with scalafmt 0.2.1.

**Comment by olafurpg** [comment]
`--alignStripMarginStrings false` disables this feature. It's true that stripMargin could be anything since scalafmt has no semantic information. However, for most use-cases I think it is safe to assume that it's the standard library `stripMargin`.

**Comment by paulp** [comment]
I think you should seriously reconsider this.

Convenience is Tail. Correctness is Dog. You are taking the position that it's OK for the code formatter to break code if someone is unlucky enough to choose stripMargin as a method name. Do you know what kind of burden it is to sift through a large corpus of scala code to discover what the formatter might have broken, so that you can later discover which options you were supposed to disable so as to avoid that?

What you are doing is very, very ad hoc, in a manner which is certain to burn people, for minimal benefit. Flip the option to ``--assumeStandardLibraryStripMargin`` or something and let any damage be self-inflicted.

**Comment by paulp** [comment]
Just in the repositories I have cloned locally, which is probably fewer than 1/10000 of all scala repositories:
```scala
scalikejdbc/scalikejdbc-core/src/main/scala/scalikejdbc/interpolation/SQLSyntax.scala
187:  def stripMargin: SQLSyntax = new SQLSyntax(value.stripMargin, parameters)
189:  def stripMargin(marginChar: Char): SQLSyntax = new SQLSyntax(value.stripMargin(marginChar), parameters)

scalikejdbc/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala
480:  def stripMargin(marginChar: Char): SQL[A, E] =
484:  def stripMargin: SQL[A, E] =

specs2/core/src/main/scala/org/specs2/specification/core/Description.scala
17:  def stripMargin(margin: Char): Description = this
18:  def stripMargin: Description = stripMargin('|')
27:  override def stripMargin(margin: Char) = copy(text.stripMargin(margin))
36:  override def stripMargin(margin: Char) = copy(text.stripMargin(margin))

specs2/core/src/main/scala/org/specs2/specification/core/Fragments.scala
69:  def stripMargin: Fragments = stripMargin('|')
72:  def stripMargin(margin: Char): Fragments = mapDescription(_.stripMargin(margin))

spray/spray-util/src/main/scala/spray/util/pimps/PimpedString.scala
99:  def stripMarginWithNewline(newline: String) = underlying.stripMargin.replace("\r\n", "\n").replace("\n", newline)
```

**Comment by olafurpg** [comment]
Wow. I admit it was naive to assume `stripMargin` would always come from the std lib. I agree that `--assumeStandardLibraryStripMargin` with default value false is more sensible. Thanks for raising this up, I'll try to address it asap.

**Comment by olafurpg** [comment]
I want to add that I take it very seriously that scalafmt never messes with semantics. Part of the test suite is verifying that scalafmt formatted code [preserves the AST of the original code](https://github.com/olafurpg/scalafmt/blob/a5066da3a3f074ab2b426a553724265b146852c6/core/src/test/scala/org/scalafmt/util/FormatAssertions.scala#L18). The tests run against ~10k Scala source files from akka, spark, intellij-scala and few more project. For obvious reasons, `--alignStripMarginStrings` is disabled in these tests (which should have raised more warnings when I think about it).

**Comment by paulp** [comment]
That's reassuring. I suggest verifying AST invariance on all the projects in the [community build](https://github.com/scala/community-builds). If you really want to test it, run it against [psp-std](https://github.com/paulp/psp-std), where you stand a great chance of flushing out more hidden assumptions. psp-std is built with `-Yno-predef -Yno-imports` and little else in the world works as hard to avoid the standard library.
