### ISSUE TITLE
Don't put if enumerator on a separate line

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#176]
Diff:
```scala
       for {
          parent <- sym.info.parents
 -        psym = parent.typeSymbol
 -        if psym.isInterface
 +        psym = parent.typeSymbol if psym.isInterface
        } yield {
          genClassName(psym)
        }
```

I'd like to keep the if where it was. 

Using: 0.2.1

**Comment by sjrd** [comment]
This is one thing where I believe the formatter should try and preserve whatever was there before. I usually use the separate line variant, except if the filter is "tightly coupled" to a `<-` in terms of semantics (which is something the formatter cannot guess).

If I were to choose one thing to always conform to, it would be the separate line variant.
