### ISSUE TITLE
Multiple pattern matching alternatives overflow the column limit

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#177]
Diff:
```scala
-        case NullTag
-           | UnitTag
-           | BooleanTag
-           | ByteTag
-           | ShortTag
-           | CharTag
-           | IntTag
-           | LongTag
-           | FloatTag
-           | DoubleTag
-           | StringTag =>
+        case NullTag | UnitTag | BooleanTag | ByteTag | ShortTag | CharTag | IntTag | LongTag | FloatTag | DoubleTag | StringTag =>
            focus withValue genLiteralValue(lit)
```

I'd like this to be within my 90-column limit, potentially aligned by `|` if possible.

Using: 0.2.1

**Comment by sjrd** [comment]
This is how I make it look in Scala.js: https://github.com/scala-js/scala-js/blob/master/ir/src/main/scala/org/scalajs/core/ir/Traversers.scala#L204-L207, i.e., wrap after a `|` and indent 4 spaces (the continuation indent).

**Comment by olafurpg** [comment]
That's what scalafmt does by default @sjrd, this issue came because there was no `_: ` before the types.
