### ISSUE TITLE
Preserve text layout when reformatting scaladoc comments

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#179]
Original:
```scala
/** Foo bar baz.
 *  - a
 *  - b
 *  - c 
 */
```

Scalafmt:
```scala
/** Foo bar baz.
  *  - a
  *  - b
  *  - c 
  */
```

I would like the input to look like this:
```scala
/** Foo bar baz.
  * - a
  * - b
  * - c 
  */
```

Using: 0.2.1

**Comment by olafurpg** [comment]
I agree this is annoying and needs to be fixed. I believe the best solution is to tackle #145 instead of coming up with ugly hacks for removing/adding 1 space indentation here and there.
