### ISSUE TITLE
Don't insert space before colon 

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#180]
Diff:
```scala
-    def map[T: reflect.ClassTag](f: Node => T): Seq[T] = {
+    def map[T : reflect.ClassTag](f: Node => T): Seq[T] = {
```

I'd like not to have colon inserted after `T`.

Using: 0.2.1

**Comment by olafurpg** [comment]
Interesting comment from @dwijnand on gitter:

> when it's one type I agree with Denys I like `T: ClassTag` too, but when it's more than one I prefer `T : ClassTag : Functor`.

**Comment by sjrd** [comment]
@dwijnand's comment makes sense. I have also seen (and used) a space being used if there is a lower bound and/or upper bound on the type.

**Comment by olafurpg** [comment]
Looking at cats, they seem to [consistently put no space before colon](https://github.com/typelevel/cats/blob/master/kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala#L25):

```scala
implicit def orderLaws[A: Eq: Arbitrary] = OrderLaws[A]
```

**Comment by densh** [comment]
@olafurpg that looks great.
