### ISSUE TITLE
Alignment in mixed owner-type blocks

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#184]
Diff:
```scala
-    var deps       = mutable.Stack[Global](entry)
-    var defns      = mutable.UnrolledBuffer.empty[Defn]
-    val resolved   = mutable.Set.empty[Global]
+    var deps  = mutable.Stack[Global](entry)
+    var defns = mutable.UnrolledBuffer.empty[Defn]
+    val resolved = mutable.Set.empty[Global]
```

I'd like for code to stay the way it was. This means that grouped blocks of vals/vars and defs would benefit from being aligned by equals sign.

The similar issue applies for aligning with "extends" over a group of objects/traits and classes. For example in following code formatted by scalafmt:

```scala
object Val {
  // low-level
  final case object None  extends Val
  final case object True  extends Val
  final case object False extends Val
  final case class Zero(zeroty: nir.Type)                     extends Val
  final case class I8(value: Byte)                            extends Val
  final case class I16(value: Short)                          extends Val
  final case class I32(value: Int)                            extends Val
  final case class I64(value: Long)                           extends Val
  final case class F32(value: Float)                          extends Val
  final case class F64(value: Double)                         extends Val
  final case class Struct(name: nir.Global, values: Seq[Val]) extends Val
  final case class Array(elemty: nir.Type, values: Seq[Val])  extends Val
  final case class Chars(value: java.lang.String)             extends Val
  final case class Local(name: nir.Local, valty: nir.Type)    extends Val
  final case class Global(name: nir.Global, valty: nir.Type)  extends Val
}
```

I'd like `extends Val` to be aligned throughout the whole block for both objects and classes. 

Using: 0.2.1

**Comment by densh** [comment]
I think I'm annoyed enough by mixed alignment of `val/var`-s that I would pay to get this bug fixed. Just name the price. 😉

**Comment by olafurpg** [comment]
We can discuss this in August ;) not sure how the configuration for it should work (or if there should be any configuration for it).

**Comment by olafurpg** [comment]
I'm happy to hardcode the most common-sense cases, and then let #172 take care of adding more customization to how tokens align together. Are there other cases than val/var and object/class bugging you @densh ?

This can be fixed by changing a single line of code:

https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L157

**Comment by densh** [comment]
I'd say val/var/def and class/trait/object are the two major groups I'd want to see aligned together.
