### ISSUE TITLE
Format Imports

### ISSUE THREAD

**Issue by bdarfler** [olafurpg/scalafmt#188]
It would be nice to sort imports and maybe group them like scalastyle or how intellij does it by default. I don't have much of an opinion on the details but making imports consistent within a project is very nice.

**Comment by olafurpg** [comment]
I agree that having this would be great. However, sorting imports correctly requires semantic information, which scalafmt does not have. Scalariform does not sort imports for the same reason, as discussed here: https://github.com/scala-ide/scalariform/issues/67 I agree with mdr's comment that this functionality probably belongs in a different tool such as scala-refactoring.

Until then, I recommend using the IntelliJ import optimizer.

**Comment by bdarfler** [comment]
Ahh, thanks for the info. I didn't realize.
