### ISSUE TITLE
Scalafmt fails to format sources of sbt plugins

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#190]
Reproduction:
https://github.com/densh/sbt-plugin-scalafmt-failure

Using
* 0.2.4-RC1

**Comment by olafurpg** [comment]
I can still reproduce on c41cbd8d96df4ed90d6da7c72030aa6759cc13ee. I wonder how many are affected.

**Comment by dwijnand** [comment]
Probably more simply because scalaVersion is 2.10.6

**Comment by olafurpg** [comment]
Any suggested fix?

**Comment by dwijnand** [comment]
Less hacks, more cross-building :)

**Comment by cquiroz** [comment]
I'm affected by this too as I want to format generated source code as part of my sbt build
