### ISSUE TITLE
Non idempotent formatting

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#192]
See 

```scala
 -  def log(formatToken: FormatToken): String = s"""${log(formatToken.left)}
 -                                                 |${log(formatToken.between:_*)}
 -                                                 |${log(formatToken.right)}""".stripMargin
 +  def log(formatToken: FormatToken): String =
 +    s"""${log(formatToken.left)}
 +       |${log(
 +           formatToken.between: _*)}
 +       |${log(formatToken.right)}""".stripMargin
```

Reformatting again produces:
```scala
  def log(formatToken: FormatToken): String =
    s"""${log(formatToken.left)}
       |${log(formatToken.between: _*)}
       |${log(formatToken.right)}""".stripMargin
```

in commit https://github.com/olafurpg/scalafmt/commit/779c1ee53edbfe812693b8ae3fdfb79329dd5658?diff=unified#diff-b276550f97eeb5bceb770dc3d64811ceL19

**Comment by paulp** [comment]
Here's a non-idempotent situation not involving an interpolated string.
```scala
class A {
  def traced(in: A => Unit, out: B => Unit): Fun[A, B] = ( f
    .   mapIn[A] { x => in(x) ; x }
    .  mapOut[B] { x => out(x) ; x }
  )
}
```
becomes
```scala
class A {
  def traced(in: A => Unit, out: B => Unit): Fun[A, B] = (f
    .mapIn[A] { x =>
      in(x); x
    }
    .mapOut[B] { x =>
      out(x); x
    })
}
```
which becomes
```scala
class A {
  def traced(in: A => Unit, out: B => Unit): Fun[A, B] =
    (f.mapIn[A] { x =>
        in(x); x
      }
      .mapOut[B] { x =>
        out(x); x
      })
}
```
Also, it was a lot better before anything happened to it.

And in the "watch out for the future" department, those leading dots are only necessary through 2.10. In 2.11 and beyond that can be written
```scala
  def traced(in: A => Unit, out: B => Unit): Fun[A, B] = ( f
      mapIn[A] { x => in(x) ; x }
     mapOut[B] { x => out(x) ; x }
  )
```
I think dotless syntax is far superior for readability but I doubt most people can handle it unless their formatter does all the handling of it, hint hint.

**Comment by olafurpg** [comment]
Thanks for the example!

> I think dotless syntax is far superior for readability but I doubt most people can handle it unless their formatter does all the handling of it, hint hint.

Some auto migration tool would be nice, indeed. I'm not sure about baking it with scalafmt, I think it better belongs to another tool like scala-tidy, similar to clang-tidy.
