### ISSUE TITLE
Case alignment can overflow the column limit

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#196]
Scalafmt formatted code:
```scala
  def genTypeSym(sym: Symbol,
                 targs: Seq[Type] = Seq(),
                 retty: Boolean = false): nir.Type = sym match {
    case ArrayClass           => genTypeSym(NArrayClass(genPrimCode(targs.head)))
    case UnitClass            => if (retty) nir.Type.Void else genTypeSym(BoxedUnitClass)
    case ObjectClass          => nir.Rt.Object
    case CharClass            => nir.Type.I16
    case BooleanClass         => nir.Type.Bool
    case ByteClass            => nir.Type.I8
    case ShortClass           => nir.Type.I16
    case IntClass             => nir.Type.I32
    case LongClass            => nir.Type.I64
    case FloatClass           => nir.Type.F32
    case DoubleClass          => nir.Type.F64
    case NullClass            => nir.Type.Null
    case NothingClass         => nir.Type.Nothing
    case NPtrClass            => nir.Type.Ptr
    case _ if isModule(sym)   => nir.Type.Module(genClassName(sym))
    case _ if sym.isInterface => nir.Type.Trait(genClassName(sym))
    case _                    => nir.Type.Class(genClassName(sym))
  }
```

Here we see overflow over 80 column limit in first two cases. 

Using
* 0.2.2

**Comment by olafurpg** [comment]
What is the expected output? This is working as intended IMO, although I'm happy to reconsider.

You can add a blank line after the UnitClass case to create a separate alignment block so it doesn't overflow the limit. I don't think scalafmt should not make that decision on your behalf.

**Comment by densh** [comment]
My understanding was that the result of the formatter should always fit within maxColumn limit. Here the limit is 80 and the produced formatted code is 90.

**Comment by olafurpg** [comment]
There are cases where scalafmt will choose not to break the column limit even if it can do so

```scala
// column              |
function(
    a,
    bbbbbb, // This comment exceeds column limit
    cc)
```

Putting a newline before the comment would make the comment confusing. Likewise, my understanding of defaultWithAlign is that breaking the vertical alignment would negatively affect the readability of the code.

**Comment by densh** [comment]
I see, sounds reasonable to me.
