### ISSUE TITLE
Nailgun integration

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#201]
The CLI currently pays the JVM startup penalty on every invocation. Nailgun (http://www.martiansoftware.com/nailgun/) might solve this problem.

**Comment by fdietze** [comment]
I just wrote some helper scripts to run scalariform with nailgun. Maybe these help:
https://github.com/fdietze/dotfiles/commit/2896816990c0cf1a7a4e3c88abcecd082f9f07f4

**Comment by olafurpg** [comment]
Thanks! Using your example I managed to get nailgun working with scalafmt. It's so fast 😄 

What's missing to get this integration working smoothly:
* pick out the working directory from a nailgun context to support relative file paths
* gracefully handle disconnections when formatting inside `.par.foreach`
* bundle ng-* scripts together with the tar release

**Comment by olafurpg** [comment]
Fixed in 0.4.6
