### ISSUE TITLE
Reconsider default style

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#202]
I see many OSS repos use a different coding style from the scalafmt default style

* --maxColumn 100 (scala.js + scalafmt are the only repos I've seen look nicely with 80 character limit)
* --continuationIndentCallSite 2
* --assumeStdLibStripMargin false

**Comment by dwijnand** [comment]
80 chars, asides from being the old traditional max column, is also the
maximum for viewing files and diffs in GitHub on mobile. On bigger screens
that default jumps up to 112. So if you're going to bump it up, 112 columns
is another option.

**Comment by olafurpg** [comment]
I agree, I will continue to use 80 chars for my own code.

My concern is that most people just install scalafmt, run it on their repo, see their lines break at odd places (e.g., a return type is 80+ char wide), assume the formatter is broken and give up.

**Comment by densh** [comment]
I think 80 chars is definitely uncommon for typical Scala, but I really believe that it is far superior to 100+ column limit as it forces you to refactor horribly big/nested expressions sooner. Scala code in the wild goes way overboard with nesting most of the time.

**Comment by olafurpg** [comment]
An alternative that came up at flatMap(Olso) is to introduce some sort of `--softMaxColumn` with default value 80 and `--hardMaxColumn` (current `--maxColumn`) with default value 100. It means scalafmt might choose to exceed to soft limit if it helps prevent very unfortunate breaks. I would need to look at diffs to confirm this works as I expect it to.

**Comment by densh** [comment]
Having two limits would be quite useful. That's what I had personally before I started using scalafmt.

**Comment by olafurpg** [comment]
Continuation indent call site became 2 spaces in the end!

Thanks for the input everyone. I agree, I think maxColumn = 80 is still the right choice.
