### ISSUE TITLE
Static style configuration in SBT plugin

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#208]
Instead of referencing a file to be read a runtime, it should be possible to pass in the contents of that file as a string literal. Context: https://gitter.im/olafurpg/scalafmt?at=572aa357d6d0f60219f0affd

**Comment by fommil** [comment]
We're planning on using the File approach in ensime, so it would be good to keep that as the primary setting.

**Comment by olafurpg** [comment]
Current workaround:

> can easily do this by putting the scalafmt config file in our plugin as a resource

**Comment by olafurpg** [comment]
This is achievable by writing the configuration contents to a file and then passing that file to the plugin.
