### ISSUE TITLE
Break before colon for massive return type

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#212]
In order to fix #192 I need to come up with a better solution for massive return types. The solution I've come up with is to follow the Spark style guide: https://github.com/databricks/scala-style-guide#indent

Original:
```scala
<<< slick groupBy 2
  def groupBy[K, T, G, P](f: E => K)(implicit kshape: Shape[_ <: FlatShapeLevel, K, T, G], vshape: Shape[_ <: FlatShapeLevel, E, _, P]): Query[(G, Query[P, U, Seq]), (T, Query[P, U, Seq]), C, (T, Query[P, U, Seq]), (T, Query[P, U, Seq])]
```

Scalafmt:
```scala
def groupBy[K, T, G, P](f: E => K)(
    implicit kshape: Shape[_ <: FlatShapeLevel, K, T, G],
    vshape: Shape[_ <: FlatShapeLevel, E, _, P])
  : Query[(G, Query[P, U, Seq]),
          (T, Query[P, U, Seq]),
          C,
          (T, Query[P, U, Seq]),
          (T, Query[P, U, Seq])]
```

Note the newline before `: Query[...`. That newline previously came before the closing parenthesis `): Query[...`. I suspect @sjrd will never approve this. So my suggestion is to add a configuration flag `--allowNewlineBeforeColonInMassiveReturnTypes` that's set to true in the default style and false in scalaJs.

Any objections?

**Comment by densh** [comment]
Looks fine to me.

**Comment by sjrd** [comment]
Configuration sounds good to me.
