### ISSUE TITLE
Return type is placed in new line without parenthesis in large method definitions

### ISSUE THREAD

**Issue by jvican** [olafurpg/scalafmt#217]
Original:
```scala
  implicit def vectorPickler[T: FastTypeTag](implicit elemPickler: Pickler[T],
    elemUnpickler: Unpickler[T], collTag: FastTypeTag[Vector[T]], cbf: CanBuildFrom[Vector[T], T, Vector[T]]):
    Pickler[Vector[T]] with Unpickler[Vector[T]] =
    SeqSetPickler[T, Vector]
```

Scalafmt:
```scala
  implicit def vectorPickler[T : FastTypeTag](
      implicit elemPickler: Pickler[T],
      elemUnpickler: Unpickler[T],
      collTag: FastTypeTag[Vector[T]],
      cbf: CanBuildFrom[Vector[T], T, Vector[T]])
    : Pickler[Vector[T]] with Unpickler[Vector[T]] =
    SeqSetPickler[T, Vector]
```

I would like the input to look like this:
```scala
  implicit def vectorPickler[T : FastTypeTag](
      implicit elemPickler: Pickler[T],
      elemUnpickler: Unpickler[T],
      collTag: FastTypeTag[Vector[T]],
      cbf: CanBuildFrom[Vector[T], T, Vector[T]]
  ): Pickler[Vector[T]] with Unpickler[Vector[T]] =
    SeqSetPickler[T, Vector]
```

Using
* 0.2.3
  
I also know that if I put a newline before the parenthesis, the output will be the desired one. However, I wonder if it wouldn't be better to format to the desired one always.

**Comment by olafurpg** [comment]
> I wonder if it wouldn't be better to format to the desired one always.

That's how it worked before 0.2.3, but it caused non-idempotent formatting (#192). Problem is once you go into "config-style" (explained [here](https://olafurpg.github.io/scalafmt/#Functionapplication)) scalafmt doesn't go back. The solution was to put the newline before the colon `:` as the Spark style guide suggests, see #212.

So sorry, you'll have to opt-in manually for the config style.
