### ISSUE TITLE
broken indent in while condition

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#225]
Broken test:
```scala
<<< SKIP while condition is like if
    while (!hasReachedEof(curr) &&
    !statementStarts.contains(hash(tokens(curr.splits.length).left))) {
      val tok = tokens(curr.splits.length)
      curr = State.next(curr, style, provided(tok), tok)
    }
>>>
while (!hasReachedEof(curr) &&
       !statementStarts.contains(hash(tokens(curr.splits.length).left))) {
  val tok = tokens(curr.splits.length)
  curr = State.next(curr, style, provided(tok), tok)
}
```

**Comment by sjrd** [comment]
The above is consistent with other formatting options that align all parameters on the column after `(`. For styles that do not use this formatting, a more consistent variant is:
```scala
while (!hasReachedEof(curr) &&
    !statementStarts.contains(hash(tokens(curr.splits.length).left))) {
```
with 4 spaces (like `if` too)

**Comment by olafurpg** [comment]
Interesting. It just so happens that `if (` is exactly 4 characters. I personally prefer to align by the opening `(`, but if no-one agrees with me then I am happy to indent at `continuationIndentCallSite` (=4 in default and scala.js styles). I think the IntelliJ formatter and scalariform indent at continuation indent. I'll keep this open a while longer, if no-one comments to agree with me then I'll keep it as you suggest @sjrd.

**Comment by olafurpg** [comment]
I decided to let the default style align by `(` and Scala.js style indent by continuation indent (=4).

**Comment by Daxten** [comment]
jus my opinion, I like it better aligned by (
