### ISSUE TITLE
Replace "--style scalaJs" flag with "--style scala.js"

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#227]
Or should it be "--style scalajs", any opinions @sjrd?

**Comment by sjrd** [comment]
The official spelling is "Scala.js" so I guess "scala.js" is the right choice if you don't want uppercase.

**Comment by olafurpg** [comment]
The documentation will then say "Scala.js", but accept anything that matches "scala.js" when lower cased.
