### ISSUE TITLE
More Configurability

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#235]
Let's just call this a general desire for significantly more configurability in the formatting style.  Scalariform is a decent example, though it's missing plenty of stuff that I *would* want (line limits being a good example).  I think scalafmt is a far better foundation, but right now its lack of configurability basically prevents me from using it.  :-(

Some general points:

- **Configurability of vertical alignment**  I cannot stress this enough.  Vertical alignment is *not* a universal desire.  I find it almost unreadable (seriously), and while I know I'm in the minority, I'm certainly not the only one.  In general, what I want is the option to make intraline spacing rules context-free (outside of the indentation scope), rather than dependent on contents of the line above/below.
- Dangling parentheses options.  Scalariform is pretty great in this regard, as it allows you to preserve parentheses, force them to their own line (like closing braces), or collapse them to the previous line.
- Better control over parameter blocks linebreaking.  Right now, I believe scalafmt forces a style in which line-broken parameter blocks (actuals and formals) are vertically aligned with the first parameter, which is retained on the same line as the method name.  Some people like this style, while others (like me) would want this situation handled by single-indenting (for actuals) or double-indenting (for formals) and moving all parameters to their own line.

These are just the biggest ones that come to mind.  All in all, I think configurability is by far the most important feature for any formatter.  I understand the desire to be opinionated, but frankly that's a non-starter for a language as syntactically rich as Scala.  Also, I did try to implement this myself, but obviously the way configuration is done right now makes that a rather difficult affair.

**Comment by sjrd** [comment]
> Configurability of vertical alignment

Isn't no-vertical-alignment the default? Btw I'm 100% with you, I also find vertical alignment weird.

> Better control over parameter blocks linebreaking.

This is configurable. Enable bin-packing for arguments and/or parameters.

**Comment by djspiewak** [comment]
> Isn't no-vertical-alignment the default?

When I was looking at it a week ago, there didn't seem to be *any* valign configuration that I could find.  Doesn't mean it wasn't there, I just couldn't find it.  :-)  That was what led me to assume that it was simply always on.

> This is configurable. Enable bin-packing for arguments and/or parameters.

Sort of.  It doesn't seem to have the style that I really want.  For example:

```scala
// formals
def foo(abc: Int, deff: Int, efg: Int) = {
  stuff
}

// assuming the above MUST be line broken
def foo(
    abc: Int,
    deff: Int,
    efg: Int) = {

  stuff
}

// actuals
foo(abc, deff, efg)

foo(
  abc,
  deff,
  efg)
```

I don't believe there is a way to achieve the above.  Obviously, this isn't the style that everyone desires, which is why I think it should be configurable.  :-)

**Comment by olafurpg** [comment]
I agree that the current configuration options are limited and don't capture all popular coding styles from the Scala community. I am happy to consider new flags.

> Configurability of vertical alignment

I admit, the default style does vertically align arguments/parameters by the opening `(`. The current rules are documented [here](https://olafurpg.github.io/scalafmt/#Functionapplication). In #223, I've considered removing option 2. Maybe we should add a flag to disallow option 3 and go straight to option 4 instead.

As @sjrd suggests, you can use ["bin packing"](https://github.com/olafurpg/scalafmt/blob/594d96b52925b6ebaf42e4323800fdd0644dfac3/core/src/main/scala/org/scalafmt/ScalafmtStyle.scala#L16), like the Scala.js style uses. I see there is no way to enable bin packing without `--style scala.js`. I can fix that in 0.2.4, see #236.

> what I want is the option to make intraline spacing rules context-free

This would be better explained with a code example. Please include the original code, what scalafmt does and what you would like scalafmt to do.

> Dangling parentheses options

scalafmt uses dangling parenthesis to detect "config style", see [here](https://olafurpg.github.io/scalafmt/#Functionapplication). For your example:

```scala
def foo(
    abc: Int,
    deff: Int,
    efg: Int) = {

  stuff
}
```
You can put a newline after `efg: Int` and scalafmt will then keep it like that.

I personally don't like Scalariform's approach to dangling parentheses because I don't see the need for 3 configuration options for something that is -- IMHO -- complete trivia.

> Better control over parameter blocks linebreaking.

Yes. I agree, and this is way more important than dangling parentheses. But, I will again need clearer examples of how you would like it to be ;) FWIW, I usually call formals "definition site" and actuals "call site".

> I prefer leaving the lines alone [for argument lists]

Note that it's impossible to keep the newlines/spaces after commas in argument lists while adhering to the line length limit. We need a rule/algorithm to decide how to break a line if the line limit is exceeded.

**Comment by olafurpg** [comment]
> Also, I did try to implement this myself, but obviously the way configuration is done right now makes that a rather difficult affair.

Where did you get stuck? Some configuration options should be quite straightforward to add. I would love to improve the contributor docs to help people hack on scalafmt.

**Comment by djspiewak** [comment]
> As @sjrd suggests, you can use "bin packing", like the Scala.js style uses. I see there is no way to enable bin packing without --style scala.js. I can fix that in 0.2.4, see #236.

Well, this isn't *quite* what I want.  If you consider either my definition or call site examples from earlier, I want everything on the same line (as I defined it) unless I hit the line limit, at which point I want everything to break such that each parameter gets their own line.  So, "all or nothing" as it were.

> This would be better explained with a code example. Please include the original code, what scalafmt does and what you would like scalafmt to do.

It's a bit of a general rule of thumb, but I'll try to give some examples.  I haven't actually tried these with scalafmt, but that's sort of beside the point.  It's the principle rule that matters:

```scala
for {
  a <- foo
  abc <- bar
  (stuff, and, things) = abc
} yield stuff
```

In the above snippet, I want it formatted exactly as I typed it.  There are a couple rules in play here.  Off the top of my head:

- Contents of curly braces (`{}`) are indented exactly one level from surrounding scope
- The generator symbol (`<-`) in a `for`-comprehension is surrounded by exactly one space on each side
  + Note that this is a special case of the "infix operator" rule, which is identical
- The assignment symbol (`=`) in all contexts – `for`-comprehension or otherwise – is surrounded by exactly one space on each side
  + Also a special case of infix operators
- Within a tuple declaration or deconstruction, the comma is preceded by zero spaces and followed by exactly one space, with the entire declaration on a single line
  + Special case of the rule for method parameters, formal or actual

The point that I'm making is that all of these are rules which we can apply equally by taking any individual line from the snippet and examining it in isolation:

```scala
(stuff, and, things) = abc
```

Aside from the indentation scope, which is clearly contextual, we know everything we need to know about how to format this line by looking at *just* this line.  (note: line limit messes with this, and I'll come back to that point)

This is in contrast to any vertical alignment scheme.  For example:

```scala
for {
  a   <- foo
  abc <- bar
  (stuff, and, things) = abc
} yield stuff

// or, perhaps?
for {
  a                   <- foo
  abc                 <- bar
  (stuff, and, things) = abc
} yield stuff
```

In both cases, the rules for formatting each individual line are broken by the fact that their context dictates something else.  In the upper case, `a <- foo` is no longer formatted correctly according to the ruleset I gave, and is instead preceded by three spaces (to align with `abc <- bar`).  This is even more egregious in the second option for alignment, where both generators are broken by the extraction.

For me, the context-free formatting ruleset is paramount.  I read things in a line-oriented fashion, which means that I have a hard time actually recognizing what language construct is in use when a line looks like this: `a                   <- foo`.  The formatting of every line should be independent of the line above or below it, except with respect to indentation scope and line breaking.

Speaking of line breaking, this is clearly where things get wonky, and it's an area where I absolutely love the foundation that scalafmt lays.  Knuth's algorithm is fantastic, and it's a brilliant tool for the job, because clearly context-free formatting no longer works when you're trying to decide on the least-awful line breaking schema.

But absent line breaking, and ignoring indentation scope, all intraline formatting should be completely context-free.  Or rather, I want the option of configuring this to be the case.  Equivalently, changing/removing/introducing a line above or below the current one in such a way that does not either exceed the line limit or introduce/remove an indentation scope must *not* affect the formatting of the current line.

> I personally don't like Scalariform's approach to dangling parentheses because I don't see the need for 3 configuration options for something that is -- IMHO -- complete trivia.

A dubious line to take with a code formatter.  :-)  It's *all* trivia.  Make it all configurable, because some people find various trivia more important than others.

I think scalariform could probably drop the third option ("preserve"), since the only time I would use that option is in DSL blocks.  For example, when I'm using parser combinators:

```scala
lazy val expr = (
    expr ~ "+" ~ expr
  | expr ~ "-" ~ expr
  | """\d+""".r
)
```

This is obviously a massive violation of all of my formatting rules (including context independence), including but not limited to trailing parentheses.  But it's a specific DSL, so I don't care.  In the event of a non-DSL example, I prefer to keep parentheses on the final line (to distinguish them visually from curly braces, which I push to the next line):

```scala
{
  List(
    1,
    2,
    3,
    4,
    5)
}
```

So ignoring the DSL case, that's really just two formatting options: same line, or next line.  It's important to have those two; we don't need scalariform's third so long as we do have the ability to exempt blocks (e.g. DSLs) from reformatting.

> Yes. I agree, and this is way more important than dangling parentheses. But, I will again need clearer examples of how you would like it to be ;) FWIW, I usually call formals "definition site" and actuals "call site".

We can start gathering examples, obviously.  It is worth noting that I wrote the original version of the Scala Style Guide, and I still ascribe to nearly all of its guidelines.  The "minimum viable" bar for me, personally, would be a sufficiently rich set of configuration options as to allow me to configure scalafmt to match that style (within the bounds of where the guide is ambiguous, obviously).

> Note that it's impossible to keep the newlines/spaces after commas in argument lists while adhering to the line length limit. We need a rule/algorithm to decide how to break a line if the line limit is exceeded.

Obviously.  :-)

> Where did you get stuck? Some configuration options should be quite straightforward to add. I would love to improve the contributor docs to help people hack on scalafmt.

I stopped at the point where I discovered that the configuration options were mostly hard-coded and implemented in an ad hoc way.  I don't have a better way of doing it, off-hand, so don't take that as a direct criticism.  :-)  I just realized that what I wanted to do was going to be a more significant project than I had anticipated, and there were far fewer options already-implemented than I had expected, so I stopped.

**Comment by olafurpg** [comment]
> I want everything on the same line (as I defined it) unless I hit the line limit, at which point I want everything to break such that each parameter gets their own line.

This sounds very similar to what scalafmt currently does. Except, scalafmt tries first to align by the `(` before moving everything to 4 space indentation. I'm happy to add an option to disable that in the next release, see #241.

> I haven't actually tried these with scalafmt, but that's sort of beside the point. 

How is it beside the point? If you format this

```scala
for {
  a <- foo
  abc <- bar
  (stuff, and, things) = abc
} yield stuffdi
```
with the default scalafmt style you will get the exact same output back, **verbatim**. Scalafmt is for most parts context independent, FWIW [the tests](https://github.com/olafurpg/scalafmt/blob/master/core/src/test/resources/unit/Val.stat) run on single statements, not compilation units.

> A dubious line to take with a code formatter. :-) It's all trivia.

hehe, true, but some trivia is more important than other trivia 😜 

> So ignoring the DSL case, that's really just two formatting options: same line, or next line. It's important to have those two

Fine. Opened #242.

>  The "minimum viable" bar for me, personally, would be a sufficiently rich set of configuration options as to allow me to configure scalafmt to match that style

I would be thrilled to add the official Scala style guide to the list of available styles in scalafmt, users could enable it with something like `--style scala-lang`. What do you consider to be missing? A good start here would be to open an issue with a single code example, show what scalafmt currently does and how it should look like to meet the official Scala coding style. In my experience, any description in English ends up being too ambiguous.

**Comment by djspiewak** [comment]
> How is it beside the point?

Mostly I was interested in exploring the general principle (context independence).  I guess this is an RFE on scalafmt though, and not a blog post, so point taken.  :-)

> […] you will get the exact same output back, verbatim. Scalafmt is for most parts context independent, FWIW the tests run on single statements, not compilation units.

Great to hear!

I will (in the next few days) try to throw scalafmt at a few of the more non-trivial codebases on my machine and see what happens.  The more I think about it, the more I really do want to use it (which is not something I would have said a few weeks ago, so apparently your talk was really fantastic).  I had been under the impression that I needed to first start by convincing you that rich configurability was a desirable feature in the first place, but if that's a non-argument, it's much better to just skip ahead and start distilling down the exact configuration required.

> I would be thrilled to add the official Scala style guide to the list of available styles in scalafmt, users could enable it with something like --style scala-lang. What do you consider to be missing? A good start here would be to open an issue with a single code example, show what scalafmt currently does and how it should look like to meet the official Scala coding style.

I think most of what I noticed was method parameter formatting was a problem, but I didn't dig in too closely.  Honestly, I'm primarily interested with making sure that all of the relevant "do this, instead of this other thing" points in the Scala Style Guide are configurable, rather than scalafmt already deciding to do it in that way.  Not sure if that makes sense, exactly.

The quote from Viktor in your talk is really compelling, describing a world in which style debates reduce to pull requests on a configuration file in the project root.  In order to do that, we need the configurability to be rich enough that teams *can* debate the the trivia which is more trivial than other trivia.  :-)

> In my experience, any description in English ends up being too ambiguous.

This is absolutely the case.  The Scala Style Guide tries to be very example-heavy, but obviously it's still ambiguous.

**Comment by olafurpg** [comment]
>  so apparently your talk was really fantastic

^_^

>  just realized that what I wanted to do was going to be a more significant project than I had anticipated,

In case you find time to hack on scalafmt, I added a tutorial in the [readme](/olafurpg/scalafmt) on how to add a new configuration flag.

> mostly hard-coded and implemented in an ad hoc way

Yeah, code formatting seems to be a hairy business. I'm still quite proud by the fact that scalafmt/core is "only" at 2.8k LOC.

**Comment by djspiewak** [comment]
I'm going to close this, if that's alright @olafurpg.  It wasn't a very specific issue to begin with, but I think that the changes in the 0.2.6 timeframe have satisfied *most* of what I need from the tool.  I'm happy to open more specific issues as they crop up.
