### ISSUE TITLE
SBT plugin does not format everything

### ISSUE THREAD

**Issue by anna-zzz** [olafurpg/scalafmt#282]
SBT plugin did not format some files.
```
> scalafmt
[info] Formatting 2 Scala sources...
[success] Total time: 2 s, completed May 23, 2016 8:44:16 PM
> scalafmtTest
[trace] Stack trace suppressed: run last foo/compile:scalafmtTest for the full output.
[error] (foo/compile:scalafmtTest) org.scalafmt.sbt.HasScalaFmt$MisformattedFile: X.scala is mis-formatted.
[error] Total time: 8 s, completed May 23, 2016 8:44:26 PM
> 
```

I open `X.scala` in Intellij and run scalafmt.
Before:
```
  def something(someObject: SomeClass)(
      implicit ec: EC): Foo[Bar[Baz]] =
```

After:
```
  def something(
      someObject: SomeClass)(implicit ec: EC): Foo[Bar[Baz]] =
```

```
$ cat .scalafmt
--style defaultWithAlign
--maxColumn 100
```

```
$ grep scalafmt build.sbt
scalafmtConfig := Some(file(".scalafmt"))
```

Intellij plugin Version: 0.2.5

**Comment by anna-zzz** [comment]
My bad, had to run `clean` and `reload`

**Comment by olafurpg** [comment]
Glad it worked out. The `scalafmt` task taps into the incremental compiler to avoid reformatting the whole project on every invocation. Since I've seen other people bump into similar problems as you, it might be worth considering adding a `scalafmtIncremental` that does what `scalafmt` currently does and let the `scalafmt` task reformat everything just like `scalafmtTest` does.

**Comment by sjrd** [comment]
Doing that will probably hide bugs in the incremental version forever, like it did for scalac pre-2.12 optimizer. I recommend against it.

*However*, it would definitely be good to be able to bypass the incremental version (but not as default), either with something like `scalafmt --all` or `scalafmtAll`.

**Comment by olafurpg** [comment]
Good point. I opened this issue to add an `--all` flag, I agree it would be a nice alternative to `clean; scalafmt`.
