### ISSUE TITLE
scalafmtConfig, Type error in expression

### ISSUE THREAD

**Issue by jkleiser** [olafurpg/scalafmt#291]
Hi,

I'm quite new to Scala, but I wanted to try your scalafmt as an sbt plugin. I installed scalafmt using homebrew, and I got scalafmt 0.2.5. Then I cloned your sbt-scalafmt-example, but when I do `sbt scalafmt`, I get this:
```
Loading /Users/jkleiser/bin/sbt/bin/sbt-launch-lib.bash
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from /Volumes/P3/Scala/sbt-scalafmt-example/project
/Volumes/P3/Scala/sbt-scalafmt-example/build.sbt:1: error: not found: value scalafmtConfig
scalafmtConfig := Some(file(".scalafmt"))
^
[error] Type error in expression
```

Using:
* 0.2.5
* --style default
* --maxColumn 40

What's can be wrong in my setup?

**Comment by olafurpg** [comment]
Which version of sbt are you using? You can try to pull from the sbt-scalafmt-example and see if it works now. I've pushed an update to force the project to use the latest sbt version 0.13.11.

**Comment by jkleiser** [comment]
When I do `sbt --version`, I get this:
```
Loading /Users/jkleiser/bin/sbt/bin/sbt-launch-lib.bash
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
sbt launcher version 0.13.0
```

I will try sbt version 0.13.11.

**Comment by jkleiser** [comment]
Yes! After I did `git pull`, then it worked. The file Foobar.scala got formatted nicely. Thanks!

**Comment by olafurpg** [comment]
Great, I'm happy that resolved the issue.
