### ISSUE TITLE
Scala files in test folder ignored by reformatOnCompileSettings

### ISSUE THREAD

**Issue by jkleiser** [olafurpg/scalafmt#295]
I'm testing scalafmt on a project where the top level folders are app, conf, lib, project, public, target and test. In sbt I'm running `~ compile`, and each time I edit and save a .scala file within the app folder, the file gets reformatted, as expected. However, when I edit and save a .scala file within the test folder, no reformatting occurs. Is this a bug or a feature?

Using:
* 0.2.5
* --style default
* --maxColumn 100

**Comment by olafurpg** [comment]
This is probably caused by some missing key in the test scope. I'm not too motivated to figure out the issue since I personally dislike this setting. It plays badly with text editors and IDEs. I'm tempted to remove the setting from the sbt plugin and ask users instead to paste this snippet into their build:

```scala
    lazy val reformatOnCompileSettings: Seq[Def.Setting[_]] = List(
        compileInputs in (Compile, compile) <<=
          (compileInputs in (Compile, compile)) dependsOn (scalafmt in Compile),
        compileInputs in (Test, compile) <<=
          (compileInputs in (Test, compile)) dependsOn (scalafmt in Test)
    )
```

**Comment by fthomas** [comment]
I like that setting. Also, keeping it in would provide a smoother upgrade path for people coming from sbt-scalariform.

**Comment by jkleiser** [comment]
I tried to put that lazy snippet into our build.sbt (both after the line with "reformatOnCompileSettings", and replacing that line), but it didn't cause our test .scala files to be reformatted. Did I misunderstand something?

**Comment by olafurpg** [comment]
@jkleiser I'm sorry, putting that snippet in your build.sbt won't resolve this issue. I suspect the issue has to do with Playframework. I'm unable to reproduce the issue the minimal play-scala activator template. Could you please provide me with a minimal repo to reproduce the issue? Something I can clone and poke at. 

@fthomas Valid point. I suspect many users like this setting.

**Comment by jkleiser** [comment]
Yes, I'll try to provide such a minimal repo. It my take a little while.

**Comment by olafurpg** [comment]
See https://github.com/olafurpg/reformatOnCompile for the play app I used.

**Comment by jkleiser** [comment]
I tried your reformatOnCompile app, and it behaves just like our Play app. I start with plain `sbt`, then I do `~ compile`. Scala files inside app folder gets reformatted when I save, those inside test don't, but I can reactions in the Terminal (`[success]`).
I'm using sbt 0.13.11, Scala 2.11.7 and Mac OSX 10.11.5.

**Comment by olafurpg** [comment]
I think I know what the issue is. Try `~test:compile` or `~test` and see if it works. The `compile` task doesn't depend on test files.

**Comment by jkleiser** [comment]
Thanks! `~test:compile` worked fine, both in your reformatOnCompile app, and in our Play app.

**Comment by olafurpg** [comment]
Glad it worked out.

**Comment by djspiewak** [comment]
I'm a few hours late to the party, but a thought I had is that it would be nice to be able to configure an "ignore" file pattern that would allow users to configure scalafmt to not reformat files on compile which have editor buffer files.  For example, a file named `Stuff.scala` might have a file named `Stuff.scala.swp` or `#Stuff.scala#` in the same directory (representing VI and jEdit, respectively).  Basically all editors have some file pattern of this sort, and it indicates that the editor in question has a dirty buffer of that file.

Dirty buffers are exactly the situation in which reformat-on-compile doesn't play nicely, so the best solution would be if scalafmt just ignored files which match that pattern.  One idea would be that the scalafmt SBT plugin could have a setting (of type `Seq[(Regex, String => String)]`) with some default patterns for the common editors, and users could add patterns as they will if they're using something unusual.  The semantics of that type, btw, would be that scalafmt could use the `Regex` as a quick check to rapidly determine whether or not a file in question *could* be a buffer, while the `String => String` would take the name of a full file (e.g. `Stuff.scala`) and compute its buffer peer (e.g. `#Stuff.scala#`).

**Comment by olafurpg** [comment]
@djspiewak you can specify an `excludeFilter` in the `hasScalafmt` task. Try

```scala
(excludeFilter in hasScalafmt) := "*.swp"
```

The implementation is borrowed from the Scalariform SBT plugin. Could that be what you had in mind?

**Comment by djspiewak** [comment]
@olafurpg Not quite.  What I want is something a bit like this:

```scala
excludeFilter := """^(.*)\.swap""".r
```

Where the first group from the pattern is used to determine the excluded file.  In other words, if `Stuff.scala.swp` *exists*, then I want to exclude `Stuff.scala` (and also, obviously, the swap file).

**Comment by olafurpg** [comment]
I see. I took the liberty to summarize this interesting idea in a separate issue #299. Let's move the discussion over there.
