### ISSUE TITLE
scalafmt creates huge diffs?

### ISSUE THREAD

**Issue by jkleiser** [olafurpg/scalafmt#296]
I read this http://olafurpg.github.io/scalafmt/#scalafmtcreateshugediffs!, and wonder, is this something we must expect most of the time when comitting changes to Scala code?
I understand that there will be lots of diffs the first time scalafmt does reformatting, but why should there be huge diffs later on?

**Comment by olafurpg** [comment]
I suppose the wording in that sections could be better. scalafmt is quite opinionated on how argument/parameter lists look like so it may create larger diffs than scalariform. Still, it shouldn't create larger diffs than opinionated formatters for other languages such as dartfmt and clang-format.
