### ISSUE TITLE
scalafmt settings for ITs

### ISSUE THREAD

**Issue by anna-zzz** [olafurpg/scalafmt#297]
I was struggling with making scalafmt work on IT sources, and I think a piece of configuration might be missing from the plugin. I wonder if `configScalafmtSettings` should be defined for `IntegrationTest` as well as for `Compile` and `Test` [here] (https://github.com/olafurpg/scalafmt/blob/a61bd6244b1982556ddcab7180e848ead893bedf/scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalaFmtPlugin.scala#L50-L52).

**Comment by olafurpg** [comment]
That is very likely the issue. Have you tried adding `inConfig(IntegrationTest)(configScalafmtSettings)` settings to your project settings? You may have to `import org.scalafmt.sbt. ScalaFmtPlugin._`. We can easily fix the sbt plugin if that resolves the issue.

**Comment by anna-zzz** [comment]
Yep, that's how I fixed it :) I wonder if it should be a part of default configuration -- I can make a PR if you want me to.

**Comment by olafurpg** [comment]
I added the IntegrationTest configuration to the plugin but users will still need to opt-into it, just like with the Scalariform sbt plugin.
