### ISSUE TITLE
Automatically reformat files after an active editing session

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#299]
Interesting suggestion from @djspiewak in #295. I can see this being an incredibly useful feature. Question is whether this should belong in the SBT plugin or in the text editor integrations as some sort of "reformat on unfocus" action.

My problem with implementing this as part of the SBT plugin is:
1. It's limited to text editors that create swap files in the same directory as the file. For example, I set my vim to put the swap files in `/tmp` and IntelliJ doesn't leave any swap files.
2. It would be tricky to get right since the current `reformatOnCompileSettings` implementation taps into the incremental compiler to know which files to format. The SBT plugin would need to know when the swap file is removed to know that it should reformat the source file.

By integrating this directly, I imagine the user experience would be smoother. However, if someone wants to take a stab at this in the SBT plugin, the relevant line of code is here: https://github.com/olafurpg/scalafmt/blob/6adefe05cc43c914569e181c1061153dafd88528/scalafmtSbt/src/main/scala/org/scalafmt/sbt/HasScalaFmt.scala#L46

**Comment by djspiewak** [comment]
Seems like this would work best as an editor plugin, but being able to do it at the SBT level, even for a subset of editors, seems extremely cool.  It would allow the code formatting question to remain part of the semantic "build question" as opposed to part of the "editor question".  On a team cultural level, I think that distinction is very significant, since the former is a team consensus subject to pull requests and compromise, while the latter is a domain of fierce personal choice.

**Comment by sjrd** [comment]
> being able to do it at the SBT level, even for a subset of editors, seems extremely cool

I disagree. This is entirely specific to an editor.

>  It would allow the code formatting question to remain part of the semantic "build question" as opposed to part of the "editor question".

For the "build question", you have `scalafmtTest`. That is definitely build-related, as it impacts CI. The reformat-on-compile is not build-related, IMO.

**Comment by djspiewak** [comment]
My original idea in #295 was actually specifically trying to configure reformat-on-compile to *not* reformat files which have dirty buffers.  I think the OP is a cool idea too, for the reasons stated, but it is a bit of an extension of what I was thinking.  :-0

**Comment by olafurpg** [comment]
@djspiewak I apologize for hijacking your idea :)

> configure reformat-on-compile to not reformat files which have dirty buffers

This is challenging for the reason number 2 above. I still think it's possible to implement. One approach that might work:

* before reformatting file, check if file has a dirty buffer,
* if file has dirty buffer, add file into a queue
* on every reformat, try to empty queue

**Comment by djspiewak** [comment]
@olafurpg I don't think it quite has to be that complicated.  If a file has a dirty buffer, then eventually it will be saved.  When it is saved, it will (by definition) be part of the file set that SBT computes as needing to be compiled.  So you can safely just ignore any files that have dirty buffers.

**Comment by olafurpg** [comment]
I see, skipping the file might be sufficient. This could be easily added here: https://github.com/olafurpg/scalafmt/blob/6adefe05cc43c914569e181c1061153dafd88528/scalafmtSbt/src/main/scala/org/scalafmt/sbt/HasScalaFmt.scala#L80

**Comment by olafurpg** [comment]
I don't suspect to work on this feature anytime soon. Feel free to re-open if you are interested in contributing to this issue.
