### ISSUE TITLE
Publish RC2

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#303]
Or alternatively, RC1.  Version 0.2.5 doesn't have the settings that I really need to use scalafmt, but master does.  If you could just do a quick publish on the RC (any RC) to sonatype, that would help me immensely!

**Comment by olafurpg** [comment]
Sure thing, I just published 0.2.6-RC1. It should sync to maven in the next half hour.

This release won't be documented, offer homebrew installation or be published to the IntelliJ plugin repository. For IntelliJ, you must build the plugin yourself and install manually via a zip file.

**Comment by anna-zzz** [comment]
Oh dear, sure thing I'm excited!
