### ISSUE TITLE
New feature request: explicit types

### ISSUE THREAD

**Issue by JohnReedLOL** [olafurpg/scalafmt#306]
I recently ran into a user transitioning from Java who found some Scala code harder to read and maintain because of the implicit types. He wants the ability to make the types explicit using some tool. One person suggested "It's probably easier to add this [feature] to scalafmt, which uses scala.meta to format code. It wouldn't be too difficult to use scala.meta to get the type an expression and add it if it missing."

What do you think?

**Comment by olafurpg** [comment]
I agree that it would be cool feature to insert type inferences and fill in implicit conversions. I would personally be interested in expanding underscore imports.

However, scalafmt doesn't have the semantic information to implement this feature. Same reason #188 won't work.
