### ISSUE TITLE
not any output when applying scalafmt to specified scala file

### ISSUE THREAD

**Issue by windfansy** [olafurpg/scalafmt#307]
Original:
```scala
package com.gridsum.spark.wd

object CombinedId {
  // Both the 'profile id' and 'user id' are either 'numeric' or 'alphanumeric', separator with one char is enough
  private val SEPARATOR = "@"

  def decode(str: String): CombinedId = {
    // The input 'str' is expected to be "${lastDecimalBitOfUserIdHash}${profileId}${SEPARATOR}${userId}"
    val parts = str.split(SEPARATOR)
    assert(parts.size == 2,
           s"Invalid string ${str}, couldn't be decoded to CombinedId")
    CombinedId(parts(0).tail.toInt, parts(1))
  }
}

case class CombinedId(profileId: Int, userId: String) {
  import CombinedId._

  def encode: String = {
    // the encoding scheme:
    // "${lastDecimalBitOfUserIdHash}${profileId}${SEPARATOR}${userId}"
    s"${userId.hashCode.toString.last}${profileId}${SEPARATOR}${userId}"
  }
}
```
[CombinedId.zip](https://github.com/olafurpg/scalafmt/files/297115/CombinedId.zip)

not any result when i apply scalafmt to this file. my cmd is:
`scalafmt -f CombinedId `

.scala`

Using:
* 0.2.5
* --style default

**Comment by olafurpg** [comment]
I am not able to reproduce the issue running `scalafmt -f CombinedId.scala` using the latest version 0.2.5. Could you please provide more info?

However, I know that the CLI doesn't print out anything in case of parse/format failure. I think the CLI should print out a helpful error message.

**Comment by windfansy** [comment]
![image](https://cloud.githubusercontent.com/assets/16920086/15773084/9575292c-29a7-11e6-9d02-1eeffc3fb2b7.png)
output nothing, i feel puzzled

**Comment by olafurpg** [comment]
I agree, I've added this issue to the 0.2.6 milestone to update the CLI so that it prints out a helpful error message. The offending line is here: https://github.com/olafurpg/scalafmt/blob/406caaaf1738a1d7a6cdd0d6606ac67c5c928327/cli/src/main/scala/org/scalafmt/cli/Cli.scala#L240

The CLI ignores errors instead of printing out. Still, I can't reproduce this particular issue on my machine:

```scala
$ scalafmt -f CombinedId.scala
package com.gridsum.spark.wd

object CombinedId {
  // Both the 'profile id' and 'user id' are either 'numeric' or 'alphanumeric', separator with one char is enough
  private val SEPARATOR = "@"

  def decode(str: String): CombinedId = {
    // The input 'str' is expected to be "${lastDecimalBitOfUserIdHash}${profileId}${SEPARATOR}${userId}"
    val parts = str.split(SEPARATOR)
    assert(parts.size == 2,
           s"Invalid string ${str}, couldn't be decoded to CombinedId")
    CombinedId(parts(0).tail.toInt, parts(1))
  }
}

case class CombinedId(profileId: Int, userId: String) {
  import CombinedId._

  def encode: String = {
    // the encoding scheme:
    // "${lastDecimalBitOfUserIdHash}${profileId}${SEPARATOR}${userId}"
    s"${userId.hashCode.toString.last}${profileId}${SEPARATOR}${userId}"
  }
}
```

**Comment by windfansy** [comment]
we can try on 0.2.6

**Comment by windfansy** [comment]
hi, when will you release version 0.2.6?

**Comment by olafurpg** [comment]
I've set June 30th as the deadline for the 0.2.6 milestone: https://github.com/olafurpg/scalafmt/milestones It may be sooner, but at the moment I'm busy writing my thesis.

If you really need this now I recommend you add print out some error in the following line and release with `cli/assembly`: https://github.com/olafurpg/scalafmt/blob/406caaaf1738a1d7a6cdd0d6606ac67c5c928327/cli/src/main/scala/org/scalafmt/cli/Cli.scala#L240

**Comment by onilton** [comment]
I think I have a simular issue @windfansy. I could not reproduce your case as @olafurpg said. But this one outputs nothing for me:

Test.scala
```
package anything                                                                                                                                                         

object main {
  def run() = {
  }
}

val a1 = new User(500000)
```

Yeah, I know it may not be valid scala code. But The experience I got when using in vim (autoformat) is  that it delete all my code, so I think this could be an important issue.

`scalafmt -f  Test.scala` also returns nothing.

I think at least it should return the same code that it has received.

**Comment by olafurpg** [comment]
>  The experience I got when using in vim (autoformat) is that it deletes all my code, so I think this could be an important issue.

I agree, this is an important issue. I won't make a new release until after a few weeks though. Until then, you will need to build from source by cloning the repo and running `cli/assembly`. Sorry for the inconvenience. I will keep the issue open until you verify the problem is fixed.

**Comment by onilton** [comment]
@olafurpg I've tested the master version and can confirm it is working for me! :+1:  :smile:

**Comment by olafurpg** [comment]
Observe that if you pass in a large number of named argument you may experience the same issue as #310. Otherwise, the master branch should be quite solid.
