### ISSUE TITLE
Abstract type constructor spuriously "spaced out"

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#312]
Original:
```scala
type F[A]
```

Scalafmt:
```scala
type F [A]  // ??????
```

Question marks may have been added by me…

I would like the input to look like this:
```scala
type F[A]
```

Ideally, scalafmt would actually *remove* spacing in this case if it is present.  I can't think of anyone who prefers a formatting style which injects spaces in this case.

**Comment by olafurpg** [comment]
Dupe of #288? Adding a case for `Decl.Type` in [this match](https://github.com/olafurpg/scalafmt/blob/406caaaf1738a1d7a6cdd0d6606ac67c5c928327/core/src/main/scala/org/scalafmt/util/TreeOps.scala#L214) will do the trick.

**Comment by djspiewak** [comment]
Yes, duplicate. Short term memory loss. :-) Sorry for the noise.
