### ISSUE TITLE
Feature request: Dynamic style configuration

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#315]
Dynamic style configuration allows you to change the style with CLI flags inside comments. For example, increase `--maxColumn` or temporarily enable vertical alignment.

Original:
```scala
val x = 1
val xx = 2
// --style defaultWithAlign
val xxx  = 3
val xxxx = 4
// --style default
val xxxxx = 5
val xxxxxx = 6
```

**Comment by sjrd** [comment]
You probably want to a bit more specific on the identification of such comments, e.g.,
```scala
// scalafmt: --style defaultWithAlign
```

**Comment by sjrd** [comment]
Also, can we have `// scalafmt: off`, which would completely disable scalafmt in a section of the code (e.g., if I'm writing parser combinators or another DSL, just want scalafmt not to touch it).

Oh, and something also nice would be to have a `push`/`pop` feature:
```scala
val x = 1
val xx = 2
// scalafmt: push --style defaultWithAlign
val xxx  = 3
val xxxx = 4
// scalafmt: pop
val xxxxx = 5
val xxxxxx = 6
```
`pop` would pop the style config on the top of a stack of configs. A safer version would be to force `pop` to be given the exact same arguments as the corresponding `push`, e.g.,
```scala
val x = 1
val xx = 2
// scalafmt: push --style defaultWithAlign
val xxx  = 3
val xxxx = 4
// scalafmt: pop --style defaultWithAlign
val xxxxx = 5
val xxxxxx = 6
```
And if I mess it up, scalafmt should report an error while formatting the file, e.g.,
```scala
val x = 1
val xx = 2
// scalafmt: push --style defaultWithAlign
val xxx  = 3
val xxxx = 4
// scalafmt: pop --javadoc    <-- here scalafmt reports an error
val xxxxx = 5
val xxxxxx = 6
```
There could also be an error reported at the end of the file if the stack is non-empty at the end of the file.

**Comment by olafurpg** [comment]
Format off is already supported: https://olafurpg.github.io/scalafmt/#//format:off


> something also nice would be to have a push/pop feature:

I like the idea of `pop`. Alternatively, we could name it `reset` and it let it disable all dynamic configuration.

> A safer version would be to force pop to be given the exact same arguments as the corresponding push.

If we have reset, I don't think this will be necessary.

> There could also be an error reported at the end of the file if the stack is non-empty at the end of the file.

I think that's unnecessarily strict. For example, you might actually want to change the style for an entire file with a header comment.

**Comment by olafurpg** [comment]
BTW. I agree that scalafmt should issue an error if the comments do something wrong, another excellent use case for #290.

**Comment by sjrd** [comment]
> I think that's unnecessarily strict. For example, you might actually want to change the style for an entire file with a header comment.

For that, one would use the non-push variant, which is a hard-set.

> Alternatively, we could name it reset and it let it disable all dynamic configuration.

I thought about that too, but `reset` does not let me to nest different levels of reconfiguration.

**Comment by olafurpg** [comment]
I see, so there could be two ways to define dynamic styles

1. hard-set style: for example `// scalafmt: --maxColumn 150`, which is enabled until the end of the file or if `// scalafmt: reset`.
2. push/pop style: for example `// scalafmt: push --maxColumn 150`, which is enabled until it's popped off `// scalafmt: pop --maxColumn 150`. In this case, I think the safe syntax is a good idea.

I imagine the hard-set style will cover >90% of use-cases for dynamic style configuration, so that would be a good place to start. If it turns out to be limiting, we can add the push/pop style. However, IMO, if you need to deeply nest dynamic style configurations you're probably doing something fishy.

**Comment by sjrd** [comment]
OK
