### ISSUE TITLE
Pathological line-limit interaction with scope opening

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#317]
Original:
```scala
  private def run(implicit S: ScheduledExecutorService): Process[Task, Unit] = {
```

Scalafmt:
```scala
  private def run(implicit S: ScheduledExecutorService): Process[Task, Unit] =
    {
```

I would like the input to look like this:
```scala
  private def run(implicit S: ScheduledExecutorService): Process[Task, Unit] = {
```

Using:
* 0.2.6-RC1
* --style default --maxColumn 80

So, the problem here is that the original input is exactly 81 characters in length.  Scalafmt penalizes this and decides to bump the whole scope to the next line, extra indented.  This makes sense as a general rule, but here it's definitely not the right approach.  A line length overflow of 1 character should not cause the *entire* function body to get indented another level.

**Comment by sjrd** [comment]
Duplicate of #305?

**Comment by djspiewak** [comment]
Yes.
