### ISSUE TITLE
Anonymous inner class as call-site parameter incorrectly indented

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#318]
Original:
```scala
    foo(new Bar {
      def stuff = 42
    })
```

Scalafmt:
```scala
    foo(
      new Bar {
      def stuff = 42
    })
```

There are two options for this snippet, depending on line limit constraints:

```scala
    // if first line is NOT over the limit

    foo(new Bar {
      def stuff = 42
    })

    // if first line is OVER the limit
    foo(
      new Bar {
        def stuff = 42
      })
```

Using:
* 0.2.6-RC1

```
--maxColumn 80
# --binPackArguments false
# --binPackParameters false
# --binPackDotChains false
--continuationIndentCallSite 2
--allowNewlineBeforeColonInMassiveReturnTypes false
--binPackParentConstructors false
--alignByArrowEnumeratorGenerator false
--javaDocs
```

**Comment by olafurpg** [comment]
I agree the first line should fit on the same line. Because #248, scalafmt penalises newlines inside the argument list more aggressively if the first argument stays on same line as `(`. Excluding that aggressive penalty inside blocks `{}` should probably do the trick.

**Comment by djspiewak** [comment]
Makes sense.  I've seen similar issues with terms like `foo(xs map { x => .... })` when broken over multiple lines, so special-casing `{}` should fix both issues.
