### ISSUE TITLE
Keep “extends” on the same line as “)” for config-style class definitions

### ISSUE THREAD

**Issue by stanch** [olafurpg/scalafmt#321]
Original:
```scala
class A(
  x: Int,
  y: String
) extends Serializable {
  def foo = x 
}
```

Scalafmt:
```scala
class A(
  x: Int,
  y: String
)
    extends Serializable {
  def foo = x
}
```

I would like the input to look like this:
```scala
class A(
  x: Int,
  y: String
) extends Serializable {
  def foo = x 
}
```

Using:
* 0.2.6
* --style defaultWithAlign
* --continuationIndentDefnSite 2

**Comment by olafurpg** [comment]
Dupe of #276? Master branch produces expected output. 0.2.5 gets it wrong.

**Comment by stanch** [comment]
Indeed! I did search for “extends” in the issues, but forgot to look at the closed ones :)
