### ISSUE TITLE
Formatting on Windows causes git to think diffs exist when no code has changed

### ISSUE THREAD

**Issue by yilinwei** [olafurpg/scalafmt#322]
You can assign this one for me to look at.

**Comment by olafurpg** [comment]
If you could take a look at this then that would be great. I don't have access to a windows machine to reproduce. I'm guessing the issue might be related to the fact that scalafmt uses `\n` for newlines, some relevant lines [here](https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L118-L120) and a few other places in that same file. If you need any help please let me know.

**Comment by yilinwei** [comment]
Unsure, possibly because I'm not a contributor to the project? You can just leave this issue open and I'll take a look at it in the next few weeks.

**Comment by olafurpg** [comment]
Please reopen if you are able to reproduce this issue.
