### ISSUE TITLE
`extends` gets forced on a new line

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#338]
Original:
```scala
case class ApnsNotificationPayload(
  alert: String,
  badge: Int,
  url: Option[String],
  sound: String = "default"
) extends NotificationPayload {
```

Scalafmt:
```scala
case class ApnsNotificationPayload(
  alert: String,
  badge: Int,
  url: Option[String],
  sound: String = "default"
)
    extends NotificationPayload {
```

Is there any reason to have `extends NotificationPayload {` on a new line?

Using:
* 0.2.5
* --style default

Cheers

**Comment by olafurpg** [comment]
Dupe of #276 and #321?

**Comment by joan38** [comment]
True for #321.
But not sure for #276.

What #321 and me means is that `extends` should probably be following the `)` without any new line.

**Comment by olafurpg** [comment]
See https://github.com/olafurpg/scalafmt/issues/276#issuecomment-220580398
