### ISSUE TITLE
Declaration site parameter wrapping SOMETIMES vertically aligns

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#340]
Original:
```scala
  def driver(implicit S: ScheduledExecutorService, cc: CallContext): Process[Task, Unit] = {
```

Scalafmt:
```scala
  def driver(implicit S: ScheduledExecutorService,
             cc: CallContext): Process[Task, Unit] = {
```

I would like the input to look like this:
```scala
  def driver(implicit
      S: ScheduledExecutorService,
      cc: CallContext): Process[Task, Unit] = {
```

Using:
* 0.2.6

```
--maxColumn 80
# --binPackArguments false
# --binPackParameters false
# --binPackDotChains false
--continuationIndentCallSite 2
--allowNewlineBeforeColonInMassiveReturnTypes false
--binPackParentConstructors false
--alignByArrowEnumeratorGenerator false
--javaDocs
```

I'm really not clear on why scalafmt decides to vertically align the continuation parameter in this particular case.  It certainly does not do it under normal circumstances (e.g. I have other functions which format correctly with respect to the continuation rules).

**Comment by olafurpg** [comment]
Have you tried the new `--alignByOpenParenCallSite false` option?

BTW, scalafmt never breaks after the `implicit` but I've seen that style used in a lot of places. That's warrants a separate ticket though.

**Comment by olafurpg** [comment]
I just realised that the name `alignByOpenParenCallSite` is wrong, it's applied to both formals and actuals. Sorry for the confusion, I opened #342.

**Comment by djspiewak** [comment]
> Have you tried the new --alignByOpenParenCallSite false option?

I had not tried it, but it works quite nicely!  Obviously the name is inaccurate, but the functionality is great.

I can live without the `implicit` breaking.  I like that style mostly because it enables a cleaner style for type level programming.  For example (from Emm):

ORIGINAL: 

```scala
  implicit def corecurse1[F[_], C <: Effects](implicit C: Binder[C], T: Traverser[C], NN: NonNested[C], F: Applicative[F], B: FlatMap[F]): Binder[F |: C] = new Binder[F |: C] {
```

FORMATTED (not with scalafmt):

```scala
  implicit def corecurse1[
    F[_],
    C <: Effects
  ](implicit
    C: Binder[C],
    T: Traverser[C],
    NN: NonNested[C],
    F: Applicative[F],
    B: FlatMap[F]
  ): Binder[F |: C] =
    new Binder[F |: C] {
```

Honestly, I go back and forth on this style.  Obviously, it's inconsistent with "normal" declaration site formatting (e.g. no double-indent, trailing parens, broken type parameters, etc).  However, there's no question that it makes complex type-level programming about as easy to read as can be achieved.  Ultimately, this is where the `implicit` breaking idea comes from.

**Comment by djspiewak** [comment]
I haven't seen this issue since update to 0.2.8.  Should this be closed?

**Comment by olafurpg** [comment]
Great. I'll close this then.

**Comment by djspiewak** [comment]
@olafurpg False alarm.  I found another reproducing case (under 0.2.9; same parameters as before):

```scala
  implicit def child[P, C](implicit ev: C <:< P,
                           ev2: C =/= P,
                           P: ADT[P]): ADT.Aux[C, P.F, P.A] =
```

**Comment by olafurpg** [comment]
Is `--alignByOpenParenDefnSite false`? There's one setting for defn site and another for call site.

**Comment by djspiewak** [comment]
That fixed it!  I forgot that the original individual setting was only supposed to affect call sites, and there are now two separate settings.
