### ISSUE TITLE
Allow configuring pre-comment, post-line spacing

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#341]
Original:

``` scala
  foo       // testing
```

Scalafmt:

``` scala
  foo // testing
```

I would like the input to look like this:

``` scala
  foo    // testing
```

I'd really like this to be configurable.  I prefer a style where the pre-comment, post-line spacing is strictly 4.  Some people try to align their post-line comments.  Others prefer different spacings (obviously, scalafmt defaults to 1 space).

**Comment by olafurpg** [comment]
This should possible to add, although I question the merit of this option 😉 Seems [this line](https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L110) is place to start looking at this. We'll probably need to guard against `tok.right` being of type `Comment` with `tok.right.code` that starts with "//". I assume this flag should override vertical alignment settings. The [readme](https://github.com/olafurpg/scalafmt/blob/master/readme.md) has a tutorial on how to add new style options. A `ScalafmtStyle` instance  is already in scope inside that method.

**Comment by olafurpg** [comment]
Any update on this @djspiewak?

**Comment by olafurpg** [comment]
Closing this since there doesn't seem to be much interest for this feature
