### ISSUE TITLE
Allow multi-line `case` block with `case` on first line?

### ISSUE THREAD

**Issue by lihaoyi** [olafurpg/scalafmt#351]
Original:
```scala
object Foo {
  foo.map{ case i =>
    println(i)
  }
}
```

Scalafmt:
```scala
object Foo {
  foo.map {
    case i =>
      println(i)
  }
}
```

I would like the input to look like this:
```scala
object Foo {
  foo.map{ case i =>
    println(i)
  }
}
```

Using:
* 0.2.8
* `scalafmt -i -f Foo.scala`

Note that this only seems to happen with `case`s; for a lambda without a `case`, the formatting is left unchanged, which is what I want

**Comment by olafurpg** [comment]
I took a stab at this in #150 but with little luck. However, I think I know how to get it done now. Will try for 0.2.10. Gonna close this as it's a dupe.
