### ISSUE TITLE
Keep alignByOpenParenCallSite even if all params fit on the line

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#354]
Hi,

If I have:

``` scala
case class Currency(user_currency: String,
                    usd_exchange: Float,
                    usd_exchange_inverse: Float,
                    currency_offset: Int)
```

With `--maxColumn 120`

Then Scalafmt does:

``` scala
case class Currency(user_currency: String, usd_exchange: Float, usd_exchange_inverse: Float, currency_offset: Int)
```

Would it be possible to have a toggle to format like the original if the first param is on the same line as the class name/method name and the 2nd is on a new line or something?

Meanwhile I do:

``` scala
case class Currency(
  user_currency: String,
  usd_exchange: Float,
  usd_exchange_inverse: Float,
  currency_offset: Int
)
```

Cheers

**Comment by olafurpg** [comment]
I've experienced the same need. I tried to implement something like you suggest but didn't like any of the solutions. Config style,

```scala
case class Currency(
  user_currency: String,
  usd_exchange: Float,
  usd_exchange_inverse: Float,
  currency_offset: Int
)
```

 is probably the way to go. Alternatively, use a lower --maxColumn so that you don't mind it being on a single line ;)

**Comment by olafurpg** [comment]
Am I free to close this issue?
