### ISSUE TITLE
Preserve newlines between vals and their body

### ISSUE THREAD

**Issue by fthomas** [olafurpg/scalafmt#356]
Original:
```scala
val x: Int =
  1
```

Scalafmt:
```scala
val x: Int = 1
```

It would be nice if the input is not reformatted. This behaviour is already implemented for `def`s, i.e. if `x` is a `def`, the newline is kept. I think it is more regular if `val`s and `def`s are treated the same in this regard.

Using:
* 0.2.10
* --style default

**Comment by psttf** [comment]
Is it possible to apply the same behavior to `<-` and `=` in `for` expressions?
