### ISSUE TITLE
macosx/linux script for scalafmt

### ISSUE THREAD

**Issue by NicolasRouquette** [olafurpg/scalafmt#393]
Since I can't use scalafmt with scalameta 1.0.0, I am using the command line application.

That is, I downloaded: https://github.com/olafurpg/scalafmt/releases/download/v0.2.12/scalafmt.tar.gz

This has a bin/scalafmt script that was:

```
#!/bin/sh
java -jar PATH_TO/scalafmt.jar $@
```

This is how I modified to work for both macosx/linux systems:

```
#!/bin/sh

get_full_path () {
  local path="$1"
  [[ -L "$path" ]] && { echo "$path" ; return; }

  if [[ `uname -s` == "Darwin" ]]; then
      if [[ -n $(which -s greadlink) ]]; then
	  die "On MacOSX, use 'brew install coreutils' to install 'greadlink' for determining full paths"
      fi
      local target=$(greadlink -f $1)
  else
      local target=$(readlink -f $1)
  fi

  if [[ "${target:0:1}" == "/" ]]; then
    echo "$target"
  else
    echo "${path%/*}/$target"
  fi
}

declare -r script_path="$(get_full_path "$BASH_SOURCE")"
declare -r script_name="${script_path##*/}"
declare -r script_dir="$(dirname $(dirname $script_path))"
declare -r script_lib="${script_dir}/cli/target/scala-2.11/scalafmt.jar"

java -jar $script_lib $@
```

It is unclear to me how to update the build.sbt script to change the generated script.

**Comment by olafurpg** [comment]
What is the issue?

The `bin/scalafmt` script is not generated by build.sbt, it's zipped as it is in the publish script: https://github.com/olafurpg/scalafmt/blob/3cef851a356c2feffdb224bd8fefe5b546595258/bin/publish.sh#L55

You can install scalafmt on OSX with `brew install olafurpg/scalafmt/scalafmt`. #359 is an open PR to make `bin/scalafmt` bootstrap and even support cool features such as passing in a scalafmt version number.

**Comment by NicolasRouquette** [comment]
The issue is that the generated script requires replacing `PATH_TO`:

```
#!/bin/sh
java -jar PATH_TO/scalafmt.jar $@
```

What I proposed would work regardless of where it is installed on macosx and linux systems.

**Comment by olafurpg** [comment]
Wow, I didn't realise how useful that script is. I would be happy to include it in the repo. However, However, I'm afraid of replacing the the current `bin/scalafmt` script since I know some build tools and package managers rely on it to be the way it currently is. A suitable alternative name for this script could be `bin/scalafmt_auto`, which can then be aliased to `scalafmt` for those who wish. What do you think?

**Comment by NicolasRouquette** [comment]
Good point; you can include as you suggested and mention these in the README.

**Comment by olafurpg** [comment]
Using your script, I put it into the `bin` folder using the name `scalafmt_auto`. The script will be included in tarball releases from now onwards (unfortunately not 0.4.1 which was released today).

**Comment by olafurpg** [comment]
Thanks a lot!
