### ISSUE TITLE
Automate IntelliJ plugin update

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#399]
The publish step for the plugin is too manual so I don't bother for tiny releases, causing #398. The Jetbrains guys showed me at ScalaDays how they build and upload the Scala plugin automatically. It would be great to do something similar for scalafmt.

**Comment by olafurpg** [comment]
Concretely, I want to make the `intellij` directory become part of the main SBT build by using this SBT plugin: https://github.com/dancingrobot84/sbt-idea-plugin

My current workflow for the intellij plugin is this:

- cp fat jar into intellij/lib
- open separate intellij project from `intellij` repo
- import `intellij.iml`
- Build > Prepare plugin for deployment
- Manually upload zip to plugins.jetbrains.com

I would like the workflow to be instead:
- `sbt publishPlugin`

Another great benefit to this change is that it becomes a lot easier for contributors to make changes to the intellij plugin, like in #544.

Any help from someone with SBT experience would be awesome.

**Comment by rbellamy** [comment]
I haven't tried the `sbt publishPlugin` since I don't have the permissions to try that, and am a bit unclear how one would go about testing it without, well, actually publishing the plugin, but it shouldn't be a great stretch to go from PR#655 to publishing.

**Comment by olafurpg** [comment]
Even though it seems I still need to manually upload the zip file to plugins.jetbrains.com, I'm happy to close this issue since most of the laborious steps needed to build the intellij plugin have now been automated thanks to #655. Thank you @rbellamy!
