### ISSUE TITLE
wrap long list extractors

### ISSUE THREAD

**Issue by easel** [olafurpg/scalafmt#408]
I would like long list extractors to respect the maximum line length, or at least respect my original formatting.

Original:
```scala
      case accountIdStr :: userIdStr :: connectorIdStr :: timestampStr :: eventClassStr :: contactIdStr
        :: contactPointIdStr :: contactPointValue :: remoteContactId :: to :: subject :: remoteId
        :: remoteGroupId :: timeZoneStr :: rest ⇒
```

Scalafmt:
```scala
      case accountIdStr :: userIdStr :: connectorIdStr :: timestampStr :: eventClassStr :: contactIdStr :: contactPointIdStr :: contactPointValue :: remoteContactId :: to :: subject :: remoteId :: remoteGroupId :: timeZoneStr :: rest ⇒
```

I would like the output to look like this:
```scala
      case accountIdStr :: userIdStr :: connectorIdStr :: timestampStr :: eventClassStr :: contactIdStr
        :: contactPointIdStr :: contactPointValue :: remoteContactId :: to :: subject :: remoteId
        :: remoteGroupId :: timeZoneStr :: rest ⇒
```

Using:
* 0.2.x
* --style defaultWithAlign
* --rewriteTokens =>;⇒,<-;←
* --maxColumn 112
* --assumeStandardLibraryStripMargin true
* --continuationIndentCallSite 2

**Comment by olafurpg** [comment]
Good catch. Scalafmt should preserve line breaking choices for infix pattern extractors just like it does for infix applications. The output will look like this now

```scala
  case accountIdStr :: userIdStr :: connectorIdStr :: timestampStr :: eventClassStr :: contactIdStr
        :: contactPointIdStr :: contactPointValue :: remoteContactId :: to :: subject :: remoteId
          :: remoteGroupId :: timeZoneStr :: rest =>
```

Since 0.2.6, scalafmt does not line wrap around infix operators because it breaks too many fancy DSLs. You choose the line breaks.

**Comment by olafurpg** [comment]
I'll try to release this asap, would like to fix #405 first.

**Comment by cula** [comment]
The bug still exists in Scalafmt 0.4.8.1.
![Uploading 捕获.PNG…]()

Is there anything I can do to workaround this now?

**Comment by olafurpg** [comment]
@cula this

```
indentOperator.exclude = "^(::|&&|\\|\\|)$"
unindentTopLevelOperators = true
```
will unindent the `::` operator. You choose the line breaks, scalafmt doesn't wrap infix operators.
