### ISSUE TITLE
Line wrapping doesn't work for imports - maxColumn is not respected

### ISSUE THREAD

**Issue by lambdista** [olafurpg/scalafmt#413]
Original:
```scala
import foo.bar.baz.{Alpha, Beta, Gamma, ...}
```

Scalafmt:
```scala
import foo.bar.baz.{Alpha, Beta, Gamma, ...}
```

I would like the input to look like this (actually anything, provided maxColumn is respected):
```scala
import foo.bar.baz.{Alpha, Beta, 
  Gamma, ...}
```

Using:
* 0.3.1
* --style defaultWithAlign
* --maxColumn 120

**Comment by olafurpg** [comment]
I'm unable to reproduce:

```scala
$ scalafmt --style defaultWithAlign --maxColumn 10 -f target/foo.scala
import foo.bar.baz.{
  Alpha,
  Beta
}

object a {
  println(
    1)
}

$ cat target/foo.scala
import foo.bar.baz.{Alpha, Beta}

object a {
  println(1)
}
```

Note that the import line needs to exceed your custom 120 column limit to wrap.

**Comment by olafurpg** [comment]
One option could be to support "config style" import selectors, so that you can force a line break if you wish the same way you can do it with regular applications.

**Comment by lambdista** [comment]
"Note that the import line needs to exceed your custom 120 column limit to wrap." -> Of course! :)

Anyway, my fault, I didn't say the whole story. It doesn't work within IntelliJ by using Ctrl+Shit+L. OTOH using scalafmt from sbt it works. In case you're wondering I have the IntelliJ plugin installed and it works for anything else.

**Comment by olafurpg** [comment]
What version of the IntelliJ plugin are you using? Line wrapping imports
only came last week.

**Comment by lambdista** [comment]
Oh OK, now it works. I don't know why IntelliJ didn't suggest the plugin update.

Thank you for your great work.
