### ISSUE TITLE
Feature request: sbt integration to scalafmt every Nth compile

### ISSUE THREAD

**Issue by ryanberckmans** [olafurpg/scalafmt#418]
Great project! Really enjoying it. 

**Version**: 0.3.1 
**Integration**: sbt, Atom editor
**Configuration**: .scalafmt with maxColumns=100; style defaultWithAlign

As you observe on the scalafmt.org website

> Add reformatOnCompileSettings to you build settings to enable automatically formatting files on compile. WARNING. This setting is very intrusive on text editors and IDEs. I encourage you to find a better way to incorporate scalafmt into your workflow.

A "better way" for me would be, **Feature request: when continuously compiling using `sbt ~compile`, run scalafmt every configurable Nth compile, such as N=20.** This would be really useful because it provides a non-intrusive mechanism to run scalafmt regularly that isn't cobbled together using git hooks, etc.

Also, semi-related, Atom editor's go-plus package runs gofmt on save; Atom seems to gracefully accept gofmt changes, so if I mis-align fields in an enum, (i.e. what scalafmt defaultWithAlign provides), the fields will gracefully jump together in Atom without the entire file flashing or moving the cursor. Whereas when I enable scalafmt on sbt compile, (despite it taking 10 seconds to complete which is irrelevant I think), the entire file flashes and cursor jumps to top of file, which is obviously unusable. Perhaps this is related to how gofmt vs. scalafmt updates the file after formatting? Summary: if Atom didn't "flash file" and move cursor to top, I'd probably use scalafmt on sbt compile.

**Comment by olafurpg** [comment]
> Great project! Really enjoying it.

Glad you like it :)

> Perhaps this is related to how gofmt vs. scalafmt updates the file after formatting? 

The go-plus atom package uses the atom api to write to the file while sbt-scalafmt works on the file system. The atom editor should IMO handle the file write more gracefully, at least keep the cursor on the same line number. This is what I think some other editors try to do.

> when continuously compiling using sbt ~compile, run scalafmt every configurable Nth compile, such as N=20. ... Summary: if Atom didn't "flash file" and move cursor to top, I'd probably use scalafmt on sbt compile.

I think creating an atom plugin for scalafmt would be a better approach than letting sbt run scalafmt on every Nth compile. You could create an atom package similar to this scalariform plugin: https://github.com/gangstead/atom-scala-format That way you won't be surprised when sbt decides to format your file. WDYT?

**Comment by ryanberckmans** [comment]
Thanks for explaining the file handling.

Come to think of it, I won't scalafmt on sbt compile because of the added cycle time. Cycle time is such a valuable metric and scalac already takes awhile.

How do you suggest integrating scalafmt into a development cycle? How do you do it? Just brainstorming solution properties: scalafmt should happen regularly, automatically, with minimal disruptions to rest of development cycle, including editing files, compilation cycle time, and commits.

I'm using `watch --color -n600 sbt scalafmt` for now.

**Comment by olafurpg** [comment]
> I'm using `watch --color -n600 sbt scalafmt` for now.

Note that `sbt scalafmt` can be painfully slow since it loads sbt and then reformats your **whole** project.

> How do you suggest integrating scalafmt into a development cycle? How do you do it?

I use the IntelliJ plugin and run it on the file I'm editing whenever I feel like it. Then I'll run scalafmt from a running sbt before submitting PRs etc.
