### ISSUE TITLE
Align %%% in defaultWithAlign

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#422]

**Comment by olafurpg** [comment]
This entails updating AlignToken.default to include %%% like it already does for %% and %, see https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/AlignToken.scala#L22

It's possible to test the fix here: https://github.com/olafurpg/scalafmt/blob/master/core/src/test/resources/align/AlignTokens.stat#L82

**Comment by melrief** [comment]
Opened a [PR for this](https://github.com/olafurpg/scalafmt/pull/436)

**Comment by olafurpg** [comment]
Closed in #436
