### ISSUE TITLE
Some style options are not parsed well by the CLI parser

### ISSUE THREAD

**Issue by GMadorell** [olafurpg/scalafmt#423]
**Version**: 0.3.1
**Integration**: CLI
**Configuration**:

```
# Test
--style defaultWithAlign
--maxColumn 120
--continuationIndentCallSite 2
--continuationIndentDefnSite 2
--alignStripMarginStrings true
--danglingParentheses true
--alignByArrowEnumeratorGenerator true
--spacesInImportCurlyBraces false
--binPackArguments false
--binPackParameters false
--binPackDotChains false
--binPackParentConstructors false
--binPackImportSelectors false
--reformatDocstrings true
--scalaDocs true

```

Scalafmt output:
```
Error: Unknown option --alignStripMarginStrings
Error: Unknown argument 'true'
Error: Unknown option --binPackArguments
Error: Unknown argument 'false'
Error: Unknown option --binPackParameters
Error: Unknown argument 'false'
Error: Unknown option --binPackDotChains
Error: Unknown argument 'false'
Error: Unknown option --reformatDocstrings
Error: Unknown argument 'true'
Error: Unknown argument 'true'
```

It seems that some valid style options (by looking at https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/ScalafmtStyle.scala) are not parsed well by the CLI parser. Some options seem to be missing from the scallopt configuration function (https://github.com/olafurpg/scalafmt/blob/master/cli/src/main/scala/org/scalafmt/cli/Cli.scala around line 173). Is that right, or am I missing something?

Thanks for the great work by the way ;)

**Comment by olafurpg** [comment]
The only configuration options that I can recommend trying are documented here: https://olafurpg.github.io/scalafmt/#Configuration 

The total list of supported CLI flags is the --help page, which you can see online here: https://olafurpg.github.io/scalafmt/#Usageexamples 

Some of the flags that you reference are not really meant to be used directly, and are intentionally left out. Some of them have different names in the CLI parser (assume std lib strip margin) and ScalafmtStyle (align strip margin). This is really just sloppy on my half, the names should be consistent.

I admit that this the documentation could be clearer on this detail. I hope to iron out this confusion and make the naming more consistent when I reorganize configuration with #316.
