### ISSUE TITLE
OutOfMemoryError: Java heap space when running sbt assembly on Arch Linux

### ISSUE THREAD

**Issue by RatanRSur** [olafurpg/scalafmt#427]
**Version**: 0.3.1
**Integration**: Building from source 3fab42a on Arch Linux

The failure always happens when there are around 7000 remaining.

It usually happens after `3700 processed, 6997 remaining...` but it's gone as far as `3900 processed, 6797 remaining...`

**Comment by olafurpg** [comment]
I've hit into the same issues (freezes around 7k files) and it started when I upgraded the scala.meta dependency to 1.0. It was fine before but I couldn't investigate it further. The update was long due. It still works if you give **very** generous heap space: https://github.com/olafurpg/scalafmt/blob/master/.drone.yml#L4

However, you shouldn't have to run the mega test suite for assembly. The only reason it's there is so I run it before I release, but I can adjust the publish script to do it in a separate task. I'll just remove this section in the build file: https://github.com/olafurpg/scalafmt/blob/master/build.sbt#L115-L118
Until then, I recommend you remove it yourself and try again.

**Comment by olafurpg** [comment]
BTW. `cli/assembly` is what I always run when I need a quick fat jar.

**Comment by RatanRSur** [comment]
Thanks! Running `sbt cli/assembly` worked just fine.
