### ISSUE TITLE
More polished select chains

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#444]
The current select chain rules are pretty ad-hoc at the moment and [badly documented](https://olafurpg.github.io/scalafmt/#Selectchains). Considering select chains are really important in Scala I think they deserve some rethinking.

They rules currently work like this:
- never line break before a dot `.` unless the dot is part of a **breakable** select chain.
- A select chain becomes breakable at the first select dot `.` that leads an application that has parentheses `()` or square brackets `[]`.
- Either all dots in a breakable select chain get a line break or none of the dots get a line break.
- By default, scalafmt puts the entire select chain on a single line if the chain can fit on a single line. PR #440 added a flag `keepSelectChainLineBreaks` that changes the default behavior so that scalafmt will put line breaks before all dots in a breakable select chain if there is a newline before the first dot in the breakable part of the select chain. 

Some examples.
- a really long sequence of `foo.bar.kaz.man.kazam` won't line break since there is no application with `[]` or `()` to make the chain breakable. This might mean that the formatted output exceeds the column limit.
-  in `lst.head.foo(...).kaz` the chain becomes breakable at `.foo` and not `.head`.
- the following example never becomes breakable because the .collect uses curly braces

``` scala
[info]   val cols = flatSchema.getFields.collect {
[info]     case f: PrimitiveType =>
[info]       Column(f.getName, typeMap(f, widths))
[info]   }.toList
```
- `keepSelectChainLineBreaks` is not triggered on the following example because there is no newline before `.from()`.

``` scala
 val serializedBsonByKey= TypedPipe.from()
    .map{Base64.decodeBase64}
    .groupBy{key}
    .head
// scalafmt default output
val serializedBsonByKey =
  TypedPipe.from().map { Base64.decodeBase64 }.groupBy { key }.head
// scalafmt output with newline before .from and keepSelectChainLineBreaks enabled
val serializedBsonByKey = TypedPipe
  .from()
  .map { Base64.decodeBase64 }
  .groupBy { key }
  .head
```
## Some questions
1. Should curly braces trigger the start of a breakable select chain just like `[]` and `()` do? I remember I tried this out and for some cases it wasn't so great.
2. What should the behavior of `keepSelectChainLineBreaks` actually be? Should the option be renamed?
3. More generally, how do you think select chains should format?

The current rules are derived from looking at quite a lot code and any changes to the rules will probably require looking at more diffs. I personally quite like the default behavior except in some cases I think scalafmt should line break select chain even if the chains can fit on a single line.

cc/ @johnynek @melrief

**Comment by johnynek** [comment]
I think the default behavior for keepSelectChainLineBreaks should be that
you only add new lines (never remove them) and you only add new lines in
order to satisfy max line width restrictions.

To the style we use with scalding (at Twitter and Stripe), `.method { }` is
a fine place to break. Side note, I don't think we should always break at
`=>` for instance `.map { x => (x, x) }` but that is another issue probably.

**Comment by olafurpg** [comment]
Following your feedback, I renamed keepSelectChainLineBreaks into `optIn.breakChainOnFirstMethodDot`. The original name was chosen in a rush during a hackathon.

> you only add new lines (never remove them) and you only add new lines in order to satisfy max line width restrictions.

I'm happy to help someone contribute a flag with this behavior. I personally prefer scalafmt to break the whole chain if can't fit on a single line.

> Side note, I don't think we should always break at `=>` for instance `.map { x => (x, x) }` but that is another issue probably.

This sounds related to #357, please pitch in there to bump up the priority.

**Comment by olafurpg** [comment]
Here is a diff from including curly braces as part of select chains: https://github.com/olafurpg/scala-repos/pull/12/files

In general, I like the new changes. For example, here is one of my favorites

```diff
-    Repositories.filter { t =>
-      (t.originUserName === userName.bind) &&
-      (t.originRepositoryName === repositoryName.bind)
-    }.sortBy(_.userName asc).map(t => t.userName -> t.repositoryName).list
+    Repositories
+      .filter { t =>
+        (t.originUserName === userName.bind) &&
+        (t.originRepositoryName === repositoryName.bind)
+      }
+      .sortBy(_.userName asc)
+      .map(t => t.userName -> t.repositoryName)
+      .list
```

What I like most about it is how consistent it looks like. I admit it the floating curly braces may seem weird sometimes
```scala
  }
  .map {
    ...
  }
  .bar {
```

On the other hand, the aligned dots . do make it clear what steps are part of the "pipeline". I also like the fact that it's easier to remove one step from the pipeline by deleting an entire line (dd for vim folks like myself).

I'm tempted to include this change in the default style, with a flag to opt-out.


cc/ @rcavalcanti

**Comment by johnynek** [comment]
This looks nice to me! Is that from the latest release? I'm sorry to say I got buried on a project and have not updated lately (also we have a lot of engineers using the repo with scalafmt linting on so I want to minimize churn of those rules). This would help us since we have a lot of select chains in scalding code.

**Comment by olafurpg** [comment]
That diff is from a PR, #532. The feedback on Gitter was positive, too. I will keep this behavior opt-in for 4.x and flip the switch in 0.5.0.

Any suggestion on a name for the new flag? Currently it's `includeCurlyBraceInSelectChains`

> I think the default behavior for keepSelectChainLineBreaks should be that you only add new lines (never remove them) and you only add new lines in order to satisfy max line width restrictions.

The combination of 

```hocon
optIn.breakChainOnFirstMethodDot = true
includeCurlyBraceInSelectChains = true
```
should roughly achieve that goal. If not, I'm happy to iterate further.

**Comment by michaelahlers** [comment]
@olafurpg, I've run into a confusing (or contradictory?) behavior here, specifically using [Play JSON's functional builder syntax](https://www.playframework.com/documentation/2.8.x/ScalaJsonCombinators).

With the following settings:

```js
includeNoParensInSelectChains = true
optIn.breakChainOnFirstMethodDot = true
// Mentioned here for completeness.
rewrite.rules = [AvoidInfix]
```

This _original_ source:

```scala
List(1)
  .headOption
  .map(_.toString)

(__ \ "a").read[String]
  .and((__ \ "b").read[String])
  .and((__ \ "c").read[String])
```

Formats into:

```scala
List(1).headOption
  .map(_.toString)

(__ \ "a")
  .read[String]
  .and((__ \ "b").read[Int])
  .and((__ \ "c").read[Long])
```

scalafmt removes the break before `.headOption` (as expected) but then adds one before the first `.read[String]` in the builder making for an unnatural visual scan of the `Reads` definition.

Here's what I'd _really_ prefer, but expect isn't possible:

```scala
List(1)
  .headOption
  .map(_.toString)

(__ \ "a").read[String]
  .and((__ \ "b").read[Int])
  .and((__ \ "c").read[Long])
```

**Comment by kitbellew** [comment]
> (__ \ "a").read[String]
>   .and((__ \ "b").read[Int])
>   .and((__ \ "c").read[Long])
> ```

@michaelahlers try `newlines.source = fold`; keep in mind that this setting will change a lot of other stuff.

Other option you could set (along with `fold`) are `optIn.breakChainOnFirstMethodDot = false`, `includeCurlyBraceInSelectChains = true` and `includeNoParensInSelectChains = false`.
