### ISSUE TITLE
Rewrite rule: add final to case class

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#446]
Context: https://twitter.com/lambdista/status/769112213072277504

```scala
case class Foo(i: Int)
```
I would like the input to look like this:
```scala
final case class Foo(i: Int)
```

cc/ @lambdista

**Comment by dwijnand** [comment]
Adding `final` to case classes isn't always safe: https://github.com/puffnfresh/wartremover/issues/136#issuecomment-84375345

**Comment by olafurpg** [comment]
Wow, I didn't know that. We can limit the rewrite to non-nested case
classes.

**Comment by lambdista** [comment]
Even if I suggested that, on second thought, since scalafmt is a formatting tool it should do just that. I agree with what you said, that is this feature should belong to scalafix or something similar.

**Comment by olafurpg** [comment]
I think we're safe to drop this issue given the feedback here and [on Twitter](https://twitter.com/olafurpg/status/777273182919294976).
