### ISSUE TITLE
Reorganize ScalafmtStyle

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#453]
Since we'll overhaul how configuration is read in #316 we might as well overhaul ScalafmtStyle into something more maintainable

I propose using these definitions

```scala
sealed abstract class Docstring
object Docstring {
  case object Scala extends Docstring
  case object Java extends Docstring
  case object Preserve extends Docstring // --reformatDocstrings false
}
case class IndentOperator(include: String, exclude: String)
case class Location[T](callSite: T, defnSite: T) // make ADT and include `ImportSelectors[T]`?
case class Align(
  byOpenParen: Location[Boolean],
  byArrowEnumeratorGenerator: Boolean,
  byIfWhileOpenParen: Boolean,
  tokens: Set[AlignToken],
  mixedOwners: Boolean
)
case class Spaces(
  contextBoundColon: Boolean,
  afterTripleEquals: Boolean,
  inImportCurlies: Boolean
)

case class Rewrites(
  tokens: Map[String, String],
  transformations: Seq[Rewrite], // see https://github.com/olafurpg/scalafmt/pull/447
)

case class ScalafmtStyle(
  maxColumn: 80,
  binpack: Location[Boolean], // what about binPackImportSelectors?
  continuationIndent: Location[Int],
  align: Align,
  indentOperator: IndentOperator,
  rewrite: Rewrites,
  // missing fields
)
```

Feedback is very welcome. I'm especially interested in suggestions to rename confusing field names.

**Comment by sjrd** [comment]
If you care about the binary compatibility of your style API, don't use case classes. You cannot even *add* a field to a case class without completely breaking its binary compatibility. Case classes should be used for things that you intend to pattern-match on, and *possibly* as a convenience for easy equals/hashCode but *only* if their fields are fixed for all eternity. This is clearly not the case here.

For a good way to define evolvable config APIs, have a look at https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/sem/Semantics.scala

**Comment by olafurpg** [comment]
Excellent point @sjrd, I had forgotten about that one. I still think I would rather prioritize these two

- ease of adding/updating one field (that's essentially why ScalafmtStyle is currently a flat case class right now).
- easy to serialize/deserialize into formats like JSON/YAML (some libraries like upickle rely on the existence of an unapply/apply). 

Still, the world is unfair. I want all of the above AND binary incompat!

**Comment by sjrd** [comment]
> AND binary incompat

Rejoyce, binary <ins>**in**</ins>compat is quite easy to achieve :smile:

**Comment by olafurpg** [comment]
WIP look for the new hierarchy:

https://github.com/olafurpg/scalafmt/pull/459/files#diff-035d8a3f2c8fa32d4e6333dfb183df46R35

It should be possible to let the `@ConfigReader` macro create copy/toString/equals/hash method so we get binary compat too.
