### ISSUE TITLE
scalafmtTest should be more lenient

### ISSUE THREAD

**Issue by elibarzilay** [olafurpg/scalafmt#462]
I've been trying to play with using scalafmtTest in a project to enforce some style, and it looks to me like its utility is very limited.  The problem is that AFAICT scalafmtTest will basically run scalafmt and barf if the result is different from the source.

As someone who cares a lot about code formatting (and therefore really likes the idea of a tool to enforce style), this is a major problem since when I write code in a specific way, it is almost always something that I did intentionally.  I'd feel even less happy about using scalafmtTest for all code in the project that other people wrote.

I'm not sure how to resolve this issue / feature request / generic whinage.  I have a general idea that a good system would allow me to specify a bunch of rules for `scalafmt`, and a subset of these rules for `scalafmtTest`.  The subset-ness can be just omitting some rules from the testing but continue using them when formatting, and it can be having a more lenient version of the rule -- for example, have a wider maxColumn for testing.

Here are a bunch of examples that I found in a first trial run -- all of these are formatted as I want to, yet scalafmtTest barfs at them.

    // (I don't want to add an empty line just to get the formatting
    // right)
    val foo  = 3
    val blah = 4
    val mu   = 5
    val someDefaultArgumentWithAVeryLongNameIsntThisObnoxious = 6
    val foo      = 7
    val blah     = 8
    val whatever = 9

    // much worse with patterns
    val foo = 3
    val bar = 4
    val (something, somethingElse, anotherThing) = blah()

    // the flags are logically grouped
    scalacOptions ++= Seq(
      "-encoding", "UTF-8",
      "-deprecation", "-unchecked", "-feature",
      "-Xfatal-warnings", "-Xlint", // fatal warnings
      ...

    Command.command("full-build") { st =>
      st.copy(remainingCommands = Seq(
                "show-section Update",          "update",
                "show-section Compile Sources", "compile",
                "show-section Compile Tests",   "test:compile",
                "show-section Running Tests",   "test",
                "show-section Packaging",       "package"
                ) ++: st.remainingCommands)
    }

    // sometimes it makes sense to have this indentation instead of
    // dropping the bar to the next line
    val stuff = foo.bar(something)
                   .blah()
                   .whatever()

    val stuff = Seq((0, "guitar"),
                    (1, "piano"),
                    (2, "bass"),
                    (3, "drums"))

**Comment by olafurpg** [comment]
Could you elaborate on what your issue is exactly? It would be great help if you followed the issue template: original/scalafmt/expected.

**Comment by elibarzilay** [comment]
(Apologies for the unclear explanation -- because of some unrelated problem the original text I wrote was lost, and when I typed it a second time I was lazy...)

No, it's not an unexpected formatting -- it's the fact that it's much more useful if scalafmtTest accepts things more leniently.  To use the last example -- running scalafmtTest with this in the source:

    val stuff = Seq((0, "guitar"),
                    (1, "piano"),
                    (2, "bass"),
                    (3, "drums"))

produces an error.  This means that if I make scalafmtTest a mandatory test that is required to pass for new code, then I'm forcing the person who wrote the above code to replace it with:

    val stuff = Seq((0, "guitar"), (1, "piano"), (2, "bass"), (3, "drums"))

but this is less readable (and editable, since it's in a test case) than the original.  This means that in this case I don't want `scalafmtTest` to complain because code didn't follow what `scalafmt` does.

A different example is the way curried definitions are mis-formatted.  If `scalafmtTest` is a requirement, I *must* live with the bad code until it is fixed, instead of being able to just accept whatever the human author wrote.

Yet another example is the `scalacOptions` flags above: I didn't put all flags on their own lines because they are related in various ways, yet if `scalafmtTest` is a requirement, then I have to stick to the all-on-one-line-or-each-on-new-line rule.  This rule is also good example for something that often trips style checkers: *usually*, you want the rule, but there are exception cases where it doesn't make sense.  I've seen (elsewhere) examples of code that looks like:

    printf("some long format %s string, with a few %s in it -- %s",
           str,
           another,
           lastOne)

but it really makes more sense to have a newline after the initial, long argument, and then no newlines later:

    printf("some long format %s string, with a few %s in it -- %s",
           str, another, lastOne)


### Alternative explanation

A good workflow with an auto-formatter of any kind (even as simple as auto-indenting after a newline) is to have it do its automatic work as usual, while allowing you to judge when you want to diverge and fix things to look differently.  But there are certain rules that are much more important and should not be broken even when you diverge.  For example, going from the first `printf` example above to the second one is something that an auto formatter won't decide to do, but a tester shouldn't barf at the result.  If I were fixing it to be:

    printf("some long format %s string, with a few %s in it -- %s",
                            str,              another,    lastOne)

then things are slightly more barf-able, but

    printf("some long format %s string, with a few %s in it -- %s",
         str, another, lastOne)

is much worse, and

    printf("some long format %s string, with a few %s in it -- %s",
    str, another, lastOne)

is so bad it can just as well be a compiler error.  So what I want is to discuss this with other people in the project, and agree on some line that shouldn't be crossed (one of the above examples that is bad enough to reject), and make `scalafmtTest` barf when it is sees that (but still be able to use scalafmt for suggested edits).

**Comment by olafurpg** [comment]
FYI, you can force "config style" in this case

```scala
// newline after ( and before )
val stuff = Seq(
(0, "guitar"),
                (1, "piano"),
                (2, "bass"),
                (3, "drums")
)
// becomes
val stuff = Seq(
  (0, "guitar"),
  (1, "piano"),
  (2, "bass"),
  (3, "drums")
)
```

For the printf example, your best bet is // format: off if you want to achieve that formatting. Alternatively, use string interpolators which are safer anyways.

I understand sometimes you want more control over the line breaks in argument lists. I am happy to guide on how to contribute such a change to scalafmt, I suspect many people might like that feature. I'm doing my best to make this project a community effort, see hacking on scalafmt tutorial here: https://github.com/olafurpg/scalafmt

My personal motivation for scalafmt was that I want to think less where I insert line breaks and more about the problem I'm solving. Sometimes this comes at the price of suboptimal formatting and I am OK with that. When I can't stand the output from scalafmt I fix the bug until I'm happy : )

**Comment by sjrd** [comment]
@olafurpg I think you're misunderstanding @elibarzilay's point here. They want `scalafmt` to keep doing its job as it currently does, but `scalafmtTest` to be less strict.

@elibarzilay I don't think this fits the model of scalafmt. `scalafmtTest` really is just about asserting that the author of a commit/PR ran `scalafmt` before committing. This ensures that subsequent contributors who clone the repo will not introducing whitespace changes in unrelated parts of *their* commits simply by running `scalafmt`. In other words, `scalafmtTest` enforces that `scalafmt` is consistently used all the time.

I think the proper way to escape from `scalafmt` (and therefore `scalafmtTest`) harming your carefully chosen style is to use `// format: off` in the places where `scalafmt` does a bad job.

Your suggestion of changing `scalafmtTest` to be more lenient than `scalafmt` would cause considerable problems to contributors of your codebase. Indeed, they could not run `scalafmt` without causing changes everywhere in the codebase that are unrelated to their work. So effectively it becomes impossible to use `scalafmt` on your codebase at all, which defeats the purpose.

**Comment by elibarzilay** [comment]
@olafurpg, yeah, I think that you misunderstood, as @sjrd described.

@sjrd, yes -- I *don't* want people to just run `scalafmt` as a global rewrite, I want people to use it to help them in formatting new code that they're writing, then use `scalafmtTest` to assure some specific minimum rule following.  I've seen the `// format: off` thing, but the way it looks now, our code will get littered with many these things.  Whatever work is done, there are always cases where a human author knows more than the code: see the two examples I have with sequences of strings --- putting each string on a line is visibly worse formatting, but that only because of the contents of the strings.

If some programmers really don't care about the actual source code, then they would in theory be fine with code being saved in any way (perhaps with newlines everywhere to get the most of source control) with something like a git smudge filter that would run scalafmt on code you check out.  But those of us who care about how code looks like won't be happy with that...

**Comment by sjrd** [comment]
> I don't want people to just run scalafmt as a global rewrite

Then I think `scalafmt` is not the right tool for you. The original, core philosophy of `scalafmt` is that one should globally use it, all the time.

Other tools like Scalariform and/or Scalastyle might fit your requirements better. Scalariform will for example fix the things that are "obviously wrong", and let your code be for everything else. Scalastyle is a checker-only with similar ideas.

**Comment by elibarzilay** [comment]
OK, and thanks for the pointers.  (I was hoping that scalafmt could be used since it looks more sophisticated, and it's more alive than those two...)

BTW, maybe it helps to phrase this whole thing in yet another way: putting aside the question of whether it's a good idea to have automated pushes, it sounds like `scalafmtTest` could be redundant if instead you set things up so every push to a repo is followed by an automatic push of the formatted code (if there are changes).  That's exactly the kind of thing that I find little use for...
