### ISSUE TITLE
for rewrite rule

### ISSUE THREAD

**Issue by johnynek** [olafurpg/scalafmt#470]
it would be nice to turn:
```scala
for(a <- as; b <- bs) yield (a, b)
```
into:
```scala
for {
  a <- as
  b <- bs
} yield (a, b)
```
which is to say, always prefer `{ }` in `for` and use newline not, `;`

**Comment by olafurpg** [comment]
That seems like an excellent rewrite candidate. I welcome contributions if anyone is interested in taking a swing at this.

For inspiration, here is the implementation of the RedundantBraces rewrite: https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

Here's how to the RedundantBraces test suite looks like: https://github.com/olafurpg/scalafmt/blob/master/core/src/test/resources/rewrite/RedundantBraces.stat

To run only that test suite, prepend `ONLY` to the top of the file and run `~core/testOnly org.scalafmt.FormatTests`.

Here's how to get started with parsing scala.meta (using ammonite):

```scala
@ load.ivy("org.scalameta" %% "scalameta" % "1.1.0")

@ import scala.meta._
import scala.meta._
@ """for(a <- as; b <- bs) yield (a, b)
  """.parse[Stat].get.structure
res2: String = """
Term.ForYield(Seq(Enumerator.Generator(Pat.Var.Term(Term.Name("a")), Term.Name("as")), Enumerator.Generator(Pat.Var.Term(Term.Name("b")), Term.Name("bs"))), Term.Tuple(Seq(Term.Name("a"), Term.Name("b"))))
"""
```

Here's a tutorial on scala.meta: https://olafurpg.github.io/scala.meta-workshop/

(The hackathon label is for the Scala Center hackathon at Lambda World this weekend)

**Comment by caoilte** [comment]
I'm looking at this with andrasp3a at the LambdaWorld 2016 Hackathon

**Comment by olafurpg** [comment]
@johnynek Could you give #483 a try?

**Comment by olafurpg** [comment]
Fixed in #483

**Comment by johnynek** [comment]
@olafurpg will try and report back.

**Comment by olafurpg** [comment]
@johnynek I can publish 0.4.3-RC1

**Comment by olafurpg** [comment]
0.4.3-RC1 should sync to maven in the next ~30 min.
