### ISSUE TITLE
No meaninful error messages while parsing .scalafmt.conf file

### ISSUE THREAD

**Issue by lespea** [olafurpg/scalafmt#473]
While migrating to 0.4.1. I had some legacy settings and when running scalafmt I got this ugly output (in sbt); it would be great if you could show what/where the problem is!

```
[info] Formatting 2 Scala sources {file:/home/adam/devel/test/}root ...
[trace] Stack trace suppressed: run last compile:scalafmt for the full output.
[error] (compile:scalafmt) scala.collection.parallel.CompositeThrowable: Multiple exceptions thrown during a parallel computation: org.scalafmt.Error$InvalidScalafmtConfiguration: Unable to parse scalafmt configuration file: /home/adam/devel/test/.scalafmt.conf
[error] org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:22)
[error] org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:22)
[error] scala.Option.getOrElse(Option.scala:121)
[error] org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:21)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:85)
[error] org.scalafmt.sbt.HasScalaFmt$$anonfun$writeFormattedContentsToFiles$1$$anonfun$apply$3.apply(HasScalaFmt.scala:54)
[error] .
[error] .
[error] .
[error] Total time: 0 s, completed Sep 27, 2016 10:09:53 PM

```

* **Version**: 0.4.1
* **Integration**: sbt

**Comment by olafurpg** [comment]
I agree that it would be nice if the SBT plugin would print a friendly message like "seems like you're using the old configuration, use the CLI to migrate" instead of throwing an `InvalidScalafmtConfiguration` exception. The intellij plugin prints a migration warning message.

I don't personally use the SBT plugin, any help to improve the experience is welcome.

**Comment by lespea** [comment]
The error occurs if there is any syntax problems... maybe you could change your exception message `Unable to parse scalafmt configuration file` to include the part it couldn't parse?  I assume it's your code that's generating that message anyway.  The main problem is the user has no way of knowing what needs to be changed to fix the parsing errors without trial and error.

**Comment by olafurpg** [comment]
The error message from the parser is thrown away here: https://github.com/olafurpg/scalafmt/blob/master/cli/src/main/scala/org/scalafmt/cli/StyleCache.scala#L28

The exception in the SBT plugin is thrown from here: https://github.com/olafurpg/scalafmt/blob/master/cli/src/main/scala/org/scalafmt/cli/Scalafmt210.scala#L22

I welcome any contribution to improve the migration experience. At the moment I am quite busy with work.

**Comment by olafurpg** [comment]
the sbt plugin should not print an error message with a link to the changelog
