### ISSUE TITLE
File formats without warnings but fails scalafmtTest

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#476]
File source:
https://github.com/scala-native/scala-native/blob/master/tools/src/main/scala/scala/scalanative/linker/Classpath.scala

Build failure:
https://travis-ci.org/scala-native/scala-native/jobs/163671348#L1579

**Version**: 0.4.1
**Integration**: sbt
**Configuration**: https://github.com/scala-native/scala-native/blob/bb43ff88c551407c0a75ca2efff35c666781cc9c/.scalafmt

**Comment by densh** [comment]
EDIT: It's linker/Classpath not linker/Linker.

**Comment by olafurpg** [comment]
@densh Using the CLI, I'm unable to reproduce non-idempotent formatting for Classpath.scala. Did you run `sbt clean` before `sbt scalafmt`? The scalafmt tasks uses the SBT `FileFunction.cached` to prevent reformatting all files in the project on every compile.

**Comment by olafurpg** [comment]
`sbt clean scalafmt` solved this issue. More SBT troubleshooting tips are in the docs: https://olafurpg.github.io/scalafmt/#SBT
