### ISSUE TITLE
No way to exclude sbt file from being auto-discovered

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#481]
Scala Native fetches `scala/scala` to compile standard library for native. That one contains sbt build definition that is not well formatted according to Scala Native style, but we don't care about it. It seems that there is no way to make `scalafmtTest` not to check that file. Things I've tried:
1. Explicitly list our sbt files via `scalafmtSbtFiles`
2. Exclude all sbt files via `excludeFilter in hasScalafmt := ".sbt"`
3. `formatSbtFiles := false`

No matter what it manages to find `scala/scala`'s sbt file and fail our build due to that. 

https://travis-ci.org/scala-native/scala-native/jobs/163990424#L1566

**Version**: 0.4.1
**Integration**: sbt
**Configuration**: https://github.com/scala-native/scala-native/pull/304/files

**Comment by olafurpg** [comment]
Is `scala/scala` an unmanagedSourceDirectory? If so and `formatSbtFiles := true` then it will format sbt files in `scala/scala`.

**Comment by densh** [comment]
No, I don't think so. It's in `scalalib/target/scalaSources` which is not managed by sbt at all. I think you are doing too aggresive of a search starting from root folder in the sbt plugin. Interestingly there seems to be no way to turn it off completely and it's blocking me.

**Comment by olafurpg** [comment]
I'm hopeful that #486 might be able to solve this problem. I've given up on trying to use the sbt build settings to decide which files to format.

**Comment by olafurpg** [comment]
The recommended way to use scalafmt in a repo is the CLI with coursier, see https://olafurpg.github.io/scalafmt/#Coursier

Instructions on how to exclude/include files with the CLI are here: https://olafurpg.github.io/scalafmt/#project

**Comment by olafurpg** [comment]
I'll keep this open in case someone wants to fix this in the SBT plugin.

**Comment by olafurpg** [comment]
The old sbt plugin has been removed in favor of the CLI.
