### ISSUE TITLE
Pull out project model from version control

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#486]
Following discussions with @densh about #481.

It would be neat if scalafmt just pulled out which files to format from git/hg. For example,

```sh
# Show tracked files
git ls-tree -r HEAD --name-only
# Show root directory of project
git rev-parse --show-toplevel
```

I'm sure we can do similar things with other VCS. Users could choose the project resolve mode:

- manual: explicitly list which files should format. This is currently the only supported mode in the CLI.
- sbt: the current buggy/ad-hoc implementation based on `unmanagedSources`  + `excludeKeys` + ... that seems to be confusing for many users.
- git: should probably work for most users, I would use personally use this. The SBT plugin could be configured to use this mode instead of the current crappy sbt implementation.
- hg: if someone wants to contribute that
- ???

Using this system, the default behavior of running `scalafmt` with no flags from the CLI could be to format all files in the current project.

**Comment by sjrd** [comment]
I like the basic idea, but there are difficulties.

First, this would make it harder to use `scalafmt` in quick projects that are not (yet) under VCS. Or under a different, unsupported VCS (git and hg form the bulk of OSS software, but I think you'll still find a bunch of proprietary VCSes within closed codebases).

For `scalafmtTest`, it also couples your CI with your VCS. This might not always be what you want.

Finally, in some cases I would *still* want exceptions. For example, I absolutely do not want scalafmt to format the files under https://github.com/scala-js/scala-js/tree/master/scalalib. I want them to keep the exact formatting (up to the number of trailing spaces on lines) that they have in scala/scala, to minimize diffs wrt. upstream and ease merges.

**Comment by olafurpg** [comment]
@sjrd I agree, I edited the list above to include "manual" mode, which is currently what the CLI does.

> you'll still find a bunch of proprietary VCSes within closed codebases

Of course, and those are free to either use the manual mode or contribute their own mode.

> Finally, in some cases I would still want exceptions.

Good point. It should always be possible to provide an `exclude` regexp to exclude certain files. The modes should maybe also combine, so you can for example use the git mode + manual mode to add a few more files that are not tracked by git (for whatever reason).

**Comment by olafurpg** [comment]
#498 added support to extract the project layout from git. It's still possible to manually specify which files to include/exclude. I'm happy to discuss support for other VCS if this feature turns out to be successful and there's demand for it.
