### ISSUE TITLE
Confusing FormatTest error message when stat file contains invalid config

### ISSUE THREAD

**Issue by caoilte** [olafurpg/scalafmt#488]
I saw a unit test error message while working on [470](https://github.com/olafurpg/scalafmt/issues/470) that was hard to understand. 

It turns out the error message is being thrown away just like in [478](https://github.com/olafurpg/scalafmt/issues/478). 

The specific problem is we don't handle the error here,

https://github.com/olafurpg/scalafmt/blob/7c765ac28bf0ad2f8f7c7e902635a07554dda8bd/core/src/test/scala/org/scalafmt/util/HasTests.scala#L90

and so the code continues until

https://github.com/olafurpg/scalafmt/blob/7c765ac28bf0ad2f8f7c7e902635a07554dda8bd/core/src/test/scala/org/scalafmt/util/HasTests.scala#L195

at which point all context about the error (except which directory it is in - which is very confusing) has been lost.

-----

To reproduce this error take an existing stat file and break the config, eg I had ```rewrite.rules = [ReplaceForParensWithBraces]``` (which no longer exists).

A simple `case Left(e)` on line 90 would handle this case. I'd be happy to submit a small PR with the change if that all sounds okay in principle.

**Comment by caoilte** [comment]
Oh, I see. It's not quite as simple as that. Ick. Ok this is the least invasive change,

``` scala
        case other => {
          try {
            spec2style(spec.replaceFirst("/.*", ""))
          } catch {
            case e:UnknownStyle => {
              if (other.isLeft) throw new Exception(s"Error in spec ${spec} check stack for details", other.left.get)
              else throw e
            }
          }
        }
```

Might be better if different types of tests specified their configuration mechanism (ie either derived from the directory or manually overriden) - but I don't fully understand your approach here so I'm not sure.

For example, is the "80 columns" here config or the title of the test?

https://github.com/olafurpg/scalafmt/blob/7c765ac28bf0ad2f8f7c7e902635a07554dda8bd/core/src/test/resources/align/AlignTokens.stat#L1

**Comment by olafurpg** [comment]
I only added last week the ability to define configuration in .stat files. Before that the configuration was derived from the folder name. I didn't migrate all of the old tests to the new setup because for some of the bigger styles I have a large number of files in each folder.

My solution was to try and parse config from the top of the file and then fallback to the folder name on failure. We can easily swap that and first try and derive configuration from the folder name and then fallback to reading the configuration from the top of the file. This allows us to throw an exception with a useful error message.

WDYT?

**Comment by olafurpg** [comment]
> For example, is the "80 columns" here config or the title of the test?

It's discarded, it was only used as a guidance to see where the column limit was.

I welcome a PR if you want to take a stab at this :)

**Comment by caoilte** [comment]
Ok,
I could prefix every '80 Columba's etc with a // and then take out two spaces.

Then any lefts might be genuine. That sound ok?

**Comment by olafurpg** [comment]
I figured I might as well do this quickly, #489 just flipped around the order so we first try to derive a style from the folder and then from the config at the top of the file.

**Comment by caoilte** [comment]
Works just as well. Maybe I'll try and pickup another issue later in the week. :-)
