### ISSUE TITLE
Formatting *.sbt files?

### ISSUE THREAD

**Issue by michalrus** [olafurpg/scalafmt#493]
**Version**: 0.3.1
**Integration**: sbt
**Configuration**: `--style defaultWithAlign --maxColumn 80 --rewriteTokens =>;⇒,->;→,<-;←`

I was using `project/Build.scala` which, at the time, was being autoformatted. But after switching to `build.sbt`, this cool behavior is lost. :crying_cat_face: 

Can I somehow add `**/*.sbt` to scalafmt’s file/glob list?

**Comment by olafurpg** [comment]
Could you try to upgrade scalafmt? There should be no diff from 0.3.1 to 0.4.3. The latest version of scalafmt can format .sbt files and the SBT plugin should by default include all .sbt files.

**Comment by michalrus** [comment]
Cool, it works. :smiley:  Sorry for not noticing this earlier, I somehow missed the newest release. I think https://scalariform.org pointed to it, at least not that long ago? However, now it’s down. Well, nevermind.

However, adding `reformatOnCompileSettings` doesn’t trigger reformatting sbt files before compilation. Not that surprising, given its definition. How do you do it? Manually running `scalafmt`?

**Comment by olafurpg** [comment]
> https://scalariform.org pointed to it

That's another formatter. http://scalafmt.org is for this project.


>  How do you do it? Manually running scalafmt?

I use the IntelliJ plugin. I welcome any contributions to improve the sbt plugin ^^

**Comment by michalrus** [comment]
Haha, yes, excuse me, I obviously meant http://scalafmt.org/ — this one’s down. :smile_cat: 

Okay, I see. =) So I guess we can close this one. Thank you very much! :heart:
