### ISSUE TITLE
Improve formatting of for comprehension?

### ISSUE THREAD

**Issue by dabd** [olafurpg/scalafmt#494]
This template isn't a strict requirement to open issues, but please try to provide as much information as possible.

**Version**: (for example, 0.3.1) 0.4.3
**Integration**: (for example, intellij, sbt, library) intellij
**Configuration**: (for example, `--maxColumn 120`)
maxColumn = 120
bestEffortInDeeplyNestedCode = true

```scala
 val genValidExpense = for {
      expenseType <- Gen.oneOf(ExpenseType.values.toList)
      totalAmount <- Gen.choose(1000, 5000)
      disallowableAmount <- if (expenseType == ExpenseType.Depreciation) Gen.const(totalAmount)
      else Gen.choose(1, totalAmount - 1)
    } yield Expense(`type` = expenseType, totalAmount = totalAmount, disallowableAmount = Some(disallowableAmount))
```

Scalafmt:
```scala
 val genValidExpense = for {
      expenseType <- Gen.oneOf(ExpenseType.values.toList)
      totalAmount <- Gen.choose(1000, 5000)
      disallowableAmount <- if (expenseType == ExpenseType.Depreciation) Gen.const(totalAmount)
      else Gen.choose(1, totalAmount - 1)
    } yield Expense(`type` = expenseType, totalAmount = totalAmount, disallowableAmount = Some(disallowableAmount))
```

I would like the input to look like this:
```scala
 val genValidExpense = for {
      expenseType <- Gen.oneOf(ExpenseType.values.toList)
      totalAmount <- Gen.choose(1000, 5000)
      disallowableAmount <- if (expenseType == ExpenseType.Depreciation) Gen.const(totalAmount)
                                             else Gen.choose(1, totalAmount - 1)
    } yield Expense(`type` = expenseType, totalAmount = totalAmount, disallowableAmount = Some(disallowableAmount))
```

**Comment by dabd** [comment]
I cannot get the github code formatter to align the 'else' with the 'if' in the for comprehension, but that would be the desired output.

**Comment by olafurpg** [comment]
How does it look like with `align.arrowEnumeratorGenerator = true`?

**Comment by dabd** [comment]
Looks much better but the 'else' is unindented 1 space to the left relative to the 'if'

**Comment by olafurpg** [comment]
The alignment by the arrow generator is an experimental flag, I welcome any contributions to improve it.

I would personally wrap the if/else in a block to get the full horizontal space.

**Comment by dabd** [comment]
Thanks for the suggestions. I'm happy if you want to close the issue.

**Comment by olafurpg** [comment]
I hope it helped :)
