### ISSUE TITLE
In Scala.js style, should never ever break in the middle of a result type

### ISSUE THREAD

**Issue by sjrd** [olafurpg/scalafmt#496]
**Version**: 0.4.3
**Integration**: sbt
**Configuration**: `style = Scala.js`, `maxColumn = 80`

```scala
   def permissionState(
      options: PushSubscriptionOptions = js.native): js.Promise[PushPermissionState] = js.native
```

Scalafmt:
```scala
   def permissionState(
      options: PushSubscriptionOptions = js.native): js.Promise[
      PushPermissionState] = js.native
```

I would like the input to look like the original, i.e.,
```scala
   def permissionState(
      options: PushSubscriptionOptions = js.native): js.Promise[PushPermissionState] = js.native
```
I don't care that the line is too long in this case. I just want scalafmt not to break in the middle of the result type, because the resulting code is much harder to read than the variant that overflows the line length limit.

This is a complete diff of all the similar problems in scalajs-dom: https://gist.github.com/sjrd/a6426e2bcbe6a7bfcc58101338424aff

I'm fine if this is a configuration option; it should be activated in `Scala.js` style.

**Comment by sjrd** [comment]
This is the only issue that's blocking me from enabling scalafmt on scalajs-dom.

**Comment by olafurpg** [comment]
We can add a flag like `newlines.neverInTypeApply` which would disable all line breaks inside argument lists of square brackets (`[XXXX, YYYY]`). This includes def result types as well as type arguments at call-site

```scala
// column limit |
val writer =
  Writer.apply[MySuperLongType]
val writer =
  Writer.apply[MySuperLongType, Effect, Bananas]
```

WDYT?

**Comment by sjrd** [comment]
Hum ... I'd have to see what unintended effects such a generalization would have on my codebases.

In general, breaking in type arguments is not bad. It's just bad in the result type because it wraps under the last parameter, so you think it's part of the parameter but in fact it's not. This confusion does not happen in other uses of type parameters, where I'm fine with breaks (and probably sometimes want them).

**Comment by sjrd** [comment]
For example, here is a legitimate diff which breaks inside TypeApplys. In this case it's fine because it's not a result type. You can see that the resulting formatting does not have the unreadable problem that happens with result types:
```diff
 @js.native
 class Promise[+A](
-    executor: js.Function2[js.Function1[A | Thenable[A], _], js.Function1[scala.Any, _], _])
+    executor: js.Function2[
+        js.Function1[A | Thenable[A], _], js.Function1[scala.Any, _], _])
     extends js.Object with js.Thenable[A] {
 
-  def `then`[B](
-      onFulfilled: js.Function1[A, B | Thenable[B]],
-      onRejected: js.UndefOr[js.Function1[scala.Any, B | Thenable[B]]] = js.undefined): Then
+  def `then`[B](onFulfilled: js.Function1[A, B | Thenable[B]],
+      onRejected: js.UndefOr[js.Function1[scala.Any, B | Thenable[B]]] =
+        js.undefined): Thenable[B] = js.native
 
-  def `then`[B >: A](
-      onFulfilled: Unit,
-      onRejected: js.UndefOr[js.Function1[scala.Any, B | Thenable[B]]]): Thenable[B] = js.na
+  def `then`[B >: A](onFulfilled: Unit,
+      onRejected: js.UndefOr[
+          js.Function1[scala.Any, B | Thenable[B]]]): Thenable[B] = js.native
 
   def `catch`[B >: A](
-      onRejected: js.UndefOr[js.Function1[scala.Any, B | Thenable[B]]] = js.undefined): Prom
+      onRejected: js.UndefOr[js.Function1[scala.Any, B | Thenable[B]]] =
+        js.undefined): Promise[B] = js.native
 }
```

**Comment by olafurpg** [comment]
I found a newline in a result type [in Scala.js sources](https://github.com/scala-js/scala-js/blob/3c4f5bdcc8dfade9243bb74e8e41a67af46be5cf/library/src/main/scala/scala/scalajs/runtime/EnvironmentInfo.scala#L51) I guess newlines are OK after comments like that ;)

**Comment by sjrd** [comment]
If there is a `//` comment, yes, scalafmt has no choice but to keep the newline.

If I were to write this code today, however, I would keep everything one line (and not have the comment).
