### ISSUE TITLE
Rename unindentTopLevelOperators into unindentNonTopLevelOperators

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#501]
**Version**: 0.4.1

Context: https://gitter.im/olafurpg/scalafmt?at=57fb570ba7c618cd26fac288

``` diff
   private def stub(): Nothing = {
     throw new NotImplementedError(
         "A method of be.doeraene.sjsreflect.Reflect was not implemented. " +
-        "Make sure you have enabled the ScalaJSReflectionPlugin on your " +
-        "project with `enablePlugins(ScalaJSReflectionPlugin)`")
+          "Make sure you have enabled the ScalaJSReflectionPlugin on your " +
+          "project with `enablePlugins(ScalaJSReflectionPlugin)`")
   }
```

**Comment by olafurpg** [comment]
This configuration solved the issue
```scala
indentOperator.exclude = "\\+"
unindentTopLevelOperators = true
```

The conclusion is to rename `unindentTopLevelOperators` into `unindentNonTopLevelOperators` and deprecate the old name.

**Comment by olafurpg** [comment]
Now that metaconfig supports `@ExtraName`, it's trivial to change this setting just like we did for importSelectors, see https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala#L179

**Comment by dwijnand** [comment]
Don't link straight to master: that line number means nothing today.

I think you were referring to https://github.com/olafurpg/scalafmt/blob/170e7d8ba563f3e6a80d10ca0f1c6677a7e95cc1/core/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala#L221

**Comment by dwijnand** [comment]
This should be a hackathon ticket, imo.

**Comment by olafurpg** [comment]
@dwijnand I wish there was a browser extension to automatically expand master links before commenting. I do my best to use permanent urls, but it happens that i forget 😢 

After a few discussions on gitter, I think the conclusion was that the current name is maybe OK. I'm gonna close this, please reopen if you can come with a better name
