### ISSUE TITLE
reformatOnCompileSettings generates Warnings

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#516]
When I enable `reformatOnCompileSettings` I get some warnings:

```
[warn] Binary version (2.11) for dependency org.scala-lang#scala-library;2.11.8
[warn]  in default#backend2-build;0.1-SNAPSHOT differs from Scala binary version in project (2.10).
```

Do you have any idea why? I'm happy to PR this issue but I don't really see where this comes from.

---

Also does anyone knows how to enable that in `global.sbt`? (Only some people want this feature in my team)

**Comment by olafurpg** [comment]
Possibly duplicate of #485 which appears to be caused by an sbt regression in 0.13.12, try sbt.version=0.13.11

**Comment by olafurpg** [comment]
Is this still a problem with sbt 0.13.11?

**Comment by olafurpg** [comment]
Reformat on compile is not supported anymore.
