### ISSUE TITLE
File contents disappear before reappearing again shortly after in Emacs

### ISSUE THREAD

**Issue by rdgreen** [olafurpg/scalafmt#529]
It's very disconcerting, and this is _not_ the correct way to rewrite a file in Unix. At a bare minimum, you should write to a temporary file first, and then rename the file when you've finished.

**Comment by olafurpg** [comment]
Could you give more info on your setup? There is no official Emacs plugin. I guess the best way to integrate scalafmt with Emacs is with --stdin to preserve undo/redo behavior. The -i flag is not really intended for editor integrations.

**Comment by olafurpg** [comment]
File writing happens here: https://github.com/olafurpg/scalafmt/blob/863c435aa5b39a6b6c2ada7e2ea342e61f6cfa06/core/src/main/scala/org/scalafmt/util/FileOps.scala#L67

Any contributions to improve the implementation are welcome.

It needs to work with JDK 6, so no java.nio.

**Comment by rdgreen** [comment]
I use `sbt-scalafmt` and revert-file-mode picks up the file changes automatically.

**Comment by olafurpg** [comment]
The SBT plugin uses the IO package from SBT, https://github.com/olafurpg/scalafmt/blob/master/scalafmtSbt/src/main/scala/org/scalafmt/sbt/HasScalaFmt.scala#L73

The FileOps package is not available to the SBT plugin because SBT plugins must be 2.10 and scalafmt is 2.11 only.

**Comment by olafurpg** [comment]
I invite you contribute a fix if this is still troubling you. Closing until then.
