### ISSUE TITLE
Option to format on save in the Idea Plugin

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#530]
All in the title.
I will make a PR for that but logging this in case anyone is already doing it.

**Comment by Daxten** [comment]
sound great +1

**Comment by olafurpg** [comment]
Closed by #534. Excellent work @joan38! For the impatient, you can try out this new feature by manually installing this plugin zip file: https://github.com/olafurpg/scalafmt/releases/download/v0.4.7/intellij-4.7-autosave.zip

I'm excited to use this myself ^_^
