### ISSUE TITLE
Scalafmt does not format sources in shared when using Scala.js crossproject

### ISSUE THREAD

**Issue by mdedetrich** [olafurpg/scalafmt#533]
**Version**: 0.4.7
**Integration**: SBT 0.13.12
**Configuration**: 
```
style = defaultWithAlign
maxColumn = 120
```

There seems tobe an issue with scala.js crossprojects (i.e. projects based off https://github.com/scala-js/scalajs-cross-compile-example). If you are using a crossproject and have this in your standard `build.sbt`

```scala
scalafmtConfig in ThisBuild := Some(file(".scalafmt.conf"))
```

Then scalafmt won't actually format any sources in your `shared` folder. It will only format the files in the `jvm`/`js` folders

**Comment by olafurpg** [comment]
Hmmm. This is annoying. I've kind of given up on figuring out how to use SBT settings to decide which files to format. It seems the SBT build landscape is too heterogeneous to make it work consistently well.

My strategy for 0.5 is to extract the project model from VCS and let users define which extra files to exclude/include in `.scalafmt.conf`. There's already git support in the 0.4.7 CLI and we are using that in scalameta/paradise, see [here](https://github.com/scalameta/paradise/blob/master/.drone.yml#L7). So far, it works great, but I would love to replace the bash script with something cleaner.

**Comment by sjrd** [comment]
That sounds strange. scalafmt correctly grabs the list of source directories to process from `unmanagedSourceDirectories in Compile` ([here](https://github.com/olafurpg/scalafmt/blob/master/scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalaFmtPlugin.scala#L100)), and `CrossProject` precisely adds the shared sources in `unmanagedSourceDirectories in Compile` ([here](https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/cross/CrossProject.scala#L316)).

What does the following display in your build:

    > show projectJVM/compile:unmanagedSourceDirectories

and

    > show projectJVM/compile:hasScalafmt::sourceDirectories

?

**Comment by mdedetrich** [comment]
I am actually thinking right now that it may have been an issue with sbt not correctly picking up a change `.scalafmt.conf` and hence not formatting the shared directory (it was a project which only has sources in `shared` and nowhere else) so it may be a false alarm, let me confirm this

**Comment by mdedetrich** [comment]
Okay, false alarm, I did a `clean` in sbt and its now working. It appears that sbt didn't initially pick up a change `.scalafmt`
