### ISSUE TITLE
Spray indentOperator clash with Scalatest

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#538]
It sounds like there is bug with `indentOperator = spray` and Scalatest.

**Version**: 0.4.7
**Configuration**: indentOperator = spray

``` scala
userReceivedPosts.postIds should contain theSameElementsAs
  Seq(postIds(0), postIds(1), postIds(2), postIds(3), postIds(4), postIds(5))
```

Scalafmt:

``` scala
userReceivedPosts.postIds should contain theSameElementsAs
Seq(postIds(0), postIds(1), postIds(2), postIds(3), postIds(4), postIds(5))
```

I would like to keep the spaces

**Comment by olafurpg** [comment]
Could you fiddle with these two to find the correct regexp?

```
indentOperator.include = regexp
indentOperator.exclude = regexp
```
I don't use `indentOperator = spray` so I don't know what's the expected behavior. I personally like the extra indentation for most infix operators.

**Comment by olafurpg** [comment]
Whoops, I forgot to include a link to the spray (or akka as I call them in the sources, for some reason) settings:
https://github.com/olafurpg/scalafmt/blob/7ea32fd4141bfcd17acc9bb3cffaa48fc5af8e03/core/src/main/scala/org/scalafmt/config/Settings.scala#L13-L14

**Comment by olafurpg** [comment]
Did you find a good setting for this? We might want to include it in the default spray settings.

**Comment by olafurpg** [comment]
Please reopen if this is still an issue.
