### ISSUE TITLE
Align %, %% and %%% in default style?

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#547]
I find myself enabling this setting more and more in my own projects. I personally find `defaultWithAlign` aligns too much, but aligned module IDs is really nice and only affect a small part of my codebase (mostly in .sbt files)

**Comment by dwijnand** [comment]
:allthethings:

**Comment by RomanIakovlev** [comment]
Here's the situation where vertical alignment produces somewhat dubious result with the `%`'s:
```
val circeVersion = "0.5.3"
libraryDependencies ++= Seq(
  "io.circe" %% "circe-core",
  "io.circe" %% "circe-generic",
  "io.circe" %% "circe-parser",
  "io.circe" %% "circe-streaming",
  "io.circe" %% "circe-literal"
).map(_      % circeVersion)
```
Have a look at the `map` method. It's Scalafmt 0.4.6, formatting a `build.sbt` file. Maybe it's a bit early to make this default?

**Comment by mtomko** [comment]
Our codebase basically doesn't use alignment anywhere except for on `%`, `%%`, and `%%%` in .sbt files, so we would fit your model.

Would you limit the effect to SBT files, or would code like:

```scala
val x = y % 10
val quux = y % 9
```
also by default get turned into
```scala
val x =    y % 10
val quux = y % 9
```

I'd suggest if you made this change having a little bit of documentation with a 1-liner to opt out of this alignment (It seems like the configuration is already expressive enough to do this, but I haven't tried it...).

**Comment by mtomko** [comment]
Regarding @RomanIakovlev's example, we tend to align `%` with the last `%` in `%%`s.

So we'd format:


```scala
"io.circe"  % "circe-core"
"io.circe" %% "circe-something-else"
```

**Comment by olafurpg** [comment]
Thanks for the input everybody. After some thinking, I agree with @Romanlakovlev that the current vertical alignment needs more improvements to merit inclusion in the default style. I also think @mtomko has a good point about limiting this setting to sbt files, to reduce the risk of false positives.

**Comment by dwijnand** [comment]
> `defaultWithAlign` aligns too much, but aligned module IDs is really nice

FWIW I've seen people on both side of this argument.

I've seen die-hard vertical alignment haters concede on vertically aligning sbt's ModuleID, but I've also seen even more die-hard haters reject it even then!

I think it should align by default, with an opt-out.

**Comment by olafurpg** [comment]
Following @RomanIakovlev's observation. I believe the vertical alignment implementation needs more work to merit inclusion in the default style. Closing for now.
