### ISSUE TITLE
Intellij plugin complains about new includeCurlyBraceInSelectChains

### ISSUE THREAD

**Issue by lunaryorn** [olafurpg/scalafmt#563]
Version 0.4.8 of the intellij plugin complains about the new option in 0.4.8:

```
Scalafmt: Failed to read .scalafmt.conf. Invalid fields: includeCurlyBraceInSelectChains
```

The same version on command line formats just fine, without any error.

**Comment by olafurpg** [comment]
Hmmm, seems the intellij plugin was using an older version of scalafmt. I really need to get #399 done, it's causing tons of problems not having the intellij plugin as part of the main sbt build.
 I've updated the plugin now (v0.4.8.1, see https://plugins.jetbrains.com/update/index?pr=idea&updateId=29863), can you check if it's working now?

**Comment by lunaryorn** [comment]
@olafurpg Thanks, works now 👍
