### ISSUE TITLE
CLI and sbt plugin yield different results

### ISSUE THREAD

**Issue by stefanobaghino** [olafurpg/scalafmt#566]
**Version**: 0.4.4, 0.4.8
**Integration**: sbt, cli
**Configuration**:

```
style = defaultWithAlign
maxColumn = 100
docstrings = JavaDoc
indentOperator = spray
unindentTopLevelOperators = true
spaces.inImportCurlyBraces = true
align.openParenCallSite = false
newlines.alwaysBeforeCurlyBraceLambdaParams = true
```

**SBT**:

```
import org.scalafmt.sbt.ScalaFmtPlugin.autoImport._
import sbt.Keys._
import sbt._

object Formatting extends Build {

  // Define where to pick the settings from and run a formatting check when compile for tests
  lazy val formatSettings: Seq[Def.Setting[_]] = List(
    // Define where to pick the configuration file
    scalafmtConfig in ThisBuild := Some(file(".scalafmt.conf")),
    // Prevent generated source files (e.g. BuildInfo) format to be checked
    excludeFilter in hasScalafmt := "target*"
  )

}
```

**Source code**:
The project is not open source, therefore I'm currently not able to disclose the offending sources. If the issue is not due to some inherent difference in how the CLI and the sbt plugin use `scalafmt` I can try to distill small samples of code on which the issue seems to arise.

**CLI and sbt**:
The issue arose as I use the CLI to check code formatting before pushing while our Jenkins instance uses the sbt plugin to perform the same check.

**Steps to reproduce**:
1. `sbt scalafmtTest` => `MisformattedFile`
2. `sbt scalafmt`
3. `sbt scalafmtTest` => `MisformattedFile`
4. `scalafmt --version 0.4.8 --config .scalafmt.conf --test -f . --exclude target` => `MisformattedFile`
5. `scalafmt --version 0.4.8 --config .scalafmt.conf -i -f . --exclude target`
6. `sbt scalafmtTest` => OK
7. `sbt scalafmt`
8. `sbt scalafmtTest` => OK again

**Comment by olafurpg** [comment]
Did you `sbt clean` before `sbt scalafmt`?

It would help a lot to have a minimal code example, could you please find a small code snippet from the diff and obscure the variable names?

**Comment by olafurpg** [comment]
Did `sbt clean` work?

**Comment by stefanobaghino** [comment]
Sorry, I had to move on to other issues and couldn't move further with this.
I'm fairly sure the main issue is with spaces between braces in imports and made [a small project to test it](https://github.com/stefanobaghino/scalafmt-566-test) but with no luck so far. :sob:

**Comment by stefanobaghino** [comment]
Minor update: the `sbt` plugin seems to _completely_ skip certain files (but only when actually re-writing the file, not when testing).

I made a test modifying some settings that could have caused the issue (switched from `defaultWithAlign` to `default` and removed spaces in braces on imports).

After doing so and running `sbt scalafmt scalafmtTest` at least one file wasn't formatted according to the test. After running `scalafmt --version 0.4.8 --config .scalafmt.conf -i -f . --exclude target` all the files were formatted.

One final note (it may be interesting for this bug or not): I'm running on an encrypted file system (and do are my colleagues). As so, to prevent issues with longer names, we added a couple of extra configurations to our global SBT build:

    scalacOptions ++= Seq("-Xmax-classfile-name","78")
    target <<= (name) { (name) => file("/tmp/sbt/") / name }

**Comment by stefanobaghino** [comment]
I've finally been able to reproduce a "dirty" situation and test the simple `sbt clean` you suggested and it worked. Why is that so? Caching?

**Comment by olafurpg** [comment]
I'm sorry to hear this caused so much problems. I think for 0.5. we should get rid of the `sbt clean` requirement, as I know you're not the only one who's been confused by this.

The reason it works like it does right now is because that's what the scalariform plugin does. Caching on compliation makes it possible to do `reformatOnCompileSettings`.

**Comment by stefanobaghino** [comment]
Ha, and we even stood away from `reformatOnCompileSettings` to not make it to heavy on us. :smile: Thanks for helping us out! :+1:
