### ISSUE TITLE
Feature Request: test:clean

### ISSUE THREAD

**Issue by ctataryn** [olafurpg/scalafmt#576]
I've been in situations where I've upgraded a library and have received several deprecation warnings. My typical workflow is to fix t `src/main/scala` stuff first, and then tackle `src/test/scala`. 

I refactor the main code by running `~;clean;compile` and fixing each error/deprecation warning displayed on the console. Similarly I'd like to tackle the test code by running `~;test:clean;test:compile`. However, it appears that `test:clean` is just an alias for `clean` because when I run `test:compile` I see it re-compiling all the `src/main/scala` classes as well, where I only wanted the `src/test/scala` classes to be recompiled so as to show all the deprecations/errors remaining in the test classes.

Is it possible to add a true `test:clean` task to sbt?

**Comment by olafurpg** [comment]
Hey, how is this related to scalafmt?

**Comment by ctataryn** [comment]
Oh my, I'm sorry! I think I followed the wrong link, meant this for `sbt`! My appologies.

**Comment by olafurpg** [comment]
No problem :) I agree that `test:clean` should not run `compile:clean`!
