### ISSUE TITLE
Jenkins failures

### ISSUE THREAD

**Issue by andreaTP** [olafurpg/scalafmt#583]
**Version**: 0.4.8
**Integration**: sbt

On our Jenkins CLI we are facing a problem that crash sbt the relevant log is:
```
java.io.FileNotFoundException: /opt/workspace/sbt-cache/ivy2-cache/scala_2.10/sbt_0.13/com.typesafe.sbt (Is a directory)
org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:82)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$writeFormattedContentsToFiles$1$$anonfun$apply$3.apply(HasScalaFmt.scala:54)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$writeFormattedContentsToFiles$1$$anonfun$apply$3.apply(HasScalaFmt.scala:54)
```

Maybe functions that interact with files should be in ```Try``` blocks?
Or any other ideas?

b.t.w.
cannot reproduce on my pc

**Comment by andreaTP** [comment]
adding to the project:
```
excludeFilter in hasScalafmt := "*com.typesafe.sbt"
```

solve the problem.
Probably adding a check if the file is a directory will solve the problem.

**Comment by olafurpg** [comment]
Hmm. It's hard to fix without a repro. I don't like the thought of blindly adding Try's but I'm OK to merge it if someone sends a pr.

No one has yet offered to help maintain the sbt plugin. I would be happy to give merge rights if someone steps up. 

Have you tried the cli with coursier (see docs, sry on the phone)? I personally recommend that over the sbt plugin.

**Comment by andreaTP** [comment]
coursier unfortunately doesn't work with some of our other projects.
I'll try to submit a quick and safe fix, but I have no time to really maintain the plugin itself, sorry for that. :-(

**Comment by olafurpg** [comment]
Coursier bootstrap scripts work a lot more reliably than the coursier sbt plugin, in my experience. 

No worries about the maintenance. I'm just trying to get the word out :)

**Comment by andreaTP** [comment]
I can confirm that the fix works :-)
Thanks!
