### ISSUE TITLE
Intellij plugin doesn't support attached projects

### ISSUE THREAD

**Issue by s-nel** [olafurpg/scalafmt#591]
**Version**: 0.4.10
**Integration**: intellij
**Configuration**: 

```
style = defaultWithAlign # For pretty alignment.
maxColumn = 110
```

In Intellij I manage several SBT projects in one window using the "attach SBT project" feature. For projects attached in this way the scalafmt Intellij plugin doesn't pick up the right config and uses the default settings instead.

Steps:
1. Create SBT project _A_
2. Create another SBT project _B_. Add .scalafmt.conf file to _B_
3. Open _A_ in Intellij
4. Attach _B_ ![screen shot 2016-11-16 at 9 08 25 am](https://cloud.githubusercontent.com/assets/504326/20324243/aa2a4914-abe4-11e6-98c8-e61056ab4007.png)
5. Open source file from _B_
6. Use scalafmt hotkey
7. Notice it formats using default settings, not the ones in .scalafmt.conf

**Comment by olafurpg** [comment]
Thanks for reporting! I have never used attached projects. The logic to pick up the configuration ishere: https://github.com/olafurpg/scalafmt/blob/7de502e59a096d91143bbff9cab8b71e7faabd83/intellij/src/org/scalafmt/intellij/IdeaUtils.scala#L45

Would you be interested in taking a swing at this? I suspect the fix probably involves finding the correct method in the IDEA API to find the attached project, I suspect you can then use the same `getBasePath` method as the plugin already does.

**Comment by s-nel** [comment]
I did some debugging and found that for attached "projects" they're just treated like any other Intellij module. The only open project returned by `ProjectManager` is the root project. Which makes this method in `IdeaUtils.scala` return `None`

```
def projectForFile(file: String) = {
    val projects = ProjectManager.getInstance().getOpenProjects
    projects.find(bp => file.startsWith(bp.getBasePath))
  }
```

I think a reasonable solution would be to recurse over parent directories of the file to format until a directory with a .scalafmt.conf file is found. What do you think?

**Comment by olafurpg** [comment]
The IntelliJ plugin tries to read `$HOME/.scalafmt.conf`, would that work for your use-case?

I'm surprised the IDEA apis don't have a method to find the attached project owner of a given file. I would love to avoid reading all parent directories of a file on every single format. But if it is in fact the only solution, I guess we can go with it. In that case, I think we should only read up until the home directory (not root `/`).

**Comment by s-nel** [comment]
Yeah that'll work for my use case. Since I can't find a more elegant solution in the Intellij API, we can either close this issue or leave open for somebody else to investigate the Intellij API. Imo it's not a serious enough issue to use a less-desirable search algorithm.

**Comment by olafurpg** [comment]
Okay, good to hear. I think it's best to close this issue then and anyone is free to reopen if they want to take a swing at this.
