### ISSUE TITLE
Indent `yield` at same level as `for` 

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#592]
Scalafmt:
```scala
object Bar {
  for (x <- Nil)
    yield 2
}
```

I would like the input to look like this:
```scala
object Bar {
  for (x <- Nil)
  yield 2
}
```

From gitter: https://gitter.im/olafurpg/scalafmt?at=582ec607e51081951edf151b

> for symmetry with if/else or try/catchs which seem to format like the former rather than the latter

**Comment by olafurpg** [comment]
I'm struggling with this example

```scala
val sizes = for (row <- table)
yield
  (for (cell <- row)
  yield
    if (cell == null) 0
    else cell.toString.length)
```
How would you format that @lihaoyi?

**Comment by olafurpg** [comment]
Here's how it would format if I replace for/yield with if/else

```scala
[info]   val sizes =
[info]     if (row > table) a
[info]     else
[info]       (if (cell > row) b
[info]        else if (cell == null) 0
[info]        else cell.toString.length)
```
It could be the same for for/yield.

**Comment by olafurpg** [comment]
Okay, so if the for/yield works exactly like if/else the output would be

```scala
[info]   val sizes =
[info]     for (row <- table)
[info]     yield
[info]       (for (cell <- row)
[info]        yield
[info]          if (cell == null) 0
[info]          else cell.toString.length)
```

I think this makes a lot of sense, I might want to make it the default behavior in 0.5.

**Comment by lihaoyi** [comment]
Yeah that looks good. Typically I wouldn't have a `(` before the `for`, but instead surround the whole block with curlies:

```scala
[info]   val sizes =
[info]     for (row <- table)
[info]     yield {
[info]       for (cell <- row)
[info]        yield
[info]          if (cell == null) 0
[info]          else cell.toString.length
[info]      }   
```

But I assume scalafmt probably already does the right thing in such a scenario

**Comment by lihaoyi** [comment]
Note that this is in addition to the "normal" way of doing `for`s:

```scala
[info]   val sizes =
[info]     for (row <- table) yield {
[info]       for (cell <- row)
[info]       yield
[info]         if (cell == null) 0
[info]         else cell.toString.length
[info]     }  
```

which hopefully should still work

**Comment by olafurpg** [comment]
Hmmm. The "normal" way is not possible with the fix in #594. Instead, it follows the behavior of if/else

```scala
val sizes =
  for (row <- table)
  yield {
    for (cell <- row)
    yield
      if (cell == null) 0
      else cell.toString.length
  }

// yield stays on same line only when the body fits on single line
for (x <- Nil) yield { 1 }
```

However, I could update #594 to make if/else and for/yield also behave the same like this

```
if (cond) a else {
  // ...
}
for (a <- b) yield {
  // ....
}
```

I think it's reasonable to treat those patterns the same.

**Comment by sjrd** [comment]
I don't understand the rationale about symmetry with if/else and try/catch. In an if/else, else is on the same level of execution as if. Same for try/catch. In for/yield, yield is logically *inside* each iteration of `for`. Not after it or as an alternative to it, but inside. This is fundamentally different, IMO.

**Comment by olafurpg** [comment]
Okay, the behavior is now unchanged in this case

```scala
for (a <- b) yield {
  // ...
}
```
The full spec is here: https://github.com/olafurpg/scalafmt/pull/594/files#diff-a2424dd000145b09a8929364d3909db6

I'll merge the PR and we can iterate on this again after next release if there are still some quirks.

@sjrd It find indenting `for`/`yield` at the same level quite nice actually. However, I never really use for comprehensions with parentheses syntax, so this won't really affect me much.

**Comment by unkarjedy** [comment]
Probably this should be revised in the context of Scala 3 new control syntax:
https://github.com/scalameta/scalafmt/issues/2216#issuecomment-790509646
