### ISSUE TITLE
Don't exclude newlines inside blocks for single-args in IntelliJ style

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#593]
From gitter: https://gitter.im/olafurpg/scalafmt?at=582ec9c6e51081951edf28dc

```scala
lihaoyi fluent$ cat .scalafmt.conf
style = IntelliJ
maxColumn = 100
#align.openParenDefnSite = true
lihaoyi fluent$ cat foo.scala
object Bar {
  println(
    for (x <- Nil) yield {
      2
    }
  )
}
lihaoyi fluent$ scalafmt -c .scalafmt.conf  -f foo.scala
object Bar {
  println(for (x <- Nil) yield {
    2
  })
}
```

**Comment by lihaoyi** [comment]
It seems to wrap oddly even if there are multiple args passed to the println:
```scala
lihaoyi fluent$ cat foo.scala
object Bar {
  println(
    for (x <- Nil) yield {
      2
    },
    234
  )
}
lihaoyi fluent$ scalafmt -c .scalafmt.conf  -f foo.scala
object Bar {
  println(for (x <- Nil) yield {
    2
  }, 234)
}
```

Ideally I'd want it to remain with each argument on its own line

**Comment by lihaoyi** [comment]
A repro without the `for`:

```scala
lihaoyi fluent$ cat foo.scala
object Bar {
  println(
    println{
      2
    },
    234
  )
}
lihaoyi fluent$ scalafmt -c .scalafmt.conf  -f foo.scala
object Bar {
  println(println {
    2
  }, 234)
}
```

**Comment by olafurpg** [comment]
I think I know what's happening, scalafmt treats those examples as "single-line" argument lists because the newlines inside the curly braces are not included.

**Comment by olafurpg** [comment]
Okay, so I don't think we should make this the default behavior in IntelliJ style since this behavior was specifically requested for patterns like this

```scala
Props(new Actor {
  context.stop(self)
  def receive = Actor.emptyBehavior
})
```

#595 adds a new flag `newlines.neverInDanglingParenthesesSingleLineArgList`, which you could set to `true` to get your desired output. I admit the name is a bit unwieldy, but I struggled to come up with something clearer. WDYT?

**Comment by lihaoyi** [comment]
A separate flag looks great to me. 

----

An alternative could be to fall back to ignoring newlines as long as there's only a single argument, and not-ignoring them as long as there are multiple arguments. For example,

```scala
foo(bar(
  lols
))
```

Is something that people may want, but 

```scala
foo(bar(
  lols
), qux)
```

or

```scala
foo(qux, bar(
  lols
))
```

are both probably things people don't want often. Furthermore, this doesn't seem related at all to whether the thing inside has curlies or parens. In both cases, as long as there's one argument, I've wanted the arg-starts-on-same-line formatting.

----

A *third* alternative, could be to accept both cases: if a user put the args on a *separate* line, leave them there. If the user put the arg on the *next* line, leave that there too. Not sure how easy this is but as I understand it scalafmt is happy with being sloppy in certain cases

**Comment by olafurpg** [comment]
The third alternative is pretty much how the default style works. If you have a newline before the closing parens and after the opening parens, then scalafmt will keep "config style".

**Comment by lihaoyi** [comment]
@olafurpg do you mean it's how the default style works before or after your fixes? Because if that's really how it works I don't think I actually need another flag; it's just that my experiments showed it always forcing the arg-on-same-line case even when it wasn't wanted

**Comment by olafurpg** [comment]
Before the fix, but it would require a minor adjustment to `optIn.configStyleArguments`. If we can avoid a new flag then I think that would be perfect. Instead of `newlines.neverInDanglingParenthesesSingleLineArgList = true` you could enable `optIn.configStyleArguments = true` (which is false in intellij style but true in default style). The difference between the two is only for cases when the argument list is formatted in "config style" but it could fit on a single line.

```scala
/* newlines.neverInDanglingParenthesesSingleLineArgList = true */
// before
foo(
  1
)
// after
foo(1)

/*optIn.configStyleArguments = true */
// before
foo(
  1
)
// after
foo(
  1
)
// before (missing newline after open paren)
foo(  1
)
// after
foo(1)
// before (missing newline after closing paren)
foo(
  1)
// after
foo(1)
```
With `optIn.configStyleArguments = true`, you have more control over the line breaks.

If this sounds OK, then I'll go ahead and remove `newlines.neverInDanglingParenthesesSingleLineArgList` and make the necessary adjustments to 
`optIn.configStyleArguments`.

**Comment by lihaoyi** [comment]
Looks good to me. Here are a few more cases I think are worth noting:

```scala
/*optIn.configStyleArguments = true */
```
```scala
// single-line remains single-line

// before
foo(1)
// after
foo(1)

```
```scala
// except if it's too long, then it should be "force" wrapped

// before
foo("12345678901234567890123456789012345678901234567890123456789012345678901234567890")
// after
foo(
  "12345678901234567890123456789012345678901234567890123456789012345678901234567890"
)
```

The second case being basically what's described in https://github.com/olafurpg/scalafmt/issues/599

**Comment by olafurpg** [comment]
This turned out to be super easy to accommodate. The settings

```
style = IntelliJ
optIn.configStyleArguments = true
```

should match what we have discussed. In a nutshell, if you put a newline after `(` and newline before `)` then scalafmt will keep it like that, regardless of whether the line can fit in a single line or not.

```scala
// scalafmt keeps line breaks this even if it can fit `foo(1)` on a single line
foo(
  1
)
```
