### ISSUE TITLE
A very long pattern matching should break into multiple lines

### ISSUE THREAD

**Issue by Atry** [olafurpg/scalafmt#601]
**Version**: (for example, 0.4.10)
**Integration**: intellij
**Configuration**: `--maxColumn 80`

```scala
val Some(element0 +: element1 +: element2 +: element3 +: element4 +: element5 +: element6 +: element7 +: element8 +: element9 +: element10 +: rest) = Some(0 until 100)
```

Scalafmt:
```scala
val Some(element0 +: element1 +: element2 +: element3 +: element4 +: element5 +: element6 +: element7 +: element8 +: element9 +: element10 +: rest) = Some(0 until 100)
```

I would like the input to look like this:
```scala
val Some(element0 +: element1 +: element2 +: element3 +: element4 +: element5 +: element6 +: element7 +:
         element8 +: element9 +: element10 +: rest) = Some(0 until 100)
```

**Comment by olafurpg** [comment]
This is working as intended, scalafmt doesn't line wrap infix operators. If you insert a newline before `element8` then scalafmt will keep that line break.

Before v0.3 scalafmt tried to be smart about wrapping infix operators but it kept messing up with fancy DSLs. Infix operators are kinda tricky for formatting.

**Comment by Atry** [comment]
Fair enough
