### ISSUE TITLE
brew command line usage case 2

### ISSUE THREAD

**Issue by BusyByte** [olafurpg/scalafmt#603]
per the documentation I thought I was in use case 2:
`# 2. .scalafmt.conf file in current directory`

scalafmt 0.4.10
brew install integration in bash

Config file
```
style = defaultWithAlign
maxColumn = 120
```

Scalafmt:
Actual
- It printed the formatting to the the console but did not format the files
- Files were left unchanged
Expected
- Formatted the files
- Files are modified with formatting

Adding `project.git = true` to the file as follows:
```
style = defaultWithAlign
maxColumn = 120
project.git = true
```
Then the files were formatted as expected.
`100.0% [##########] 67 source files formatted`

Expected fix:
Need a test case for case 2 or need to clarify the documentation on usage

**Comment by olafurpg** [comment]
Thank you for reporting! I am so sorry for the slow response. I am unable to reproduce with 0.5.8, I believe this got fixed sometime in the 0.5.x series.
