### ISSUE TITLE
SearchStateExploded error

### ISSUE THREAD

**Issue by cb372** [olafurpg/scalafmt#605]
**Version**: 0.4.10
**Integration**: coursier, via my [poor man's sbt plugin](https://github.com/ovotech/mailgun-api-client/blob/72417be93cb4ef82ddf9f37262ddd892f22d899d/build.sbt#L21-L26)
**Configuration**: `maxColumn = 120; project.git = true`

```
[warn] Error in /Users/chris.birchall/code/mailgun-api-client/src/test/scala/com/ovoenergy/mailgun/model/events/EventsResponseSpec.scala: org.scalafmt.Error$SearchStateExploded: Search state exploded around line 59
```

The input is [this ridiculously verbose test I just wrote](https://github.com/ovotech/mailgun-api-client/blob/72417be93cb4ef82ddf9f37262ddd892f22d899d/src/test/scala/com/ovoenergy/mailgun/model/events/EventsResponseSpec.scala).

**Comment by olafurpg** [comment]
This is a known issue, see #140 for an explanation. #582 is related. For config style arguments (like in your test) I don't think this should be too hard to fix. Turns out this is a blocker for #588, so I might take a look at it soon.

ps. 120 max column is a lot, you must have a wide display :p

**Comment by olafurpg** [comment]
Good news @cb372, see https://github.com/olafurpg/scalafmt/pull/621

Your ridiculously verbose test has now become a scalafmt unit test :D The change is limited to Term.Apply with a large number of arguments and large bodies. In those cases, scalafmt will force "config style" and dequeue the search space at the start of every argument. The optimization is controlled by two magic numbers, which are configurable inside `runner.optimizer`. I have no idea if the defaults are any good.

I'll include this for v0.5!

**Comment by olafurpg** [comment]
Closing this since your particular example now formats easily.

**Comment by cb372** [comment]
Yay! Thanks for the fix! I love your flamegraph-style test output by the way.
