### ISSUE TITLE
Add the parameter to keep annotations in the original lines

### ISSUE THREAD

**Issue by mpociecha** [olafurpg/scalafmt#607]
It would be helpful to have a parameter which simply allows to keep annotations in the original lines (relatively - obviously the number of the line could change). Only the indentation etc. would be fixed, if needed.

**Version**: 0.4.10
**Configuration**: the default one, but setting various params rather doesn't change anything

**Input == expected:**
```scala
  @annot @deprecated class B extends A {
    @annot override def foo = 1
  
    @annot
    override def bar = 1
  
    @annot @deprecated def foo2 = 1
  
    @annot
    @deprecated
    def bar2 = 1
  }
  
  @annot
  @deprecated class C
  
  @annot
  @deprecated
  class D
```

**Scalafmt:**
```scala
  @annot
  @deprecated
  class B extends A {
    @annot override def foo = 1
  
    @annot
    override def bar = 1
  
    @annot
    @deprecated def foo2 = 1
  
    @annot
    @deprecated
    def bar2 = 1
  }
  
  @annot
  @deprecated class C
  
  @annot
  @deprecated
  class D
```

**Comment by olafurpg** [comment]
I think this should be relatively simple to fix. I suggest we name the flag `optIn.newlineBeforeAnnotation: Boolean`, which can be added to the case class `OptIn`.

To track down where the newline/spaces are created you can follow the tutorial here: https://github.com/olafurpg/scalafmt#tutorial-add-spacesinparentheses-flag
The tutorial may be slightly outdated (which reminds me I should update it), but most importantly - - you don't need to create a directory in `core/src/test/resources`
-  just add a file in [here](https://github.com/olafurpg/scalafmt/tree/master/core/src/test/resources/optIn) and
- enable the configuration like [here](https://github.com/olafurpg/scalafmt/blob/master/core/src/test/resources/optIn/SelectChain.stat#L1)

Once you've tracked down the `Split` before the `@` symbol I think you can check `newlines: Int` which tells you how many newlines were between the `@` and its leading token in the original source file.

Don't hesitate to ask if you get stuck!

**Comment by olafurpg** [comment]
btw, i'm open for suggestions on another option name, anything that makes it easier to understand what it does.
