### ISSUE TITLE
Weird vertical alignment for match-case after lambda

### ISSUE THREAD

**Issue by stefanobaghino** [olafurpg/scalafmt#608]
**Version**: 0.4.4
**Configuration**:
```
style = defaultWithAlign
maxColumn = 100
docstrings = JavaDoc
indentOperator = spray
unindentTopLevelOperators = true
spaces.inImportCurlyBraces = true
align.openParenCallSite = false
newlines.alwaysBeforeCurlyBraceLambdaParams = true
```

Scalafmt:
```scala
iterator.find { case (a, _) => doSomethingWith(a) } match {
  case None                 => ???
  case Some((a, b)) if predicateOn(a, b) => ???
```

I would like the input to look like this:
```scala
iterator.find { case (k, _) => doSomethingWith(a) } match {
  case None                              => ???
  case Some((a, b)) if predicateOn(a, b) => ???
```

**Comment by olafurpg** [comment]
Have you tried 0.4.10? I think this has been fixed.

**Comment by stefanobaghino** [comment]
I'll try, I haven't find it in both open and closed issues and thought this wasn't known. Thanks!

**Comment by stefanobaghino** [comment]
I rerun from the CLI like this
```bash
scalafmt --version 0.4.10 --config .scalafmt.conf -i -f . --exclude target
```
and it reformatted half of the code base. :joy: 
This is how it reformatted the snippet above
```scala
iterator.find { case (a, _) => doSomethingWith(a) } match {
  case None => ???
  case Some((a, b)) if predicateOn(a, b) =>
    ???
```
I suspect the operators cannot be aligned because there a further cases below that span more than 100 characters over a single line.

Sorry for the spurious issue and thanks for the help.

**Comment by olafurpg** [comment]
These can definitely align:

```
  case None => ???
  case Some((a, b)) if predicateOn(a, b) =>    ???
```
as long as `???` are both on the same line as their respective `=>`

> and it reformatted half of the code base. 😂

In a good or bad way? If it's bad I'd love to know the regression.

**Comment by olafurpg** [comment]
I made the vertical alignment a lot stricter to eliminate false positives like in this issue. The rules may be unnecessarily strict now.
