### ISSUE TITLE
Cross build against 2.12

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#616]
Blocking:

- [x] next scala.meta release to get https://github.com/scalameta/scalameta/pull/563
- [x] move metaconfig into separate repo https://github.com/olafurpg/metaconfig
- [ ] update crossScalaVersions
- [ ] use sbt-doge to handle test commands

**Comment by raboof** [comment]
Hmm, it looks like scalameta 1.5.0 was tagged and announced, but hasn't hit maven central yet due to some sonatype syncing issues. Should be there soon(tm)!

**Comment by MasseGuillaume** [comment]
@olafurpg 

Scalameta 2.12 is available (1.4.0).
http://search.maven.org/#artifactdetails%7Corg.scalameta%7Cscalameta_2.12%7C1.4.0%7Cjar
https://index.scala-lang.org/scalameta/scalameta/scalameta?target=_2.12

It would be cool to have a 2.12 scalafmt artifact so I could release Scastie's server with 2.12.1

**Comment by raboof** [comment]
1.4.0 does not have the PR mentioned above (scalameta/scalameta#563) yet though... 1.5.0 has not arrived at sonatype, but I hear 1.6.0 is expected soon ;)

**Comment by MasseGuillaume** [comment]
Ahh ops.
