### ISSUE TITLE
The new sbt plugin is not compatible with the ++ command of sbt

### ISSUE THREAD

**Issue by sjrd** [olafurpg/scalafmt#641]
**Version**: 0.5.1
**Integration**: sbt

Reproduction:
* Take any project with scalafmt enabled in sbt
* do `$ sbt ++2.12.1 scalafmt` (or any other non-2.11 version)
* Observe the crash:

```
[info] Setting version to 2.12.1
[info] Reapplying settings...
[info] Set current project to Scala.js DOM (in build file:/home/travis/build/sjrd/scala-js-dom/)
[info] Updating {file:/home/travis/build/sjrd/scala-js-dom/}scalafmt-stub...
[info] Resolving org.scala-lang#scala-library;2.12.1 ...
[info] Resolving com.geirsson#scalafmt-cli_2.12;0.5.1 ...
[info] Resolving com.geirsson#scalafmt-cli_2.12;0.5.1 ...
[warn] 	module not found: com.geirsson#scalafmt-cli_2.12;0.5.1
[warn] ==== local: tried
[warn]   /home/travis/.ivy2/local/com.geirsson/scalafmt-cli_2.12/0.5.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/geirsson/scalafmt-cli_2.12/0.5.1/scalafmt-cli_2.12-0.5.1.pom
[info] Resolving org.scala-lang#scala-compiler;2.12.1 ...
[info] Resolving org.scala-lang#scala-reflect;2.12.1 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.12;1.0.6 ...
[info] Resolving jline#jline;2.14.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.geirsson#scalafmt-cli_2.12;0.5.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.geirsson:scalafmt-cli_2.12:0.5.1 ((org.scalafmt.sbt.ScalafmtPlugin) ScalafmtPlugin.scala#L33)
[warn] 		  +- scalafmt-stub:scalafmt-stub_2.12:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.geirsson#scalafmt-cli_2.12;0.5.1: not found
...
[error] (scalafmt-stub/*:update) sbt.ResolveException: unresolved dependency: com.geirsson#scalafmt-cli_2.12;0.5.1: not found
[error] Total time: 1 s, completed Dec 23, 2016 1:48:19 PM
```
Example Travis build: https://travis-ci.org/sjrd/scala-js-dom/jobs/186342345

This happens because ++2.12.1 also affects the `scalaVersion` of the synthetic project that is used to run the scalafmt CLI. I'm not sure how to solve this issue. At least this bug report can serve as a documented limitation.

**Comment by olafurpg** [comment]
This is surprising, but I guess it makes sense. It's a shame. My experience is that `+` and `++` don't work well in multi-project builds with heterogenous scala versions. Writing sbt plugins is hard...

**Comment by sjrd** [comment]
> My experience is that + and ++ don't work well in multi-project builds with heterogenous scala versions.

I'm not sure about that. In Scala.js we exclusively use ++ to deal with our projects, and we have a significantly heterogeneous build. I haven't experienced any issue with that.

**Comment by olafurpg** [comment]
My experience is that it's easy to forget a `++ VERSION` command when I cross-publish locally a 2.11/2.10 library and then run scripted tests in 2.10. sbt-doge solved the problem for me.
