### ISSUE TITLE
Add --debug flag in cli

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#653]
- **Version**: 0.5.1
- **Integration**: cli

It would be nice to have a --debug flag to track down weird behavior. Context: https://gitter.im/olafurpg/scalafmt?at=58624950e7bdfe4e29a191eb

The flag would print out:

- where configuration was read from
- what configuration was read
- current working directory
- which files are formatted

**Comment by clhodapp** [comment]
Sorry, I feel like I kinda tricked you into bringing the plugin back what with all the problems you seem to have had as a result.
(Completely non-deliberately, of course)

**Comment by olafurpg** [comment]
No worries at all :) I learned a lot about sbt while going through all this.
