### ISSUE TITLE
Intellij silently ignores Ctrl-Shift-L on Linux

### ISSUE THREAD

**Issue by rbellamy** [olafurpg/scalafmt#656]
- **Version**: 0.5.1
- **Integration**: IntelliJ
- **Platform**: Arch Linux
- **Configuration**: I liked the values from this project, so I stole them fair-and-square.
```
align.tokens = [
  { code = "%", owner = "Infix" }
  { code = "%%", owner = "Infix" }
]
assumeStandardLibraryStripMargin = true
optIn.breakChainOnFirstMethodDot = true
project.excludeFilters = [
  target
  sbt-test
]
project.git = true
```

## No formatting 
I use the `Ctrl-Shift-L` combination, and nothing happens. I've reviewed the system shortcuts, and Gnome isn't using that at all. The only collision within IntelliJ was for `Find Next` which also had a `Shift-F3` shortcut - so I removed the `Ctrl-Shift-L` shortcut from that action. Still no love.

The `idea.log` file doesn't have any smoking gun either.

On Mac, `Shift-Cmd-L` works as expected.

**Comment by olafurpg** [comment]
Have you tried to assign a custom shortcut for the "reformat with scalafmt"
action?

**Comment by rbellamy** [comment]
I have not - I'll give that a try.

**Comment by rbellamy** [comment]
Okay, so it turns out the Haskell plugin includes that same key combination for reloading the REPL. Removing the Haskell Plugin Shortcut resolved my issue.
