### ISSUE TITLE
New rewrite: expand import selectors

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#657]
Obtained, scalafmt formats code like this:
```scala
import a.{b, c}
```

Expected, I would like the formatted output to look like this:
```scala
import a.b
import a.c
```

**Comment by ysusuk** [comment]
shall this be an option? like expandImportSelectors.

**Comment by olafurpg** [comment]
It'll be a `Rewrite`, like these https://olafurpg.github.io/scalafmt/#rewrite.rules

**Comment by ysusuk** [comment]
i observed that import compiles in .stat file if it looks like:

```scala
import a.{
    b,
    c
  }, h.{
    k, l
  }
```

and doesn't compile if it looks like:

```scala
import a.{b, c}, h. {k, l}
```

what is the trick here?

**Comment by olafurpg** [comment]
What if you make it a '.source' file?

**Comment by ysusuk** [comment]
same behaviour!

**Comment by olafurpg** [comment]
What if you put leading and trailing imports statements in a '.source' file?

**Comment by olafurpg** [comment]
Fixed by @ysusuk, thank you!
