### ISSUE TITLE
space should not be present before super keyword

### ISSUE THREAD

**Issue by Atry** [olafurpg/scalafmt#661]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.1
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 120
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
fxmlTest. super.withFixture(test)
```

Expected, I would like the formatted output to look like this:
```scala
fxmlTest.super.withFixture(test)
```

**Comment by Atry** [comment]
The entire source file can be found at https://github.com/ThoughtWorksInc/Binding.scala/blob/7567ad0/fxml/src/test/scala/com/thoughtworks/binding/fxmlTest.scala#L145

**Comment by olafurpg** [comment]
Thank you for reporting! This is clearly a bug, I'll try to get it fixed for the next release.
