### ISSUE TITLE
Error while formatting sequence unpacking in curly braces.

### ISSUE THREAD

**Issue by tgodzik** [olafurpg/scalafmt#663]
This template is a guideline, not a strict requirement.
- **Version**: 0.4.9
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 40
```

## Unexpected formatting output

Obtained, scalafmt does not format code like this (we get an error):
```scala
function{array.toSeq :_*}
```

Expected, I would like the formatted output to look like this:
```scala
function {
    array.toSeq :_*
}
```

I checked it also by adding a test:
```
maxColumn = 40
<<< ONLY Sequence unpacking in curly braces 
function{array.toSeq :_*}
>>>
function {
    array.toSeq :_*
}
```

and we get an error:
```
[info]   <input>:1: error: ; expected but identifier found
[info]   function{asd.toSeq :_*}
[info]                        ^
```

**Comment by olafurpg** [comment]
Related https://github.com/scalameta/scalameta/issues/312#issuecomment-267081928

This is one of a few remaining parser bugs in scala.meta

**Comment by tgodzik** [comment]
Thanks for the info, that's what I was worried about.

**Comment by olafurpg** [comment]
Closing in favor of scala.meta issue.
