### ISSUE TITLE
Error when formatting class with a comment after opening braces.

### ISSUE THREAD

**Issue by tgodzik** [olafurpg/scalafmt#672]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 10
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
class A extends B with C{ // this is an additional comment
}
```

Expected, I would like the formatted output to look like this:
```scala
class A extends B with C{
  // this is an additional comment
}
```

Output not formatted, got an error:
```
org.scalafmt.Error$FormatterChangedAST: Formatter changed AST
[info] =====================
[info]  (Nil, Name.Anonymous
[info] -(), None, None), Some
[info] -(Nil)))
[info] +(), None, None), None))
[info] =====================
[info] class A
[info]     extends B
[info]     with C 
[info] =====================
[info] Formatter changed AST
[info]   at org.scalafmt.util.FormatAssertions$class.assertFormatPreservesAst(FormatAssertions.scala:31)
[info]   at org.scalafmt.FormatTests.assertFormatPreservesAst(FormatTests.scala:32)
[info]   at org.scalafmt.FormatTests.run(FormatTests.scala:69)
[info]   at org.scalafmt.FormatTests$$anonfun$4.apply(FormatTests.scala:54)
[info]   at org.scalafmt.FormatTests$$anonfun$4.apply(FormatTests.scala:54)
[info]   at org.scalafmt.util.HasTests$$anonfun$runTest$2.apply$mcV$sp(HasTests.scala:156)
[info]   at org.scalafmt.util.HasTests$$anonfun$runTest$2.apply(HasTests.scala:151)
[info]   at org.scalafmt.util.HasTests$$anonfun$runTest$2.apply(HasTests.scala:151)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   ...

```

**Comment by olafurpg** [comment]
Sorry for the slow response! Could you provide more info on this? I am unable to reproduce with this input

```scala
class A extends B with C { // this is an additional comment
}
```

**Comment by tgodzik** [comment]
I created a stat file like this:

```
maxColumn = 10
<<< ONLY Comment after extends with
class A extends B with C{ // this is an additional comment
}
>>>
class A
    extends B
    with C { // this is an additional comment
}
```

It still fails on the newest master. It's seems there is a policy that drops non newlines after a "with", which in turn makes the formatting incomplete.

I think I managed to fix that in the Router.scala, but not sure if it's the right way or whether i get it correctly:

```
Policy(
                  {
                    // Force template to be multiline.
                    case d @ Decision(
                          FormatToken(open @ LeftBrace(), right, _),
                          splits)
                        if !hasSelfAnnotation &&
                          !right.is[RightBrace] && // corner case, body is {}
                          !right.is[Comment] &&
                          childOf(template, owners(open)) =>
                      d.copy(splits = splits.filter(_.modification.isNewline))
                  },
                  expire.end
                )
```

Added "!right.is[Comment] &&"

**Comment by olafurpg** [comment]
I am able to reproduce with maxColumn=10. Good catch, I am not surprised to see a bug caused by a comment, comments are incredibly tricky in code formatting.

In the error output, you can see the active policies are defined in lines 1007, 595 and 364 in Router.scala.
```
policies=Vector(P:1007(D=false), P:595(D=false), P:364(D=false))
```
You tracked down the correct culprit policy on line 1007, but the bug seems to be caused by the `expire` token. If you `logger.elem(expire)` you'll see that its

```
[debug] Router.scala:1007         [expire]: }
```

However, changing expire to the opening curly brace `{` did still not fix the problem. The culprit is the overly strict policy
```scala
                      d.copy(splits = splits.filter(_.modification.isNewline))
```
I've come to learn that blindly filtering out policies is not a good idea because of comments. I replaced that line to `d.forceNewline` and now the test passes. `forceNewline` handles the edge-case around comments.

There we go! I've opened a PR to fix this issue.

**Comment by tgodzik** [comment]
Cool, thanks!
