### ISSUE TITLE
sbt scalafmt just prints to stdout if no .scalafmt.conf file is present

### ISSUE THREAD

**Issue by alexkops** [olafurpg/scalafmt#677]
- **Version**: 0.5.1
- **Integration**: sbt
- **Configuration**: No .scalafmt.conf present

I just added sbt-scalafmt 0.5.1 to my plugins.sbt and ran `sbt scalafmt` but it would only print formatted code to the stdout. When I used version 0.4.10 and did the same, it would actually alter the files.
Only after adding an empty .scalafmt.conf it worked.
Not sure if it's intended, if so it should be mentioned in the changelog.

**Comment by olafurpg** [comment]
Thanks for reporting! This is unintentional, will be fixed in 0.5.2 : )

**Comment by manub** [comment]
I'm experiencing exactly the same issue using sbt `0.13.13` and scalafmt `0.5.6`.

`sbt scalafmt` only prints formatted files to the standard output, but adding an empty `.scalafmt.conf` makes it working.

**Comment by sahil-sawhney** [comment]
Hey, this issue is still present in scalafmt version 0.6.6

**Comment by asarkar** [comment]
Happens on `sbt-scalafmt:2.4.3`. Without a `.scalafmt.conf`, the task `scalafmtCheckAll` fails; an empty file makes it work.
