### ISSUE TITLE
Formatting files encoded with UTF8 and containing complex characters (like Chinese) results in errors

### ISSUE THREAD

**Issue by ochrons** [olafurpg/scalafmt#694]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.3
- **Integration**: sbt
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 140
```

Scalafmt breaks UTF8 encoding here,
https://github.com/ochrons/boopickle/blob/master/boopickle/shared/src/test/scala/external/PickleTests.scala#L257-L260

The result is illegal UTF8 and scalac fails to compile:
```
          val bb = Pickle.intoBytes("\uD834\uDF06泡�?�")
          assert(bb.limit == 1 + 3 * 4)
          val s = Unpickle[String].fromBytes(bb)
          assert(s == "\uD834\uDF06泡�?�")
```

scalac error message
```
[error] IO error while decoding D:\work\boopickle\boopickle\shared\src\test\scala\external\PickleTests.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
```

it also warns about,
```
[warn] Error in D:\work\boopickle\boopickle\shared\src\test\scala\boopickle\CodecTests.scala: <input>:61: error: illegal character '\u2013'
val data = Seq[Char](' ', 'A', '├û', 'σ?ë', 'Γé¼')
```
which is https://github.com/ochrons/boopickle/blob/master/boopickle/shared/src/test/scala/boopickle/CodecTests.scala#L61

**Comment by ochrons** [comment]
Furthermore, this only happens running scalafmt via SBT, in IntelliJ plugin it works fine. My system is Win10 so default encoding is probably not UTF8.

**Comment by ochrons** [comment]
Starting SBT with
```
JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 sbt
```
seems to fix the issue.

**Comment by olafurpg** [comment]
Good to know you found a workaround. I'm thinking of adding an 'encoding' configuration option which defaults to utf8 but can be set to the system default (mimicking the current behavior). Wdyt?

**Comment by ochrons** [comment]
Sounds like a sensible solution. I would imagine most people use UTF8 for source code, but who knows...
