### ISSUE TITLE
A `!` gets combined with `===` resulting in compilation error

### ISSUE THREAD

**Issue by ochrons** [olafurpg/scalafmt#697]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.3
- **Integration**: SBT
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 140

```

## Unexpected formatting output

```
  def ===(that: S): Boolean

  def =!=(that: S): Boolean = ! ===(that)
```
gets formatted to
```
  def ===(that: S): Boolean

  def =!=(that: S): Boolean = !===(that)
```
which doesn't compile due to `!===`

**Comment by olafurpg** [comment]
I clearly need to point my test suite against your repos! I run checks to verify that scalafmt does not change the AST. Thanks for reporting, I'll try to get this fixed asap.

**Comment by olafurpg** [comment]
I was able to reproduce and #698 is a fix. I'll try to publish 0.5.4 today.

**Comment by olafurpg** [comment]
0.5.4 is on its way to maven and intellij plugin repository.

**Comment by olafurpg** [comment]
Seems like the fix for this bug was too aggressive, it adds spaces when it's not necessary

```diff
-    assert(!_evaluatorSet, "Evaluator can be set at most once")
+    assert(! _evaluatorSet, "Evaluator can be set at most once")
```

**Comment by olafurpg** [comment]
Guess this belongs to a separate issue.
