### ISSUE TITLE
Feature request: manage copyright notice

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#705]
It would be nice if scalafmt could manage the copyright-notice at the top of a file.
 
Possible configuration options:
- `copyright.template: String` text to appear in copyright notice
- `copyright.regex: String` to determine if top comment matches template

**Comment by pjrt** [comment]
I have seen this in the wild so I can assume it is a wanted feature (we use scalastyle to check this atm). However it might be complicated getting this in scalafmt since it is a formatter instead of a yeller (unlike scalastyle). 
Here are some issues:

* What if the cc is there but it doesn't match? Do we add it or yell that "there is a thing here, but idk what it is"
* Since cc usually change by year (I have my editor just place "current year") this means we need to support some sort of "script" that can generate the correct time/whatever.
  * This affects the first point since now the cc will change at the turn of the year or whatever. Do we replace it with the new CC? Ignore it? Yell about it? How do we detect a change?

There may be more issue, but I definitely think supporting this (assuming we can get it right) is a wanted feature.

**Comment by olafurpg** [comment]
I had imagined that scalafmt would just automatically insert the correct cc if it's missing. If scalafmt is enforced during ci, then the unexpected diff will be the yelling.

It would be possible to implement this with the Rewrite system, you can specify a patch to replace the top comment token.

Type safe config supports multi-line strings with triple quotes so users could configure the cc text in scalafmt.conf. To update the year I imagined that you could just update the configured template and reformat. Alternatively, we could replace a term holder such as YEAR with the current year.

Wdyt?

**Comment by pjrt** [comment]
Atm I can't think of anything else that could change besides the year, so yeah, we can have a plain check for `%YEAR`. 

What if the user has something up there that isn't THE cc but it is similar enough (where similar enough = "some comment")? I guess we can just delete whatever it is and replace it with the cc. This will be the case in your scenario of "...update the configured template and reformat".

**Comment by olafurpg** [comment]
I had imaged using copyright.regex to determine if the top comment is cc. If there is a top level comment that doesn't match the regexp then we can insert a new comment with the cc leaving the other comment alone. If the regexp matches we can replace the comment. 

I'm still not sure if it's necessary to provide a YEAR placeholder since the user can just update the  cc template in scalafmt.conf instead.

**Comment by sjrd** [comment]
Please don't make a YEAR placeholder, as that would make builds non-reproducible.

**Comment by olafurpg** [comment]
I agree, I can see builds breaking on jan 1st. I think a config like this should be enough

```
copyright.template = """ Foobar 2017 asdf asdf
lorem ipasdfads
asdf
asdf
asdf"""
copyright.regex = "lorem ipasdf"
```
When you want to update the year to 2018 you can update the template. The same goes if you want to change the licence text.

**Comment by sirthias** [comment]
How would this relate to the [sbt-header](https://github.com/sbt/sbt-header) plugin?

**Comment by olafurpg** [comment]
@sirthias Cool! I didn't know about sbt-header. I imagine it would work very similarly, the header would be automatically inserted/updated on reformat according to .scalafmt.conf.

**Comment by sirthias** [comment]
Does it make sense though to duplicate the work that @hseeberger has already done with sbt-header?

IMHO the problem of managing file headers is solved and one could argue that it shouldn't be in scope for scalafmt.

**Comment by hseeberger** [comment]
I agree with @sirthias. sbt-header is widely used (not only for .scala files) and scalafmt should stay focussed on formatting of Scala sources.

**Comment by olafurpg** [comment]
Thank you for pitching in. I have been convinced that copyright headers is
better managed by a build integration tool such as sbt header.

It was not my intention to step on anyone's toes or undermine the work
that's been put into sbt header. I apologize.

**Comment by sirthias** [comment]
No problem, Olaf!
Thank you for scalafmt's awesomeness!

**Comment by hseeberger** [comment]
@olafurpg I don't think you stepped on anyone's toes. At least not on mine ;-) Even if you added copyright headers to scalafmt, that would not undermine the work put into sbt-header. So no worries at all!
