### ISSUE TITLE
Migrate to scalafix patches

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#706]
Scalafix recently added new awesome patches that support high-level tree operations and low-level token operations. SEe re's the relevant section https://github.com/scalacenter/scalafix/blob/master/core/src/main/scala/scalafix/util/Patch.scala#L33-L44

Benefits include:
- Easier to solve conflicts (some patches compose)
- Faster (TokenPatches are grouped by single token)

It would be nice to use these in scalafmt, this would involve refactoring the existing rewrites to use the new patches.

NOTE. It might be worth considering putting the patches in scalameta/contrib  and depend on them from here https://github.com/scalameta/scalameta/pull/624

**Comment by ysusuk** [comment]
Hi @olafurpg! will be glad to contribute on this. what do you think should be done? Replacing org.scalafmt.rewrite.Patch with scalafix.util.Patch (and its childs)

**Comment by olafurpg** [comment]
After more thinking I think that patches should belong in scalameta/contrib, a new module that just got merged yesterday. Otherwise, we end up duplicating code + bugs! I think we'll try to use the scalafix patch implementation as a base for the scalameta/contrib patch. I think it's best I do the migration to scalameta/contrib myself, since the scalafix patch implementation is still experimental and not thoroughly tested yet.

Instead, I think we can go ahead with https://github.com/olafurpg/scalafmt/issues/707 straight away and get immediate performance benefits. Would you be interested in that? Before doing the refactoring, it would be really useful to benchmark the current patch implementation when multiple rewrites are configured.

**Comment by olafurpg** [comment]
Fixed in #712
