### ISSUE TITLE
Feature request: AvoidInfix rewrite

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#709]
```diff
-          promise success "done"
+          promise.success("done")
```

I made progress on this rewrite in #517.

It got stuck because I was missing Patch.Add{Left,Right}, we can add those to the scalafmt patch impl

**Comment by ysusuk** [comment]
cool, you made a lot on AvoidInfix! do you think i can reuse most of the staff?

**Comment by olafurpg** [comment]
Yes, we can reuse most of that. I never merged it because the rewrite didn't handle the most tricky cases from scalatest where whitelisted infix operators were mixed together with blacklisted operators. This is really common in scalatest matcher code.

I would recommend you run the rewrite against projects such as akka that use scalatest matchers and look carefully at the diffs. For test data, you can clone this repo https://github.com/olafurpg/scala-repos It contains a ton of projects already formatted with scalafmt (branch name == version). I just pushed to branch 0.5.5

**Comment by olafurpg** [comment]
btw, note that there exists a FilterMatcher now so there's no need to add the one from the old PR

**Comment by ysusuk** [comment]
there is not such a branch (0.5.5) the highest is 0.5.1

**Comment by olafurpg** [comment]
Whoops, I maybe forgot to push. I'll do it when I get back to my desk.

**Comment by ysusuk** [comment]
not a problem) i'm having a hard time finding discrepencies %)

**Comment by olafurpg** [comment]
Just pushed to 0.5.5 https://github.com/olafurpg/scala-repos/tree/0.5.5

One challenge with this rewrite is to be guaranteed that it doesn't change the semantic of the program. One way to do this is to check the normalized ast is unchanged.

You can normalise a tree to remove all infix applications like this

```scala
@   q"1 + 1 + 2 should be ( 1) ".transform {
      case Term.ApplyInfix(lhs, op, targs, args) =>
       if (targs.nonEmpty) q"$lhs.$op[..$targs](..$args)"
       else q"$lhs.$op(..$args)"
    }
res7: Tree = 1.+(1).+(2).should(be(1))
@ res7.structure == q"1.+(1).+(2).should(be(1))".structure
res8: Boolean = true
```

**Comment by ysusuk** [comment]
hey @olafurpg! can you pls explain as well what did you mean by missing a  Patch.Add{Left,Right}

**Comment by ysusuk** [comment]
in a WordSpec, should

```scala
class StackSpec extends WordSpec {
  "A Stack" when {
    "empty" should {
      "be empty" in {
        // ...
      }
```
become
```scala
class StackSpec extends WordSpec {
  "A Stack".when {
    "empty" should {
      "be empty".in {
        // ...
      }
```

Shall we add to default excludes all WordSpec combinators? and combinators of other spec like test styles?

**Comment by ysusuk** [comment]
I will add here all the candidates for exclude:
`taggedAs`

**Comment by olafurpg** [comment]
I think it is good to whitelist the common operators in scalatest such as
when and in.

For the patch add left / right, I recall bumping into a situation like this

foo + 1 bar 2 + 3 kas 4

That should rewrite to

((foo + 1).bar(2) + 3).kas(4)

In order to handle the double open paren before foo we need to have a
Patch.AddLeft(token, toadd) combinator. The current replace implementation
cannot support merging 2 patches on the same token. You can see how it's
done in scalafix. Maybe it's OK to just copy the scalafix TokenPatch design
to scalafmt for now.

**Comment by ysusuk** [comment]
Cool! just let me add my example from akka repo, that i think struggles with the same problem
``` scala
Iterator from 1 map (Helpers.base64(_))
```
should become
``` scala
Iterator.from(1).map(Helpers.base64(_))
```
but is in the moment
```scala
Iterator.from(1) map (Helpers.base64(_))
```

**Comment by ysusuk** [comment]
i found a bunch of examples where rewrite was applied to one part of expression but not to the other, so i expect that first step will be to rewrite Patch from old style to new scalafix one!

**Comment by olafurpg** [comment]
Great! Sounds like you're on the right track, those were exactly the examples I was struggling with.

**Comment by ysusuk** [comment]
do you think i can reuse Patch of scalafix, and when contrib is ready we can switch?

**Comment by olafurpg** [comment]
I think that's OK.

**Comment by olafurpg** [comment]
Feel free to copy it over and adjust. I recommend we do that in a separate
pr from the avoid infix rewrite.

**Comment by ysusuk** [comment]
do you mean this one https://github.com/olafurpg/scalafmt/issues/706 :)

**Comment by olafurpg** [comment]
Correct.

**Comment by ysusuk** [comment]
should this be converted or not
```diff
-Iterator from 1 map (Helpers.base64(_))
+Iterator.from(1).map(Helpers.base64(_))
```

**Comment by olafurpg** [comment]
I think so yes. But range operators such as until / to / by should stay
infix I think.

**Comment by ysusuk** [comment]
not sure what to do in this case
```scala
foreach System.err.println
```not sure what to do in this case
```scala
foreach System.err.println
```

**Comment by olafurpg** [comment]
That is postfix syntax and should not be changed by AvoidInfix. I'd like to
handle it in a separate rewrite.

**Comment by ysusuk** [comment]
this guy doesn't parse

```scala
(a map (_.asInstanceOf[AnyRef]): _*))
```

fails with a failure `) expected but identifier found`

**Comment by ysusuk** [comment]
@olafurpg i misspelled issue number, i put #702 instead of #709. Initial pull request is there, pls take a look

**Comment by olafurpg** [comment]
Guess we can close  this 🎉
