### ISSUE TITLE
Unnecessary space for unary operator + _

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#710]
Seems like the fix for #697  bug was too aggressive, it adds spaces when it's not necessary

```diff
-    assert(!_evaluatorSet, "Evaluator can be set at most once")
+    assert(! _evaluatorSet, "Evaluator can be set at most once")
```

**Comment by pjrt** [comment]
I noticed this today. Would a check for `_` suffice? I believe `_` isn't allowed in infix methods so it should be fine.

**Comment by olafurpg** [comment]
Yes, a check for underscore is enough. Underscore is the only symbol that's
treated like an alphanumeric character in identifiers, according to the
spec.
