### ISSUE TITLE
Search state exploded for classes with large number of parameters

### ISSUE THREAD

**Issue by tgodzik** [olafurpg/scalafmt#719]
- **Version**: 0.5.5
- **Integration**: IntelliJ
- **Configuration**:
```
style = default

maxColumn = 120

docstrings = JavaDoc

align.openParenCallSite = false

assumeStandardLibraryStripMargin = true
```

Scalafmt fails with "SearchStateExploded around line 1" for:
```scala
class PropertyInfo18[E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, R: Manifest](name: String, flags: Long, impl: (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18) => R) extends DefPropertyInfo[E, (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18) => Boolean, (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18) => R, R](name, flags)
class PropertyInfo19[E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19, R: Manifest](name: String, flags: Long, impl: (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19) => R) extends DefPropertyInfo[E, (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19) => Boolean, (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19) => R, R](name, flags)
```

**Comment by olafurpg** [comment]
Thanks for reporting! If you run that in the tests and then open target/index.html you'll see a report like this

<img width="785" alt="screen shot 2017-02-08 at 11 06 11" src="https://cloud.githubusercontent.com/assets/1408093/22732496/b05127bc-edee-11e6-87ba-e3fb874578f1.png">

What's happening is that each argument in `impl` doubles the search space. This is because Term.Function is handled specially in router.scala. This should totally be fixable, but I can't promise when I'll look into it. I'm happy to help if you're interested in taking a stab at it yourself.

**Comment by olafurpg** [comment]
You can use bin packing for defn site to avoid the search state error

```scala
// scalafmt: { binPack.defnSite = true }
class PropertyInfo18[
    uE, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16,
    P17, P18, R: Manifest](name: String, flags: Long,
    impl: (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15,
        P16, P17, P18) => R)
    extends DefPropertyInfo[E,
                            (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11,
                                P12, P13, P14, P15, P16, P17, P18) => Boolean,
                            (E, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11,
                                P12, P13, P14, P15, P16, P17, P18) => R,
                            R](name, flags)
```

**Comment by mjaghouri** [comment]
I ran into the same error, but if I try the suggested solution, I get: 
`StyleMap:44 [e]: Invalid fields: defnSite`

Running with this config:

```
// project/plugins.sbt
libraryDependencies += "com.geirsson" %% "scalafmt-bootstrap" % "0.6.6"
// build.sbt
def latestScalafmt = "1.3.0"
commands += Command.args("scalafmt", "Run scalafmt cli.") {
  case (state, args) =>
    val Right(scalafmt) =
      org.scalafmt.bootstrap.ScalafmtBootstrap.fromVersion(latestScalafmt)
    scalafmt.main("--non-interactive" +: args.toArray)
    state
}
```

**Comment by olafurpg** [comment]
@mjaghouri Please see http://scalameta.org/scalafmt/#Deeplynestedcode for up-to-date recommendations.

**Comment by mjaghouri** [comment]
Thanks. It fixed most of the errors, but I still get the `Search state exploded` error in one file in which I have a method with 24 curried parameters (i.e., like `def curriedMethod(p1: xxx)(p2: yyy)...(p24: zzz)`.
Any suggestion?

**Comment by olafurpg** [comment]
That curried case probably merits an issue, I have never seen a function with so many curried parameter lists. It may be simple to fix, I'm happy to give pointers if someone is interested in taking a look.

**Comment by aandrieu** [comment]
The documentation linked in https://github.com/scalameta/scalafmt/issues/719#issuecomment-338165486 is broken.
Here is the new one: https://scalameta.org/scalafmt/docs/known-issues.html#deeply-nested-code
