### ISSUE TITLE
Feature request: scalafmt --pre-commit

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#720]
It would be nice if you could put in .git/hooks/pre-commit
```
scalafmt --pre-commit
```
and that would reformat changed files before each commit.

**Comment by pjrt** [comment]
Shouldn't that be the job of a pre-commit script? What would that flag do?

**Comment by olafurpg** [comment]
The pre commit hook would use this flag, eliminating the need for complex
bash scripts. It's possible to pipe the output of git diff name only into
--files but that doesn't handle project.excludeFilters and such.

**Comment by pjrt** [comment]
> git diff name only into
--files but that doesn't handle project.excludeFilters and such.

Couldn't we just make `--files` handle excludeFilters then? If we can get that then we could just make a `.sh` script that people can copy over into their pre-commit hooks.

**Comment by bjornj12** [comment]
@olafurpg My 2 cents on it is calling it --modified, i think that is what git calls it ?
with --files you also need to go through some extra work of filtering out non .scala files, working on this right now, can give better feedback soon.

This is a simple command i have gotten up to find all modified files and get it into scalafmt.

```
$ scalafmt -i -f $(git status --porcelain | cut -c 4- | tr '\n' ',')
```

Missing to exclude everything that is not .scala

For example is scalafmt erroring for me right now because in my modified is 

```
modified:   .scalafmt.conf
```

But @pjrt is kind of right though, that the pre-commit is really simple tbh, atleast for me as it is now, even though its slightly broken.

I think it would be more nice to have it as scalafmt flag, to give the user of scalamft the flexibility of where to use it, but a easy way to use it.

For example i am running a build tool called Pants, and i would love to later on to write a pants plugin that runs ``` scalafmt --modified ``` before compiling or something similar.

**Comment by bjornj12** [comment]
Im sorry for late update, but i got stuck at doing something else, 
I ended up with a simple command layer to apply scalafmt on all modified files, using bash

```
scalafmt -i -f $(git status --porcelain | grep -e .scala$ | cut -c 4- | tr '\n' ',')
```

Its not hugely battle tested, so there might still be some bugs with it. but it atleast got me started using a pre-commit hook for now. Thought it could be usefull for someone.

**Comment by pjrt** [comment]
@bjornj12 FYI: you can do `git diff --name-only` and it will give it the file path on its own (so no need to `cut` afterwards).

**Comment by olafurpg** [comment]
Sry for the slow response, been swamped at work lately.

`scalafmt --diff` currently uses `git diff --name-only` but that does not include unstaged files. Seems `--porcelain` is exactly what we want.

`--modified` is not 100% accurate since we want to reformat both modified files and new files. We can do two things

1. add `--pre-commit` flag that replaces current `--diff`. `--pre-commit` uses `--porcelain` behind the scenes. This flag is simple and inflexible but convenient, you should be able to put `scalafmt --pre-commit` in `.git/hooks/precommit` and move on with life.
2. add `--respect-project` flag that tells the `--files` flag to respect excludefilters. This offer more flexibillity at the cost of requiring more DYI solutions from the user.

WDYT?

**Comment by bjornj12** [comment]
@olafurpg 
going from what you said, 
i took a look at what you are doing in 'git diff..'

```
override def diff(branch: String): Seq[AbsoluteFile] = {
    exec(
      Seq(
        "git",
        "diff",
        "--name-only",
        "HEAD",
        branch
      )).lines.map { x =>
      AbsoluteFile.fromFile(new File(x), workingDirectory)
    }.toSeq
  }
```

it seems  to me like the <branch> is preventing the uncommitted files to be included.

`$git status`

```
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   src/scala/com/foo/api/models/FooModel.scala

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/scala/com/foo/api/services/FooService.scala
	modified:   src/scala/com/foo/api/services/BarService.scala
	modified:   src/scala/com/foo/api/models/BarModel.scala

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	src/scala/com/foo/api/models/Conversions.scala

```

`$ git diff --name-only HEAD master`
 gives empty results

`$ git diff --name-only HEAD`
gives:

```
src/scala/com/foo/api/models/FooModel.scala
src/scala/com/foo/api/models/BarModel.scala
src/scala/com/foo/api/services/FooService.scala
src/scala/com/foo/api/services/BarService.scala
```

It however skips the untracked files, but i dont know if we really want them in this case, since they havent been added to git yet.

**Comment by olafurpg** [comment]
The original implementation used `git diff --name-only HEAD` and it worked great on my machine. Unfortunately, it failed on the git version that was installed on CI.

> It however skips the untracked files, but i dont know if we really want them in this case, since they havent been added to git yet.

I think it makes sense to include untracked file.

**Comment by bjornj12** [comment]
we can move the discussion to here: https://github.com/olafurpg/scalafmt/pull/742

**Comment by olafurpg** [comment]
Seems like `diff --name-only` is insufficient because it includes removed files, see #759.
We either need to filter out non-existing files from `diff` or use `status --porcelain` to filter out removed files.

**Comment by bjornj12** [comment]
@olafurpg i have only tested this a little bit locally just now, but seems to work for this case.. 
git diff has an option called `--diff-filter` which we can use to remove deleted files

here is my local test:

```
$ git status
On branch scalafmt-playground
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bar.scala
	deleted:    foo.scala

no changes added to commit (use "git add" and/or "git commit -a")
```

```
$ git diff --name-only --diff-filter=d
src/scala/com/test/bar.scala
```

This is what we are looking for ?

**Comment by olafurpg** [comment]
Thanks everyone who contributed to the discussions. I think we are safe to close this issue, it should be possible to put `scalafmt --diff` in `.git/hooks/precommit`. If that is not the case, please open a bug report.

**Comment by caoilte** [comment]
Loving the new "scalafmt --diff" functionality. It's great for my dev workflow. Thanks everyone here who made it happen.

I've found one small problem, that has opened my eyes to the screaming void of pain that all pre-commit scripts seem to run into. I'd love your thoughts on it. It's at #882

**Comment by olafurpg** [comment]
Thanks @caoilte for contributing a fix!
