### ISSUE TITLE
Ugly implicit parameters location

### ISSUE THREAD

**Issue by d1egoaz** [olafurpg/scalafmt#723]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.4
- **Integration**: scalafmt command
- **Configuration**:
```
# options in https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/config/Settings.scala
style = IntelliJ
align.mixedOwners = false
align.openParenCallSite = false
align.openParenDefnSite = false
align.tokens = ["%", "%%"]
# align.tokens = ["%", "%%", "="] # enable this to format SBT files
binPack.literalArgumentLists = true
binPack.parentConstructors = false
binPackImportSelectors = true
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2
danglingParentheses = true
optIn.configStyleArguments = false # has to be false to make danglingParentheses work
docstrings = ScalaDoc
importSelectors = singleLine
includeCurlyBraceInSelectChains = false
#indentOperator.exclude = "^(::|&&|\\|\\|)$"
maxColumn = 120
newlines.alwaysBeforeCurlyBraceLambdaParams = false
newlines.penalizeSingleSelectMultiArgList = false
newlines.sometimesBeforeColonInMethodReturnType = true
optIn.annotationNewlines = true
optIn.breakChainOnFirstMethodDot = false
rewrite.rules = [AvoidInfix, SortImports, PreferCurlyFors, RedundantParens]
rewrite.redundantBraces.stringInterpolation = true
spaces.inImportCurlyBraces = false
unindentTopLevelOperators = true
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
  def xxxxxxxxxxxxxxxxxxxxxxx(yyyyyyyyyyyyyyy: Long)(
    implicit executionContext: ExecutionContext
  ): Future[Option[String]]
```

Expected, I would like the formatted output to look like this:
```scala
 def xxxxxxxxxxxxxxxxxxxxxxx(yyyyyyyyyyyyyyy: Long)
    (implicit executionContext: ExecutionContext): Future[Option[String]]
```
or
```scala
 def xxxxxxxxxxxxxxxxxxxxxxx(
    yyyyyyyyyyyyyyy: Long
  )(implicit executionContext: ExecutionContext): Future[Option[String]]
```

**Comment by pjrt** [comment]
`verticalMultilineAtDefinitionSite` kind looks like what you are looking for (it is a combination of your first example and the last one).

**Comment by olafurpg** [comment]
Yup, I was thinking the same. I like verticalMultilineAtDefinitionSite more and more, I'm thinking if we should put it into default. The default style was not designed for curried functions really, since I rarely use such long curried parameter lists.

**Comment by pjrt** [comment]
We could since, as far as I can tell, the Scala style guide doesn't mention how vertical multiline methods should be defined. So `verticalMultilineAtDefinitionSite` is as official as anything else :D

**Comment by olafurpg** [comment]
Moving the discussion about changing default to https://github.com/olafurpg/scalafmt/issues/732. 

@d1egoaz closing since verticalMultilineAtDefinitionSite is very similar to your last expected output.
