### ISSUE TITLE
Concatenated list indentation

### ISSUE THREAD

**Issue by nremond** [olafurpg/scalafmt#728]
Hi,

I'm creating this issue as suggested on Gitter by @olafurpg.

- **Version**: 0.5.6
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 120
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
lazy val ReleaseCmd = Command.command("release") { state =>
  "set elideOptions in client := Seq(\"-Xelide-below\", \"WARNING\")" ::
    "client/clean" ::
      "client/test" ::
        "server/clean" ::
          "server/test" ::
            "server/dist" ::
              "set elideOptions in client := Seq()" ::
                state
}
```

Expected, I would like the formatted output to look like this:
```scala
lazy val ReleaseCmd = Command.command("release") { state =>
  "set elideOptions in client := Seq(\"-Xelide-below\", \"WARNING\")" ::
    "client/clean" ::
    "client/test" ::
    "server/clean" ::
    "server/test" ::
    "server/dist" ::
    "set elideOptions in client := Seq()" ::
    state
}
```

Thank you

**Comment by olafurpg** [comment]
Thank you for reporting! I agree that the expected output is nicer, and it's more consistent with how


```scala
a +
  b +
  c
```

is formatted. I suspect the difference is caused by `::` being right-associative, so the AST is the reverse of `+`.

**Comment by olafurpg** [comment]
The way to solve this is probably to correctly handle the "expiration" of the 2 space indent from `::`.
