### ISSUE TITLE
Question: Don't align on braces

### ISSUE THREAD

**Issue by s12v** [olafurpg/scalafmt#738]
- **Version**: 0.5.6
- **Integration**: sbt
- **Configuration**:
```
style = IntelliJ or default
maxColumn = 120
optIn.configStyleArguments = true
```

Sorry, this probably was asked many times, but I couldn't find a solution.

I have a number of simple case classes like this:
```scala
case class Abc (property1: String, property2: String, ...)
```
I want them to be reformatted like this (1):
```scala
case class Abc(
  property1: String,
  property2: String,
  ...
)
```
but _sometimes_ they're turned into (2)
```scala
case class Abc (property1: String,
                property2: String)

```
Some classes are formatted like (1), some like (2), which makes it odd. I guess, scalafmt decides based on arguments, or class names (they are auto-generated and in fact often quite long), but I would like to always have (1) no matter what.
Could you please point me the right config?

Thanks!

**Comment by pjrt** [comment]
`align.openParenDefnSite = false` should force `1` always.

**Comment by s12v** [comment]
@pjrt, thanks!

**Comment by pjrt** [comment]
@s12v closing this since that fixed your issue.
