### ISSUE TITLE
Configuration/Configurable continuation indent for blocks curly brace

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#744]
This question has come up several times on gitter, see https://gitter.im/olafurpg/scalafmt?at=58ae783700c00c3d4f76ea49

No, it's not possible to configure the indentation for blocks and I'd prefer to keep it that way. 2 space continuation indent for blocks is pretty much universally accepted in the Scala ecosystem. It's one of a few things that everyone can agree on.

Opening this issue so google can index it.

**Comment by pjrt** [comment]
The Scala Style Guide specifies that 2-spaces should be used. 

http://docs.scala-lang.org/style/indentation.html
