### ISSUE TITLE
Search state exploded on medium-size large numbered list

### ISSUE THREAD

**Issue by dispalt** [olafurpg/scalafmt#745]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.6
- **Integration**: IntelliJ
- **Configuration**:

```

```

## Search state exploded

I am really making sure to isolate this file, but I am surprised it's throwing a search state exploded issue...  I am not really sure where to begin, luckily it's a fairly isolated example.

```scala
object SharedPolicyAmounts {
  val limits: Seq[Int] = Seq(
      2500, 3000, 4000, 5000, 7500, 10000, 15000,
      20000, 30000, 40000, 50000, 75000, 100000,
      150000, 200000, 300000, 400000, 500000, 750000,
      1000000
  )
}
```

**Comment by olafurpg** [comment]
Thanks! I am able to reproduce with the default settings. If anyone is interested in taking  a swing at this, see "debugging performance" here https://github.com/olafurpg/scalafmt#quick-help

**Comment by olafurpg** [comment]
This was caused by the combination of "config style" and the automatic bin packing of long argument lists of numeric literals (introduced in 0.5). The formatted output will look like this now

```
object SharedPolicyAmounts {
  val limits: Seq[Int] = Seq(
      2500, 3000, 4000, 5000, 7500, 10000, 15000, 20000, 30000, 40000, 50000,
      75000, 100000, 150000, 200000, 300000, 400000, 500000, 750000, 1000000
  )
}
```
