### ISSUE TITLE
No way to control alignment for type definitions

### ISSUE THREAD

**Issue by wlk** [olafurpg/scalafmt#747]
- **Version**: 0.5.6
- **Integration**: sbt
- **Configuration**:
```
style = IntelliJ
maxColumn = 120
danglingParentheses = true
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
align.openParenCallSite = false
align.openParenDefnSite = false
includeCurlyBraceInSelectChains = false
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
type MyTypeWithVeryLongName = (A,
                               Int,
                               Int,
                               Int,
                               Int,
                               String,
                               DateTime,
                               List[String],
                               List[String],
                               Int,
                               B,
                               C,
                               D,
                               E)
```

Expected, I would like the formatted output to look like this:
```scala
type MyTypeWithVeryLongName = (A,
  Int,
  Int,
  Int,
  Int,
  String,
  DateTime,
  List[String],
  List[String],
  Int,
  B,
  C,
  D,
  E)
```

Issue created after asking on gitter channel, it seems that scalafmt is missing setting to control alignment for type definitions. There are controls for function definitions and method calls

Expected configuration parameter:
```
align.openParenTypeDefnSite = false
continuationIndent.TypeDefnSite = 2
```

Please correct me if I'm wrong and it is in fact possible to control this

**Comment by olafurpg** [comment]
Thank you for reporting! There is currently no flag to control this, I think it makes most sense to include this as part of the `align.openParenDefnSite = false` flag. I suspect tuple type newlines are currently handled in some ad-hoc way. It'd be great to make it consistent with defn site parameter lists. 

A good place to start looking at this would be to follow the tutorial and see where the splits are coming from https://github.com/olafurpg/scalafmt/blob/master/Tutorial.md

**Comment by olafurpg** [comment]
Tuples were special cased which caused the align settings not to affect them, I've changed it so that tuples follow the align configuration now

```
// no align even for tuple types
align.openParenDefnSite = false
// no align even for tuple terms
align.openParenCallSite = false
```
