### ISSUE TITLE
Parse error with anonymous TimerTask and RedundantBraces rewrite error

### ISSUE THREAD

**Issue by Katrix-** [olafurpg/scalafmt#748]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.6
- **Integration**: IntelliJ
- **Configuration**:
```
rewrite.rules = [
  RedundantBraces
]
```
Tried to format file looking like this:

```scala
import java.util.{Timer, TimerTask}

class WithTimer {

  val timer = new Timer(true)

  def init(): Unit = {
    val task = new TimerTask {
      override def run(): Unit = println("Test")
    }

    //timer.schedule(task, 10)
  }
}
```

Received this error:

```scala
Parse error: <input>:8: error: illegal start of simple expression
val task = new TimerTask {
```

Uncommenting the line with the scheduling removes the error. Removing the `RedundantBraces` rewrite rule also fixes the issue.

**Comment by olafurpg** [comment]
Thanks for reporting! I guess RedundantBraces should not run when the only statement is a definition such as val, should be a simple fix.

**Comment by ysusuk** [comment]
hi @Katrix- , @olafurpg ! i'm not able to reproduce the issue %(
I put this test code into RedundantBraces.stat (commenting/uncommeting doesn't make any difference)

```
<<< #748: Parse error with anonymous TimerTask and RedundantBraces rewrite error
class WithTimer {

  val timer = new Timer(true)

  def init(): Unit = {
    val task = new TimerTask {
      override def run(): Unit = println("Test")
    }

    //timer.schedule(task, 10)
  }
}
>>>
class WithTimer {

  val timer = new Timer(true)

  def init(): Unit = {
    val task = new TimerTask {
      override def run(): Unit = println("Test")
    }

    //timer.schedule(task, 10)
  }
}
```
can the problem be only in 0.5.6 release?

**Comment by olafurpg** [comment]
@ysusuk I was able to reproduce the error by putting the test in a new suite with only `rewrite.rules=[Redun..]`. Here's the branch to reproduce https://github.com/olafurpg/scalafmt/compare/748?expand=1

If someone wants to take a swing at this, a good place to start would be to get this method to return false
https://github.com/olafurpg/scalafmt/blob/b52acf0d78ab7d677b6eb807b18486e9acf4111f/core/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala#L16
