### ISSUE TITLE
Gradle integration via Spotless

### ISSUE THREAD

**Issue by nedtwigg** [olafurpg/scalafmt#751]
[Spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-scalafmt-to-scala-files), a gradle formatting plugin, just added support for scalafmt.

```gradle
// build.gradle
plugins {
    id "com.diffplug.gradle.spotless" version "3.1.0"
}

spotless {
    scala {
        scalafmt()
        // optional: you can specify a specific version or config file
        scalafmt('0.5.1').configFile('scalafmt.conf')
    }
}
```

Spotless is a formatting "switchboard" that composes different formatters for different languages with different build systems. It has some value-add like up-to-date checking, respecting line-endings from .gitattributes, and automatically fixing minor idempotence glitches.

Would you be interested in a PR to https://olafurpg.github.io/scalafmt/#Installation

**Comment by jcranky** [comment]
I think you could just create the PR and let a contributor reply by accepting or denying it :)

**Comment by olafurpg** [comment]
@nedtwigg Cool project! Yes, I'd definitely be interested in listing your plugin to update the installation docs. The docs are creatd here https://github.com/olafurpg/scalafmt/blob/ee52411bef096d1ae30add30b7c5f9eafebb5fc9/readme/Installation.scalatex#L153 instructions to build the docs are here https://github.com/olafurpg/scalafmt#quick-help

BTW, there is another gradle plugin for scalafmt, see https://github.com/alenkacz/gradle-scalafmt could you maybe also include a link to that project, just for completeness?

**Comment by olafurpg** [comment]
I updated the docs to mention spotless @nedtwigg, thank you! https://olafurpg.github.io/scalafmt/#Gradle

**Comment by nedtwigg** [comment]
Great, thanks!  You beat me to the draw ;-)
