### ISSUE TITLE
[Request] Add named parameters for optional values rewrite rule

### ISSUE THREAD

**Issue by d1egoaz** [olafurpg/scalafmt#755]
Add names of arguments in a function call for `Option` values.

Given
```scala
case class Foo(name: String, bar = Option[Int])
```
Obtained, scalafmt formats code like this:
```scala
val fooName = "diego"
val f1 = Foo(name, None)
val f2 = Foo(name, Some(1))
```
Expected, I would like the formatted output to look like this:
```scala
val fooName = "diego"
val f1 = Foo(fooName, bar = None)
val f2 = Foo(fooName, bar = Some(1))
```
or add the named parameters for all arguments
```scala
val fooName = "diego"
val f1 = Foo(name = fooName, bar = None)
val f2 = Foo(name = fooName, bar = Some(1))
```

**Comment by diego-alvarez-hs** [comment]
it can also be used for boolean parameters

**Comment by olafurpg** [comment]
I agree this would be super nice but scalafmt is syntactic tool and doesn't have access to compiler info such as the name of a parameter. This belongs to another tool, I'm afraid.

**Comment by olafurpg** [comment]
Closing since this is impossible to implement.
