### ISSUE TITLE
Scalafmt should not produce uncompilable code

### ISSUE THREAD

**Issue by Atry** [olafurpg/scalafmt#756]
Scalafmt should preserve spaces between a type end with a symbol and the `#`

- **Version**: 0.5.6
- **Integration**: IntelliJ
- **Configuration**:
```
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
  trait TypeEndWithASymbol_! {
    type D
  }

  type A = TypeEndWithASymbol_!#D
```

Expected, I would like the formatted output to look like this:
```scala
  trait TypeEndWithASymbol_! {
    type D
  }

  type A = TypeEndWithASymbol_! #D
```

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce. This is a bug and will be fixed ASAP.

**Comment by eparejatobes** [comment]
The same sort of thing happens on the right; if the type *member* name starts with a symbol:

``` scala
abstract class Product {

  type On <: Category

  type ∗ <: On#Objects
  
  // (...)
}

// somewhere else
// the space here should be preserved
def doSomething[P <: Product]: P# ∗
```

Reopening? or a new issue would be better?

**Comment by olafurpg** [comment]
@eparejatobes can you please open a separate ticket? I'm able to reproduce, this should be a simple fix. Seems type projection requires a space before selecting symbolic type names.

**Comment by eparejatobes** [comment]
@olafurpg sure! #1116
