### ISSUE TITLE
Don't want a new line after enabling alwaysBeforeTopLevelStatements

### ISSUE THREAD

**Issue by d1egoaz** [olafurpg/scalafmt#774]
- **Version**: 0.5.8
- **Integration**: shell
- **Configuration**:
```
newlines.alwaysBeforeTopLevelStatements = true
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
  /** test */

  def foo(): Int = 0

  // bar

  def foo(): Int = 0
```

## Expectation

I would like the formatted output to look like this:
```scala
  /** test */
  def foo(): Int = 0

  // bar
  def foo(): Int = 0

```

**Comment by olafurpg** [comment]
cc/ @Daxten

**Comment by olafurpg** [comment]
This issue was fixed by @Daxten

**Comment by diego-alvarez-hs** [comment]
tyvm!
