### ISSUE TITLE
Expanding and sorting imports together produces invalid code

### ISSUE THREAD

**Issue by guymers** [olafurpg/scalafmt#775]
- **Version**: 0.5.8
- **Integration**: sbt
- **Configuration**:
```
rewrite.rules = [ExpandImportSelectors, SortImports]
```

## Steps

I ran scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```diff
-import scala.util.{Failure, Success, Try}
+import scala.util.Failure
+import scala.util.Success
+import scala.util.TryFailureSuccessTry
```
On a second run it formats code like this:
```diff
-import scala.util.Failure
-import scala.util.Success
-import scala.util.TryFailureSuccessTry
+import scala.util.FailureFailure
+import scala.util.SuccessSuccess
+import scala.util.TryFailureSuccessTryTryFailureSuccessTry
```

## Expectation

I would like the formatted output to look like this:
```diff
-import scala.util.{Failure, Success, Try}
+import scala.util.Failure
+import scala.util.Success
+import scala.util.Try
```

## Notes

The order of the rewrites makes no difference to the output.

**Comment by olafurpg** [comment]
Thank you for reporting. I guess the real issue is that these two rewrites are incompatible with each other and should run together. This should be fixable by failing fast when validating the configuration.

**Comment by ysusuk** [comment]
@guymers looks fancy =)
@olafurpg do you think it's possible to make them compatible? i will be happy to use them both on my own!

**Comment by olafurpg** [comment]
I think we want a more holistic approach to import management which is under discussion in #722
