### ISSUE TITLE
bring back spaces in parenthesis

### ISSUE THREAD

**Issue by cvogt** [olafurpg/scalafmt#780]
Could we consider bringing back spaces in parentheses :)? https://github.com/olafurpg/scalafmt/issues/116

I personally find it much easier to parse (i.e. read) code with spaces inside of parenthesis. To the point that this is a necessary requirement for me to be able to use scalafmt. Other people at @xdotai like this style as well and we use it across our code base. I know we seem to be in the minority about this aspect, but we'd really love to migrate from scalariform to scalafmt and this is blocking us right now :).

**Comment by olafurpg** [comment]
Can you please provide some small corpus of code that uses this style? It'd make it a lot easier to implement. The cbt sources use this option inconsistently IMO, taken from https://github.com/cvogt/cbt/blob/master/stage2/Stage2.scala#L12

```scala
    new Lib( context.logger ).loadRoot( context ).finalBuild( context.cwd )
...
    val paths = CbtPaths(args.cbtHome,args.cache)
```

More here https://github.com/cvogt/cbt/blob/master/stage2/BuildBuild.scala#L78-L80

What happens with `init()`, for example? is it `init( )`?

BTW, if you're interested in taking a swing at this yourself, the tutorial uses this exact option as a running example of how to hack on scalafmt https://github.com/olafurpg/scalafmt/blob/master/Tutorial.md

**Comment by cvogt** [comment]
CBT sources are manually indented at the moment. For manual indentation I actually tend to use alternating white-space between or not to help find matching parenthesis ;). But CBT is currently not consistent at all indeed. Milestone 1.0 is all about cleanup and ideally also adds scalafmt to CBT.

My preferred Scalariform settings include ```
        .setPreference(SpaceInsideParentheses, true)
        .setPreference(SpacesWithinPatternBinders, true)
        .setPreference(SpacesAroundMultiImports, true)
```

Empty parenthesis have no space inside of them there.

I can see if I can share some of our code at work.

Alternatively. Adding scalariform to any SBT build should turn up lots of examples, e.g. with these settings

```
import scalariform.formatter.preferences._
import com.typesafe.sbt.SbtScalariform.defaultScalariformSettings
import com.typesafe.sbt.SbtScalariform.ScalariformKeys
settings ++= (
    defaultScalariformSettings ++
      addCommandAlias("format", ";test:scalariformFormat ;scalariformFormat") ++
      (
      ScalariformKeys.preferences := ScalariformKeys.preferences.value
        .setPreference(AlignParameters, true)
        .setPreference(AlignArguments, true)
        .setPreference(AlignSingleLineCaseStatements, true)
        .setPreference(MultilineScaladocCommentsStartOnFirstLine, true)
        .setPreference(SpaceInsideParentheses, true)
        .setPreference(SpacesWithinPatternBinders, true)
        .setPreference(SpacesAroundMultiImports, true)
        .setPreference(DoubleIndentClassDeclaration, false)
    )
)
```
