### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lespea** [olafurpg/scalafmt#800]
Using scalafmt 0.6.1 (doesn't appear to be an issue in pre-6.0 versions) I am getting an java.lang.ArrayIndexOutOfBoundsException with the following example (excuse the odd code, I just tried getting the simplest version that would still cause the issue).

It's very finicky getting it to throw this exact error. For example if you change the `ParallelNum` reference in `mapAsyncUnordered` to a constant int, it won't throw.  If the "a" string isn't really long it also won't throw.  If you remove the flow assignment it won't throw.  Also doesn't appear to be an issue if you don't use `defaultWithAlign` (instead you get a search state explosion on line 37).

---------------------

Code
```scala
import akka.NotUsed
import akka.stream.SourceShape
import akka.stream.scaladsl._

import scala.concurrent.Future

import java.nio.file.{Files, Paths}

object Test {
  object RuntimeConsts {
    val ParallelNum = 8
  }

  object NodeStreamer {
    def makeIterator(t: (Int, Int) ⇒ String): Iterator[String] = ???
  }

  private val inFile = Paths.get("")
  Some(Files.newInputStream(inFile)) match {
    case Some(reader) ⇒
      val srcStream: Source[Int, NotUsed] =
        Source.single((3, 4)).flatMapConcat {
          case ((n1, n2)) ⇒
            Source.fromGraph(GraphDSL.create() { implicit b ⇒
              import GraphDSL.Implicits._

              val src = Source.fromIterator(
                () ⇒
                  NodeStreamer.makeIterator(
                    (n, p) ⇒ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                ))

              val procStream = Flow[String].mapAsyncUnordered(RuntimeConsts.ParallelNum) {
                case _ ⇒ Future(43)
              }

              val flow = src ~> procStream
              SourceShape(flow.outlet)
            })
        }
  }
}
```

.scalafmt.conf
```ini
style = defaultWithAlign
```

**Comment by olafurpg** [comment]
Thank you for reporting! The array index out of bounds happened because the search state exploded, breaking some assumptions in the vertical alignment algorithm . It seems to be caused by `binPack.lambdaParameter=false`, which got changed in 0.6.1. You can get the 0.6.0 behavior in by setting the option to true. I've opened #802

**Comment by lespea** [comment]
Great, thanks for the quick update!
