### ISSUE TITLE
newlines.alwaysBeforeTopLevelStatements; Annotations

### ISSUE THREAD

**Issue by Daxten** [olafurpg/scalafmt#806]
## Problem

Scalafmt formats code like this:
```scala
@Singleton

class Test {

}
```

## Expectation

I would like the formatted output to look like this:
```scala
@Singleton
class Test {

}
```
## Notes

Will fix this myself at the weekend

**Comment by alexarchambault** [comment]
Self-contained repro: https://gist.github.com/alexarchambault/822a8e04026fafde5d8d3b849c30fbcb

**Comment by Daxten** [comment]
#820
