### ISSUE TITLE
@annotations in front of `def` should be kept there

### ISSUE THREAD

**Issue by sjrd** [olafurpg/scalafmt#97]
Original:
```scala
  @inline def Rule = raw.CSSRule
```

Scalafmt:
```scala
  @inline
  def Rule = raw.CSSRule
```

I would like the input to look like this:
```scala
  @inline def Rule = raw.CSSRule
```
at least if the everything up to `=` stays on one line.

Although, if the original had `@inline` on a separate line, I'd like scalafmt to keep it on a separate line.

Using
* 0.1.1
* default

**Comment by olafurpg** [comment]
I have a fix that allows space after annotations if the annotation is only a single identifier `@identifier` (no `@annotation(foo)`) AND the right hand side fits in a single line up to either the first `=` or the last token of the statement (for example `@root class Token`). This at least allows single line definitions of common annotations like `@inline`, `@tailrec`, etc.

**Comment by olafurpg** [comment]
If the original code is 

```
@inline
def foo = 2
```
then the formatter will keep the newline.
